SELECT count(*) FROM TELS_BULK_DEALERS;
SELECT * FROM TELS_OGPO_POSITION;
SELECT * FROM TELS_OGPT_PARTICIPANT;
SELECT * FROM TELS_CLCU_CUSTOMER;


SELECT *
FROM TELS_BULK_DEALERS;

SELECT 
  dlr.FILENAME, 
  dlr.RECORD_NUMBER,
  dlr.PARTNER_CODE,
  dlr.PARTNER_TYPE,
  SUBSTR(dlr.PARTNER_TYPE, 0, instr(dlr.PARTNER_TYPE,' - ')-1) PARTNER_GROUP,
  SUBSTR(dlr.PARTNER_TYPE, instr(dlr.PARTNER_TYPE,' - ')+3) PARTNER_LEVEL,
  SUBSTR(dlr.ROLE2, instr(dlr.ROLE2,' - ')+3) PAYMENT_TYPE,
  dlr.ROLE2
FROM TELS_BULK_DEALERS dlr
--WHERE dlr.FILENAME = '$$filename'
;

SELECT 
  dlr.FILENAME, 
  dlr.RECORD_NUMBER,
--  dlr.PARTNER_CODE,
--  dlr.PARTNER_TYPE,
--  dlr.PARTNER_GROUP,
--  dlr.PARTNER_LEVEL,
--  dlr.PAYMENT_TYPE,
  CASE WHEN (SELECT Count(*) FROM TELS_BULK_DEALERS dlr2 WHERE dlr2.FILENAME = dlr.FILENAME AND dlr2.PARTNER_CODE = dlr.PARTNER_CODE AND dlr2.PARTNER_LEVEL = 'Premise')>0 THEN 1 ELSE 0 END PREMISE_FLAG,
  CASE WHEN (SELECT Count(*) FROM TELS_BULK_DEALERS dlr2 WHERE dlr2.FILENAME = dlr.FILENAME AND dlr2.PARTNER_CODE = dlr.PARTNER_CODE AND dlr2.PARTNER_LEVEL = 'Distributor')>0 THEN 1 ELSE 0 END DISTRIBUTOR_FLAG,
  CASE WHEN (SELECT Count(*) FROM TELS_BULK_DEALERS dlr2 WHERE dlr2.FILENAME = dlr.FILENAME AND dlr2.PARTNER_CODE = dlr.PARTNER_CODE AND dlr2.PARTNER_LEVEL = 'Super-Distributor')>0 THEN 1 ELSE 0 END SUPDISTRIBUTOR_FLAG
FROM TELS_BULK_DEALERS dlr
WHERE 
  dlr.PARTNER_LEVEL IN('Super-Distributor','Distributor')
  AND dlr.PAYMENT_TYPE = 'Pay Point'
--  AND dlr.FILENAME = '$$filename'
;

SELECT 
  dlr.FILENAME, 
  dlr.RECORD_NUMBER,
  'OGPT,OGPO,CLCU,PLMC' ELIGIBILITY
FROM TELS_BULK_DEALERS dlr
WHERE 
  dlr.PAYMENT_TYPE = 'Pay Point'
--  AND dlr.FILENAME = '$$filename'
;

SELECT 
  dlr.FILENAME,
  dlr.RECORD_NUMBER,
  'CLCU' ELIGIBILITY
FROM
    (SELECT 
      dlr.FILENAME, 
      dlr.PARTNER_CODE, 
      count(*) NUM_ENTITIES
    FROM TELS_BULK_DEALERS dlr
    --WHERE 
    --  dlr.FILENAME = '$$filename'
    GROUP BY
      dlr.FILENAME, 
      dlr.PARTNER_CODE) premises 
    JOIN TELS_BULK_DEALERS dlr ON
      dlr.FILENAME = premises.FILENAME
      AND dlr.PARTNER_CODE = premises.PARTNER_CODE
WHERE
  premises.NUM_ENTITIES = 1
;

SELECT * FROM CS_BUSINESSUNIT@TC_LINK;