SELECT * FROM TELS_CORE_DATA_SUMMARY;

--Landing Pad processes in the last 24hours;
SELECT BATCHPROCESSDATE, 
  CASE WHEN FILEHANDLERNAME LIKE '%inbound%' THEN 'Inbound' WHEN FILEHANDLERNAME LIKE '%outbound%' THEN 'Outbound' END DIRECTION, 
  SOURCEFILENAME SOURCEFILE, 
  REPLACE(TARGETFILENAME_1,',','<br>') TARGETFILE, 
  REPLACE(TARGETRECORDCOUNT_1,',','<br>') TARGETRECORDCOUNT, 
  ERRORFILENAME, ERRORCOUNT 
FROM TELS_CORE_DATA_SUMMARY
WHERE TO_DATE(BATCHPROCESSDATE,'YYYY/MM/DD HH24:MI:SS') > SYSDATE - 1
  AND BATCHPROCESSDATE LIKE '2019%'
ORDER BY BATCHPROCESSDATE DESC;