/********************************************************************
  ** TELS_PREMISE_VIEW
  **
  ** Version: 1.0
  ** Author: Simon Marsh
  ** Created: October 2018
  ** Description:
  **
  ** Date       Modified By   Description
  ** ------------------------------------------------------------------
  ** 201801008   Simon Marsh   Initial Version
  ********************************************************************/
  CREATE OR REPLACE VIEW TELS_PREMISE_PARTNER_VIEW AS(
    SELECT
      BU.NAME BUSINESSUNIT
    , CU.EFFECTIVESTARTDATE
    , CU.EFFECTIVEENDDATE
    , CL.CLASSIFIERSEQ
    , CL.CLASSIFIERID
    , CL.NAME
    , CL.DESCRIPTION
    , CU.GENERICATTRIBUTE1
    , CU.GENERICATTRIBUTE2
    , CU.GENERICATTRIBUTE3
    , CU.GENERICATTRIBUTE4
    , CU.GENERICATTRIBUTE5
    , CU.GENERICATTRIBUTE6
    , CU.GENERICATTRIBUTE7
    , CU.GENERICATTRIBUTE8
    , CU.GENERICATTRIBUTE9
    , CU.GENERICATTRIBUTE10
    , CU.GENERICATTRIBUTE11
    , CU.GENERICATTRIBUTE12
    , CU.GENERICATTRIBUTE13
    , CU.GENERICATTRIBUTE14
    , CU.GENERICATTRIBUTE15
    , CU.GENERICATTRIBUTE16
    , CU.GENERICNUMBER1
    , CU.GENERICNUMBER2
    , CU.GENERICNUMBER3
    , CU.GENERICNUMBER4
    , CU.GENERICNUMBER5
    , CU.GENERICNUMBER6
    , CU.GENERICDATE1
    , CU.GENERICDATE2
    , CU.GENERICDATE3
    , CU.GENERICDATE4
    , CU.GENERICDATE5
    , CU.GENERICDATE6
    , CU.GENERICBOOLEAN1
    , CU.GENERICBOOLEAN2
    , CU.GENERICBOOLEAN3
    , CU.GENERICBOOLEAN4
    , CU.GENERICBOOLEAN5
    , CU.GENERICBOOLEAN6
    FROM CS_CUSTOMER CU
    JOIN CS_CLASSIFIER CL
    ON CL.CLASSIFIERSEQ = CU.CLASSIFIERSEQ
    AND CL.TENANTID = 'TELS'
    AND CL.REMOVEDATE = TO_DATE('01/01/2200', 'dd/mm/yyyy')
    JOIN CS_CATEGORY_CLASSIFIERS CC
    ON CC.CLASSIFIERSEQ = CL.CLASSIFIERSEQ
    AND CC.TENANTID = 'TELS'
    AND CC.REMOVEDATE = TO_DATE('01/01/2200', 'dd/mm/yyyy')
    JOIN CS_CATEGORYTREE CT
    ON CT.CATEGORYTREESEQ = CC.CATEGORYTREESEQ
    AND CT.TENANTID = 'TELS'
    AND CT.REMOVEDATE = TO_DATE('01/01/2200', 'dd/mm/yyyy')
    JOIN CS_BUSINESSUNIT BU
    ON BU.MASK = CL.BUSINESSUNITMAP
    WHERE (1=1)
    AND CU.TENANTID = 'TELS'
    AND CU.REMOVEDATE = TO_DATE('01/01/2200', 'dd/mm/yyyy')
);