/********************************************************************
  ** TELS_TEMPLATE_TXSTAG_TXN
  **
  ** Version: 1.0
  ** Author: Simon Marsh
  ** Created: June 2018
  ** Description:
  **
  ** Date       Modified By   Description
  ** ------------------------------------------------------------------
  ** 20180619   Simon Marsh   Initial Version
  ********************************************************************/
--DROP TABLE TELS_TEMPLATE_TXSTAG_TXN;
CREATE TABLE TELS_TEMPLATE_TXSTAG_TXN
(
    FILENAME                  varchar2(255) NOT NULL,
    RECORDNUMBER              number(10) NOT NULL,
    BATCHPROCESSDATE          varchar2(255),
    ORDERID                   varchar2(255),
    LINENUMBER                varchar2(255),
    SUBLINENUMBER             varchar2(255),
    EVENTTYPEID               varchar2(255),
    ACCOUNTINGDATE            varchar2(255),
    PRODUCTID                 varchar2(255),
    PRODUCTNAME               varchar2(255),
    PRODUCTDESCRIPTION        varchar2(255),
    VALUE                     varchar2(255),
    UNITTYPEFORVALUE          varchar2(255),
    NUMBEROFUNITS             varchar2(255),
    UNITVALUE                 varchar2(255),
    UNITTYPEFORUNITVALUE      varchar2(255),
    COMPENSATIONDATE          varchar2(255),
    PAYMENTTERMS              varchar2(255),
    PONUMBER                  varchar2(255),
    CHANNEL                   varchar2(255),
    ALTERNATEORDERNUMBER      varchar2(255),
    DATASOURCE                varchar2(255),
    NATIVECURRENCY            varchar2(255),
    NATIVECURRENCYAMOUNT      varchar2(255),
    DISCOUNTPERCENT           varchar2(255),
    DISCOUNTTYPE              varchar2(255),
    BILLTOCUSTID              varchar2(255),
    BILLTOCONTACT             varchar2(255),
    BILLTOCOMPANY             varchar2(255),
    BILLTOAREACODE            varchar2(255),
    BILLTOPHONE               varchar2(255),
    BILLTOFAX                 varchar2(255),
    BILLTOADDRESS1            varchar2(255),
    BILLTOADDRESS2            varchar2(255),
    BILLTOADDRESS3            varchar2(255),
    BILLTOCITY                varchar2(255),
    BILLTOSTATE               varchar2(255),
    BILLTOCOUNTRY             varchar2(255),
    BILLTOPOSTALCODE          varchar2(255),
    BILLTOINDUSTRY            varchar2(255),
    BILLTOGEOGRAPHY           varchar2(255),
    SHIPTOCUSTID              varchar2(255),
    SHIPTOCONTACT             varchar2(255),
    SHIPTOCOMPANY             varchar2(255),
    SHIPTOAREACODE            varchar2(255),
    SHIPTOPHONE               varchar2(255),
    SHIPTOFAX                 varchar2(255),
    SHIPTOADDRESS1            varchar2(255),
    SHIPTOADDRESS2            varchar2(255),
    SHIPTOADDRESS3            varchar2(255),
    SHIPTOCITY                varchar2(255),
    SHIPTOSTATE               varchar2(255),
    SHIPTOCOUNTRY             varchar2(255),
    SHIPTOPOSTALCODE          varchar2(255),
    SHIPTOINDUSTRY            varchar2(255),
    SHIPTOGEOGRAPHY           varchar2(255),
    OTHERTOCUSTID             varchar2(255),
    OTHERTOCONTACT            varchar2(255),
    OTHERTOCOMPANY            varchar2(255),
    OTHERTOAREACODE           varchar2(255),
    OTHERTOPHONE              varchar2(255),
    OTHERTOFAX                varchar2(255),
    OTHERTOADDRESS1           varchar2(255),
    OTHERTOADDRESS2           varchar2(255),
    OTHERTOADDRESS3           varchar2(255),
    OTHERTOCITY               varchar2(255),
    OTHERTOSTATE              varchar2(255),
    OTHERTOCOUNTRY            varchar2(255),
    OTHERTOPOSTALCODE         varchar2(255),
    OTHERTOINDUSTRY           varchar2(255),
    OTHERTOGEOGRAPHY          varchar2(255),
    REASONID                  varchar2(255),
    COMMENTS                  varchar2(255),
    BUSINESSUNITNAME          varchar2(255),
    GENERICATTRIBUTE1         varchar2(255),
    GENERICATTRIBUTE2         varchar2(255),
    GENERICATTRIBUTE3         varchar2(255),
    GENERICATTRIBUTE4         varchar2(255),
    GENERICATTRIBUTE5         varchar2(255),
    GENERICATTRIBUTE6         varchar2(255),
    GENERICATTRIBUTE7         varchar2(255),
    GENERICATTRIBUTE8         varchar2(255),
    GENERICATTRIBUTE9         varchar2(255),
    GENERICATTRIBUTE10        varchar2(255),
    GENERICATTRIBUTE11        varchar2(255),
    GENERICATTRIBUTE12        varchar2(255),
    GENERICATTRIBUTE13        varchar2(255),
    GENERICATTRIBUTE14        varchar2(255),
    GENERICATTRIBUTE15        varchar2(255),
    GENERICATTRIBUTE16        varchar2(255),
    GENERICATTRIBUTE17        varchar2(255),
    GENERICATTRIBUTE18        varchar2(255),
    GENERICATTRIBUTE19        varchar2(255),
    GENERICATTRIBUTE20        varchar2(255),
    GENERICATTRIBUTE21        varchar2(255),
    GENERICATTRIBUTE22        varchar2(255),
    GENERICATTRIBUTE23        varchar2(255),
    GENERICATTRIBUTE24        varchar2(255),
    GENERICATTRIBUTE25        varchar2(255),
    GENERICATTRIBUTE26        varchar2(255),
    GENERICATTRIBUTE27        varchar2(255),
    GENERICATTRIBUTE28        varchar2(255),
    GENERICATTRIBUTE29        varchar2(255),
    GENERICATTRIBUTE30        varchar2(255),
    GENERICATTRIBUTE31        varchar2(255),
    GENERICATTRIBUTE32        varchar2(255),
    GENERICNUMBER1            varchar2(255),
    UNITTYPEFORGENERICNUMBER1 varchar2(255),
    GENERICNUMBER2            varchar2(255),
    UNITTYPEFORGENERICNUMBER2 varchar2(255),
    GENERICNUMBER3            varchar2(255),
    UNITTYPEFORGENERICNUMBER3 varchar2(255),
    GENERICNUMBER4            varchar2(255),
    UNITTYPEFORGENERICNUMBER4 varchar2(255),
    GENERICNUMBER5            varchar2(255),
    UNITTYPEFORGENERICNUMBER5 varchar2(255),
    GENERICNUMBER6            varchar2(255),
    UNITTYPEFORGENERICNUMBER6 varchar2(255),
    GENERICDATE1              varchar2(255),
    GENERICDATE2              varchar2(255),
    GENERICDATE3              varchar2(255),
    GENERICDATE4              varchar2(255),
    GENERICDATE5              varchar2(255),
    GENERICDATE6              varchar2(255),
    GENERICBOOLEAN1           varchar2(255),
    GENERICBOOLEAN2           varchar2(255),
    GENERICBOOLEAN3           varchar2(255),
    GENERICBOOLEAN4           varchar2(255),
    GENERICBOOLEAN5           varchar2(255),
    GENERICBOOLEAN6           varchar2(255)
);