DROP MATERIALIZED VIEW TELS_RCRM_MV_ATTRIBUTE;

DROP TABLE TELS_RCRM_MV_ATTRIBUTE CASCADE CONSTRAINTS;

CREATE TABLE TELS_RCRM_MV_ATTRIBUTE
(
    FILENAME VARCHAR2(255) NOT NULL
  , BATCHPROCESSDATE DATE NOT NULL
  , RECORDNUMBER NUMBER(15) NOT NULL
  , IS_FILTERED NUMBER(1) NOT NULL
  , ORDER_NUMBER VARCHAR2(30)
  , ORDER_SUB_TYPE VARCHAR2(30)
  , STATUS_HEADER VARCHAR2(30)
  , ROW_ID VARCHAR2(15)
  , ATTRIBUTE_ROW_ID VARCHAR2(15)
  , ATTRIBUTE_ACTION_CODE VARCHAR2(30)
  , ATTRIBUTE_DISPLAY_NAME VARCHAR2(100)
  , ATTRIBUTE_VALUE VARCHAR2(255)
)
TABLESPACE TELS_TRANSFORMS;

--DROP MATERIALIZED VIEW TELS_RCRM_MV_ATTRIBUTE;

CREATE MATERIALIZED VIEW TELS_RCRM_MV_ATTRIBUTE
ON PREBUILT TABLE
REFRESH COMPLETE
ON DEMAND
AS
SELECT
    FILENAME
  , BATCHPROCESSDATE
  , RECORDNUMBER
  , IS_FILTERED
  , ORDER_NUMBER
  , ORDER_SUB_TYPE
  , STATUS_HEADER
  , ROW_ID
  , ATTRIBUTE_ROW_ID
  , ATTRIBUTE_ACTION_CODE
  , ATTRIBUTE_DISPLAY_NAME
  , ATTRIBUTE_VALUE
FROM TELS_STAGE_RCRM
WHERE (1=1)
AND ATTRIBUTE_ROW_ID IS NOT NULL
;

BEGIN
  DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_ATTRIBUTE', METHOD => 'C' );
END;

--CREATE UNIQUE INDEX TELS_RCRM_MV_ATTRIBUTE_PK ON TELS_RCRM_MV_ATTRIBUTE
--(ORDER_NUMBER,STATUS_HEADER,ROW_ID,ATTRIBUTE_ROW_ID);

--ALTER TABLE TELS_RCRM_MV_ATTRIBUTE ADD (
--  CONSTRAINT TELS_RCRM_MV_ATTRIBUTE_PK
--  PRIMARY KEY (ORDER_NUMBER,STATUS_HEADER,ROW_ID,ATTRIBUTE_ROW_ID)
--  USING INDEX TELS_RCRM_MV_ATTRIBUTE_PK);

--CREATE UNIQUE INDEX TELS_RCRM_MV_ATTRIBUTE_AK ON TELS_RCRM_MV_ATTRIBUTE
--(FILENAME,BATCHPROCESSDATE,RECORDNUMBER);

--ALTER TABLE TELS_RCRM_MV_ATTRIBUTE ADD (
--  CONSTRAINT TELS_RCRM_MV_ATTRIBUTE_AK
--  UNIQUE (FILENAME,BATCHPROCESSDATE,RECORDNUMBER)
--  USING INDEX TELS_RCRM_MV_ATTRIBUTE_AK);

DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_1;

CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_1 ON TELS_RCRM_MV_ATTRIBUTE
(FILENAME,ROW_ID,ATTRIBUTE_ROW_ID,ATTRIBUTE_DISPLAY_NAME,ATTRIBUTE_ACTION_CODE)
TABLESPACE TELS_TRANSFORMS
;

DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_2;

CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_2 ON TELS_RCRM_MV_ATTRIBUTE
(FILENAME,ROW_ID,ATTRIBUTE_DISPLAY_NAME,ATTRIBUTE_ACTION_CODE)
TABLESPACE TELS_TRANSFORMS
;

DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_3;

CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_3 ON TELS_RCRM_MV_ATTRIBUTE
(ROW_ID,ATTRIBUTE_DISPLAY_NAME,FILENAME)
TABLESPACE TELS_TRANSFORMS
;

DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_4;

CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_4 ON TELS_RCRM_MV_ATTRIBUTE
(ROW_ID,FILENAME,ATTRIBUTE_ACTION_CODE)
TABLESPACE TELS_TRANSFORMS
;

--DROP INDEX TELS_RCRM_MV_IX_1;

--CREATE INDEX TELS_RCRM_MV_IX_1 ON TELS_RCRM_MV_ATTRIBUTE
--(FILENAME,ROW_ID,ORDER_NUMBER,ATTRIBUTE_DISPLAY_NAME)
--TABLESPACE TELS_TRANSFORMS
--;

--DROP INDEX TELS_RCRM_MV_IX_TEST;

--CREATE UNIQUE INDEX TELS_RCRM_MV_IX_TEST ON TELS_RCRM_MV_ATTRIBUTE
--(FILENAME,ROW_ID,ATTRIBUTE_DISPLAY_NAME)
--TABLESPACE TELS_TRANSFORMS
--;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(
      OWNNAME           => 'TELSADMIN'
    , TABNAME           => 'TELS_RCRM_MV_ATTRIBUTE'
    , ESTIMATE_PERCENT  => NULL
    , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
    , DEGREE            => NULL
    , CASCADE           => TRUE
    , NO_INVALIDATE     => FALSE
    );
END;
