DROP TABLE TELS_CWP_PRODUCTPRICE_PRESTG CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_PRODUCTPRICE_PRESTG
(
  FILENAME                        VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE                DATE          NOT NULL,
  RECORDNUMBER                    NUMBER(15)    NOT NULL,
  IS_FILTERED                     NUMBER(1)     NOT NULL,
  SOURCE_SYSTEM                   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_PRODUCT_SPEC_KEY  VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CHARGE_KEY        VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY               VARCHAR2(255 BYTE),
  SOURCE_START_DATE               VARCHAR2(255 BYTE),
  SOURCE_END_DATE                 VARCHAR2(255 BYTE),
  RATE_IDENTIFIER                 VARCHAR2(255 BYTE),
  PRICE                           VARCHAR2(255 BYTE),
  CHARGE_NAME                     VARCHAR2(255 BYTE),
  CHARGE_DESCRIPTION              VARCHAR2(255 BYTE),
  CURRENCY_NAME                   VARCHAR2(255 BYTE),
  BILLING_SPEC_ID                 VARCHAR2(255 BYTE),
  CHARGE_PERIODICITY              VARCHAR2(255 BYTE),
  IS_BILL_IN_ADVANCE              VARCHAR2(255 BYTE),
  TAX_TREATMENT                   VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP            VARCHAR2(255 BYTE),
  B2B_KEY                         VARCHAR2(255 BYTE),
  B2B_BATCH_ID                    VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_PRESTAGE_PRODPRICE_PK ON TELS_CWP_PRODUCTPRICE_PRESTG
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
