DROP TABLE TELS_CWP_PRODUCTOFFER_STAGE CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_PRODUCTOFFER_STAGE
(
  FILENAME                  VARCHAR2(255 BYTE)  NOT NULL,
  BATCHPROCESSDATE          DATE                NOT NULL,
  RECORDNUMBER              NUMBER(15)          NOT NULL,
  IS_FILTERED               NUMBER(1)           NOT NULL,
  B2B_KEY                   VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP      VARCHAR2(255 BYTE),
  B2B_BATCH_ID              VARCHAR2(255 BYTE),
  SOURCE_SYSTEM             VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY         VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_PARENT_KEY  VARCHAR2(255 BYTE),
  PRODUCTOFFER_NAME         VARCHAR2(255 BYTE),
  PRODUCTOFFER_TYPE         VARCHAR2(255 BYTE),
  DESCRIPTION               VARCHAR2(255 BYTE),
  SOURCE_EFF_START_DT       VARCHAR2(255 BYTE),
  SOURCE_EFF_END_DT         VARCHAR2(255 BYTE),
  GL_CODE                   VARCHAR2(255 BYTE),
  GL_DESCRIPTION            VARCHAR2(255 BYTE),
  GL_PERF_OBLIGATION        VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_STAGE_PRODUCTOFFR_PK ON TELS_CWP_PRODUCTOFFER_STAGE
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
