DROP TABLE TELS_CWP_OPPORTUNITY_STAGE CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_OPPORTUNITY_STAGE
(
  FILENAME                       VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE               DATE           NOT NULL,
  RECORDNUMBER                   NUMBER(15)     NOT NULL,
  IS_FILTERED                    NUMBER(1)      NOT NULL,
  B2B_KEY                        VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP           VARCHAR2(255 BYTE),
  B2B_BATCH_ID                   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM                  VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CUSTOMER_KEY     VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY              VARCHAR2(255 BYTE),
  IS_DELETED                     VARCHAR2(255 BYTE),
  IS_PRIVATE                     VARCHAR2(255 BYTE),
  OPPORTUNITY_NAME               VARCHAR2(255 BYTE),
  STAGE_NAME                     VARCHAR2(255 BYTE),
  AMOUNT                         VARCHAR2(255 BYTE),
  PROBABILITY                    VARCHAR2(255 BYTE),
  EXPECTED_REVENUE               VARCHAR2(255 BYTE),
  TOTAL_OPPORTUNITY_QUANTITY     VARCHAR2(255 BYTE),
  CLOSE_DATE                     VARCHAR2(255 BYTE),
  OPPORTUNITY_TYPE               VARCHAR2(255 BYTE),
  NEXT_STEP                      VARCHAR2(255 BYTE),
  LEAD_SOURCE                    VARCHAR2(255 BYTE),
  IS_CLOSED                      VARCHAR2(255 BYTE),
  IS_WON                         VARCHAR2(255 BYTE),
  CAMPAIGN_ID                    VARCHAR2(255 BYTE),
  OWNER_DNO                      VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CREATED_DATE     VARCHAR2(255 BYTE),
  FISCAL_QUARTER                 VARCHAR2(255 BYTE),
  FISCAL_YEAR                    VARCHAR2(255 BYTE),
  FISCAL                         VARCHAR2(255 BYTE),
  CIDN                           VARCHAR2(255 BYTE),
  DESCRIPTION                    VARCHAR2(255 BYTE),
  END_DATE                       VARCHAR2(255 BYTE),
  OFFER_NAME                     VARCHAR2(255 BYTE),
  OPPORTUNITY_CONTACT_PHONE_1    VARCHAR2(255 BYTE),
  OPPORTUNITY_NUMBER             VARCHAR2(255 BYTE),
  OPPORTUNITY_SOURCE             VARCHAR2(255 BYTE),
  ARCHETYPE                      VARCHAR2(255 BYTE),
  BILLING_SOLUTION               VARCHAR2(255 BYTE),
  CHANGE_TO_ABR_CALC             VARCHAR2(255 BYTE),
  COMPETITOR                     VARCHAR2(255 BYTE),
  CONFIDENCE_LEVEL               VARCHAR2(255 BYTE),
  CONTRACT_TERM                  VARCHAR2(255 BYTE),
  CONTRACT_TERMS                 VARCHAR2(255 BYTE),
  CONTRACT_TYPE                  VARCHAR2(255 BYTE),
  IS_CUSTOMER_ACCEPTED           VARCHAR2(255 BYTE),
  CUSTOMER_TIER                  VARCHAR2(255 BYTE),
  DOMAIN                         VARCHAR2(255 BYTE),
  EXPECTED_REVENUE_CALC          VARCHAR2(255 BYTE),
  EXTERNAL_OPPORTUNITY_ID        VARCHAR2(255 BYTE),
  ONGOING_OVER_CONTRACT_CALC     VARCHAR2(255 BYTE),
  OPPORTUNITY_RECORD_TYPE        VARCHAR2(255 BYTE),
  IS_OVERDUE                     VARCHAR2(255 BYTE),
  PORTFOLIO_CODE                 VARCHAR2(255 BYTE),
  PRICE_LIST                     VARCHAR2(255 BYTE),
  PRICING_METHOD                 VARCHAR2(255 BYTE),
  PRICING_STATUS                 VARCHAR2(255 BYTE),
  PRODUCT_DOMAIN                 VARCHAR2(255 BYTE),
  PROPOSAL_TYPE                  VARCHAR2(255 BYTE),
  REVENUE_IMPACT_DATE_CALC       VARCHAR2(255 BYTE),
  REVENUE_IMPACT_DATE            VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_OF_OPPORTUNITY   VARCHAR2(255 BYTE),
  SUCCESS_INDICATOR              VARCHAR2(255 BYTE),
  TOTAL_CONTRACT_VALUE_CALC      VARCHAR2(255 BYTE),
  WON_LOST_REASON                VARCHAR2(255 BYTE),
  ACQUISITION_REVENUE_ROLLUP     VARCHAR2(255 BYTE),
  AVG_ANNUALISED_REVENUE_ROLLUP  VARCHAR2(255 BYTE),
  CURRENT_REVENUE_ROLLUP         VARCHAR2(255 BYTE),
  INCREMENTAL_REVENUE_ROLLUP     VARCHAR2(255 BYTE),
  NEW_INCOME_REVENUE_ROLLUP      VARCHAR2(255 BYTE),
  ONCE_OFF_REVENUE_ROLLUP        VARCHAR2(255 BYTE),
  PRODUCT_COUNT                  VARCHAR2(255 BYTE),
  RENEWAL_REVENUE_ROLLUP         VARCHAR2(255 BYTE),
  OVERALL_WIN_LOSS_COMMENT       VARCHAR2(255 BYTE),
  PRODUCT_TYPE                   VARCHAR2(255 BYTE),
  IS_ACTIVE_ACCOUNT              VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_PARTNER_ID       VARCHAR2(255 BYTE),
  PARTNER_ACCOUNT_NAME           VARCHAR2(255 BYTE),
  PARTNER_CODE                   VARCHAR2(255 BYTE),
  PARTNER_TYPE                   VARCHAR2(255 BYTE),
  CONTRACT                       VARCHAR2(255 BYTE),
  ALLIANCE                       VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_STAGE_OPPORTUNITY_PK ON TELS_CWP_OPPORTUNITY_STAGE
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
