DROP TABLE TELS_CWP_BILLING_SUBSCRIPTION CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_BILLING_SUBSCRIPTION
(
  FILENAME                        VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE                DATE          NOT NULL,
  RECORDNUMBER                    NUMBER(15)    NOT NULL,
  IS_FILTERED                     NUMBER(1)     NOT NULL,
  SOURCE_SYSTEM                   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY               VARCHAR2(255 BYTE),
  SOURCE_SYS_BILLING_ACCOUNT_KEY  VARCHAR2(255 BYTE),
  BILLING_ACCOUNT_NUMBER          VARCHAR2(255 BYTE),
  PLAN_NUMBER                     VARCHAR2(255 BYTE),
  PLAN_NAME                       VARCHAR2(255 BYTE),
  PLAN_DESCRIPTION                VARCHAR2(255 BYTE),
  PLAN_INSTANCE_NUMBER            VARCHAR2(255 BYTE),
  CLIENT_PLAN_INSTANCE_ID         VARCHAR2(255 BYTE),
  MASTER_PLAN_INSTANCE_NO         VARCHAR2(255 BYTE),
  CLIENT_MASTER_PLAN_INSTANCE_ID  VARCHAR2(255 BYTE),
  PARENT_SOURCE_SYSTEM_KEY        VARCHAR2(255 BYTE),
  CLIENT_PARENT_PLAN_INSTANCE_ID  VARCHAR2(255 BYTE),
  PLAN_INSTANCE_DESCRIPTION       VARCHAR2(255 BYTE),
  PLAN_DATE                       DATE,
  PLAN_UNITS                      INTEGER,
  PLAN_LAST_BILL_DATE             DATE,
  PLAN_NEXT_BILL_DATE             DATE,
  BILL_THROUGH_DATE               DATE,
  BILL_DAY                        INTEGER,
  IS_PREPAID                      VARCHAR2(255 BYTE),
  CURRENCY                        VARCHAR2(255 BYTE),
  IS_DEFAULT_RATE_SCHEDULE        VARCHAR2(255 BYTE),
  IS_SUPPLIMENTARY_PLAN           VARCHAR2(255 BYTE),
  PLAN_INSTANCE_STATUS            VARCHAR2(255 BYTE),
  PLAN_INSTANCE_STATUS_DATE       DATE,
  PLAN_ASSIGNMENT_DATE            DATE,
  PLAN_DEPROVISIONED_DATE         DATE,
  CLIENT_PLAN_ID                  VARCHAR2(255 BYTE),
  SERVICE_NUMBER                  VARCHAR2(255 BYTE),
  CLIENT_RATE_SCHEDULE_ID         VARCHAR2(255 BYTE),
  PHOENIX_SERVICE_NUMBER          VARCHAR2(255 BYTE),
  SIGMA_PRODUCTID                 VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP            DATE,
  B2B_BATCH_ID                    VARCHAR2(255 BYTE),
  B2B_KEY                         VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_BILLING_SUBSCRIPTION_PK ON TELS_CWP_BILLING_SUBSCRIPTION
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
