DROP TABLE TELS_CWP_CUSTOMER_ORDER CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_CUSTOMER_ORDER
(
  FILENAME                       VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE               DATE           NOT NULL,
  RECORDNUMBER                   NUMBER(15)     NOT NULL,
  IS_FILTERED                    NUMBER(1)      NOT NULL,
  B2B_KEY                        VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP           DATE,
  B2B_BATCH_ID                   VARCHAR2(255 BYTE),
  CUSTOMER_ORDER_SOURCE          VARCHAR2(255 BYTE),
  PHOENIX_BILLING_ACCNT_SR_KEY   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CUSTOMER_KEY     VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_OPPORTUNITY_KEY  VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY              VARCHAR2(255 BYTE),
  IS_DELETED                     INTEGER,
  CUSTOMER_ORDER_NAME            VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CREATED_DATE     DATE,
  ORDER_END_DATE                 DATE,
  ORDER_NUMBER                   VARCHAR2(255 BYTE),
  ORDER_TYPE                     VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_PARENT_KEY       VARCHAR2(255 BYTE),
  ORDER_START_DATE               DATE,
  ORDER_STATUS                   VARCHAR2(255 BYTE),
  TOTAL_ONE_OFF_CHARGES          NUMBER(25,10),
  FULFILMENT_ORDER_NUMBER        VARCHAR2(255 BYTE),
  FULFILMENT_ORDER_VERSION       NUMBER,
  IS_PM_REQUIRED                 INTEGER,
  PROJECT_COMPLEXITY             VARCHAR2(255 BYTE),
  PROJECT_ID                     VARCHAR2(255 BYTE),
  PROJECT_MGR_CONTACT_NUMBER     VARCHAR2(255 BYTE),
  PROJECT_MANAGER_EMAIL          VARCHAR2(255 BYTE),
  PROJECT_MANAGER_USER_ID        VARCHAR2(255 BYTE),
  FORECASTED_DELIVERY_DATE       DATE,
  TELSTRA_COMMITTED_DATE         DATE,
  MILESTONE_STAGE_COMPLETED      VARCHAR2(255 BYTE),
  STAGE                          VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_CUSTOMER_ORDER_PK ON TELS_CWP_CUSTOMER_ORDER
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
