DROP TABLE TELS_CWP_BILLITEM_PRESTAGE CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_BILLITEM_PRESTAGE
(
  FILENAME                        VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE                DATE          NOT NULL,
  RECORDNUMBER                    NUMBER(15)    NOT NULL,
  IS_FILTERED                     NUMBER(1)     NOT NULL,
  SOURCE_SYSTEM                   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY               VARCHAR2(255 BYTE),
  SOURCE_SYS_BILLING_SUBSCR_KEY   VARCHAR2(255 BYTE),
  SOURCE_SYS_BILLING_ACCOUNT_KEY  VARCHAR2(255 BYTE),
  SOURCE_SYS_CUSTOMER_BILL_KEY    VARCHAR2(255 BYTE),
  BILLING_ACCOUNT_NUMBER          VARCHAR2(255 BYTE),
  LINE_NUMBER                     VARCHAR2(255 BYTE),
  INVOICE_LINE_DESCRIPTION        VARCHAR2(255 BYTE),
  INVOICE_LINE_AMOUNT             VARCHAR2(255 BYTE),
  INVOICE_LINE_COMMENTS           VARCHAR2(255 BYTE),
  PLAN_NAME                       VARCHAR2(255 BYTE),
  PLAN_NUMBER                     VARCHAR2(255 BYTE),
  SERVICE_NAME                    VARCHAR2(255 BYTE),
  SERVICE_NUMBER                  VARCHAR2(255 BYTE),
  USAGE_UNITS                     VARCHAR2(255 BYTE),
  USAGE_RATE                      VARCHAR2(255 BYTE),
  START_DATE                      VARCHAR2(255 BYTE),
  END_DATE                        VARCHAR2(255 BYTE),
  TRANSACTION_TYPE                VARCHAR2(255 BYTE),
  MASTER_PLAN_INSTANCE_ID         VARCHAR2(255 BYTE),
  CLIENT_MASTER_PLAN_INSTANCE_ID  VARCHAR2(255 BYTE),
  CLIENT_RATE_SCHEDULE_ID         VARCHAR2(255 BYTE),
  RATE_SCHEDULE_NO                VARCHAR2(255 BYTE),
  RATE_SCHEDULE_TIER_NO           VARCHAR2(255 BYTE),
  PLAN_INSTANCE_NUMBER            VARCHAR2(255 BYTE),
  CLIENT_PLAN_INSTANCE_ID         VARCHAR2(255 BYTE),
  CLIENT_SERVICE_ID               VARCHAR2(255 BYTE),
  TAX_RELATED_IND                 VARCHAR2(255 BYTE),
  DEBIT                           VARCHAR2(255 BYTE),
  TAX_RATE                        VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP            VARCHAR2(255 BYTE),
  B2B_BATCH_ID                    VARCHAR2(255 BYTE),
  B2B_KEY                         VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_PRESTAGEBILL_ITEM_PK ON TELS_CWP_BILLITEM_PRESTAGE
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
