DROP TABLE TELS_CWP_PRODUCTLINE CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_PRODUCTLINE
(
  FILENAME                        VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE                DATE          NOT NULL,
  RECORDNUMBER                    NUMBER(15)    NOT NULL,
  IS_FILTERED                     NUMBER(1)     NOT NULL,
  B2B_KEY                         VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP            DATE,
  B2B_BATCH_ID                    VARCHAR2(255 BYTE),
  SOURCE_SYSTEM                   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY               VARCHAR2(255 BYTE),
  SOURCE_SYS_CUSTOMER_ORDER_KEY   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_PRODUCT_KEY       VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_PRODUCT_SPEC_KEY  VARCHAR2(255 BYTE),
  IS_DELETED                      INTEGER,
  PRODUCT_LINE_NAME               VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CREATED_DATE      DATE,
  ACTIVATION_DATE                 DATE,
  DEACTIVATION_DATE               DATE,
  DEACTIVATION_REASON             VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_PARENT_KEY        VARCHAR2(255 BYTE),
  SERVICE_STATUS                  VARCHAR2(255 BYTE),
  TOTAL_ONE_OFF_CHARGES           NUMBER(25,10),
  TOTAL_RECURRING_CHARGES         NUMBER(25,10),
  REPLACED_SERVICE_KEY            VARCHAR2(255 BYTE),
  REPLACEMENT_SERVICE_KEY         VARCHAR2(255 BYTE),
  SERVICE_NUMBER_SEQUENCE         VARCHAR2(255 BYTE),
  SERVICE_NUMBER                  VARCHAR2(255 BYTE),
  TECHNOLOGY_TYPE                 VARCHAR2(255 BYTE),
  NUMBER_OF_SEATS                 NUMBER(25,10),
  ONE_OFF_CHARGE                  NUMBER(25,10),
  RECURRING_CHARGE                NUMBER(25,10),
  PRODUCT_LINE_ZONE               VARCHAR2(255 BYTE),
  CUSTOMER_FACING_SERVICE_ID      VARCHAR2(255 BYTE),
  PRIMARY_ORDER_NUMBER            VARCHAR2(255 BYTE),
  QUANTITY                        VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_CWP_PRODUCTLINE_PK ON TELS_CWP_PRODUCTLINE
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
