DROP TABLE TELS_CWP_BILLINGACCOUNT CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_BILLINGACCOUNT
(
  FILENAME                       VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE               DATE           NOT NULL,
  RECORDNUMBER                   NUMBER(15)     NOT NULL,
  IS_FILTERED                    NUMBER(1)      NOT NULL,
  B2B_KEY                        VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP           DATE,
  B2B_BATCH_ID                   VARCHAR2(255 BYTE),
  SOURCE_SYSTEM                  VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CUSTOMER_KEY     VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_ADDRESS_KEY      VARCHAR2(255 BYTE),
  PHOENIX_SOURCE_SYSTEM_KEY      VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY              VARCHAR2(255 BYTE),
  BILLING_ACCOUNT_NUMBER         INTEGER,
  CUSTOMER_NAME                  VARCHAR2(255 BYTE),
  BILLING_ADDRESS_LINE1          VARCHAR2(255 BYTE),
  BILLING_ADDRESS_LINE2          VARCHAR2(255 BYTE),
  BILLING_ADDRESS_LINE3          VARCHAR2(255 BYTE),
  BILLING_CITY                   VARCHAR2(255 BYTE),
  BILLING_LOCALITY               VARCHAR2(255 BYTE),
  BILLING_STATE_PROVINCE         VARCHAR2(255 BYTE),
  BILLING_COUNTRY                VARCHAR2(255 BYTE),
  BILLING_POST_CODE              VARCHAR2(255 BYTE),
  SOURCE_SYS_PR_MAS_ACCOUNT_NO   VARCHAR2(255 BYTE),
  SOURCE_SYS_PR_MAS_BILL_ACC_NO  VARCHAR2(255 BYTE),
  IS_TEST_ACCOUNT                VARCHAR2(255 BYTE),
  BILLING_ACCOUNT_ST_DATE        DATE,
  ACCOUNT_CURRENCY               VARCHAR2(255 BYTE),
  ACCOUNT_BALANCE                NUMBER(25,10)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_BILLINGACCOUNT_PK ON TELS_CWP_BILLINGACCOUNT
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
