DROP TABLE TELS_CWP_PRODUCTSPEC_PRESTAGE CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_PRODUCTSPEC_PRESTAGE
(
  FILENAME                      VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE              DATE            NOT NULL,
  RECORDNUMBER                  NUMBER(15)      NOT NULL,
  IS_FILTERED                   NUMBER(1)       NOT NULL,
  SOURCE_SYSTEM                 VARCHAR2(255 BYTE),
  SOURCE_SYS_KEY                VARCHAR2(255 BYTE),
  SOURCE_SYS_PRODUCT_OFFER_KEY  VARCHAR2(255 BYTE),
  PRODUCT_SPECIFICATION_NAME    VARCHAR2(255 BYTE),
  PRODUCT_SPECIFICATION_TYPE    VARCHAR2(255 BYTE),
  PRODUCT_SPEC_DESCRIPTION      VARCHAR2(255 BYTE),
  SOURCE_EFF_START_DT           VARCHAR2(255 BYTE),
  SOURCE_EFF_END_DT             VARCHAR2(255 BYTE),
  GL_CODE                       VARCHAR2(255 BYTE),
  GL_DESCRIPTION                VARCHAR2(255 BYTE),
  GL_PERF_OBLIGATION            VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP          VARCHAR2(255 BYTE),
  B2B_KEY                       VARCHAR2(255 BYTE),
  B2B_BATCH_ID                  VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_PRESTAGE_PRODUCTSPEC_PK ON TELS_CWP_PRODUCTSPEC_PRESTAGE
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
