DROP TABLE TELS_CWP_SITE CASCADE CONSTRAINTS PURGE
/

CREATE TABLE TELS_CWP_SITE
(
  FILENAME                    VARCHAR2(255 BYTE) NOT NULL,
  BATCHPROCESSDATE            DATE              NOT NULL,
  RECORDNUMBER                NUMBER(15)        NOT NULL,
  IS_FILTERED                 NUMBER(1)         NOT NULL,
  B2B_KEY                     VARCHAR2(255 BYTE),
  B2B_INSERT_TIMESTAMP        DATE,
  B2B_BATCH_ID                VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_KEY           VARCHAR2(255 BYTE),
  SOURCE_SYSTEM_CUSTOMER_KEY  VARCHAR2(255 BYTE),
  IS_DELETED                  INTEGER,
  SITE_NAME                   VARCHAR2(255 BYTE),
  ACCOUNT_ID                  VARCHAR2(255 BYTE),
  INSTALLATION_ADDRESS        VARCHAR2(255 BYTE),
  PRIMARY_CONTACT             VARCHAR2(255 BYTE),
  SECONDARY_CONTACT           VARCHAR2(255 BYTE),
  DISPLAY_NAME                VARCHAR2(255 BYTE),
  ADBOR_ID                    VARCHAR2(255 BYTE),
  SITE_ADDRESS                VARCHAR2(255 BYTE),
  ADDRESS_STATUS              VARCHAR2(255 BYTE),
  SOURCE_SYSTEM               VARCHAR2(255 BYTE),
  SITE_ACCOUNT                VARCHAR2(255 BYTE)
)
TABLESPACE TELS_SOURCES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX TELS_SITE_PK ON TELS_CWP_SITE
(FILENAME, BATCHPROCESSDATE, RECORDNUMBER)
LOGGING
TABLESPACE TELS_SOURCES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/
