SELECT * FROM DBA_TABLES WHERE TABLE_NAME LIKE 'TELS%';
SELECT * FROM DBA_TAB_COLUMNS WHERE TABLE_NAME LIKE 'TELS%';

SELECT OWNER, TABLE_NAME, '' SCHEDULE, COLUMN_LIST, '' TABLE_FILTER 
FROM
    (SELECT OWNER, TABLE_NAME,RTRIM(XMLAGG(XMLELEMENT(E,COLUMN_NAME,',').EXTRACT('//text()') ORDER BY COLUMN_ID).GetClobVal(),',') COLUMN_LIST
    FROM all_tab_columns 
    WHERE (TABLE_NAME LIKE 'TELS_%' OR TABLE_NAME LIKE 'CS_%')
      AND DATA_TYPE NOT IN ('CLOB','BLOB')
    GROUP BY OWNER, TABLE_NAME)
ORDER BY OWNER, TABLE_NAME;

SELECT LISTAGG(TABLE_NAME,',') WITHIN GROUP (ORDER BY TABLE_NAME) table_list FROM TELS_REPOSITORYEXPORT_CONFIG WHERE EXPORT_SCHEDULE <> 'x';

SELECT * FROM TELS_REPOSITORYEXPORT_CONFIG WHERE TABLE_NAME = 'TELS_INVOICE_NUMBER';
