SELECT * FROM TELS_CORE_JOB_TEMPLATE;
SELECT * FROM TELS_CORE_JOB_QUEUE;
SELECT * FROM TELS_CORE_JOB_HISTORY;

TRUNCATE TABLE TELS_CORE_JOB_QUEUE;

--INSERT INTO TELS_CORE_JOB_TEMPLATE(JOB_NAME, JOB_TYPE, CALLSCRIPT) VALUES('Security Access Log','Outbound','./tels_outbound_securityaccesslog.sh');
INSERT INTO TELS_CORE_JOB_QUEUE(JOB_NAME, JOB_TYPE, DUE_DATETIME, CALLSCRIPT, STATUS) SELECT jt.JOB_NAME, jt.JOB_TYPE, SYSTIMESTAMP, jt.CALLSCRIPT, 'QUEUED' FROM TELS_CORE_JOB_TEMPLATE jt;
INSERT INTO TELS_CORE_JOB_QUEUE(JOB_NAME, JOB_TYPE, DUE_DATETIME, CALLSCRIPT, STATUS) SELECT jt.JOB_NAME, jt.JOB_TYPE, SYSTIMESTAMP +1, jt.CALLSCRIPT, 'QUEUED' FROM TELS_CORE_JOB_TEMPLATE jt;
INSERT INTO TELS_CORE_JOB_QUEUE(JOB_NAME, JOB_TYPE, DUE_DATETIME, CALLSCRIPT, STATUS) SELECT jt.JOB_NAME, jt.JOB_TYPE, SYSTIMESTAMP -1, jt.CALLSCRIPT, 'QUEUED' FROM TELS_CORE_JOB_TEMPLATE jt;

COMMIT;

SELECT * FROM(
SELECT JOB_ID||'|'||JOB_NAME||'|'||JOB_TYPE||'|'||DUE_DATETIME||'|'||CALLSCRIPT||'|'||STATUS
FROM TELS_CORE_JOB_QUEUE
WHERE DUE_DATETIME < SYSTIMESTAMP AND STATUS = 'QUEUED' ORDER BY DUE_DATETIME
) WHERE ROWNUM = 1;

