SELECT * FROM TEST_OIC_HOLD; --146991
SELECT count(*) FROM TELS_RCRM_STAGE_HOLD WHERE STATUS_HEADER = 'Complete'; --1319125

SELECT * FROM TELS_RCRM_STAGE_HOLD WHERE FILENAME = 'CCB-RCRM_OrderDataExtract_20190125_063539.dat';

--Records in RCRM Hold, not in OIC
SELECT ROW_ID, ROOT_ITEM_ROW_ID, STATUS_HEADER,  c.* --count(*)
FROM TELS_RCRM_STAGE_HOLD c
WHERE not EXISTS(SELECT 1 FROM TEST_OIC_HOLD o WHERE o.OLI_ROW_ID = c.ROW_ID)
  and not EXISTS(SELECT 1 FROM TEST_OIC_HOLD o WHERE o.MOLI_ROW_ID = c.ROW_ID);
  
  
SELECT * FROM TEST_OIC_HOLD WHERE MOLI_ROW_ID = '1-O47HPCQX'; 

SELECT 
  o.MOLI_ROW_ID, o.OLI_ROW_ID, o.* 
--  count(*)
FROM TEST_OIC_HOLD o
WHERE not exists(SELECT 1 FROM TELS_RCRM_STAGE_HOLD c WHERE c.ROW_ID = o.OLI_ROW_ID)
  and not exists(SELECT 1 FROM TELS_RCRM_STAGE_HOLD c WHERE c.ROW_ID = o.MOLI_ROW_ID)
  and not exists(select 1 from TELS_CORE_PRESTAGEERROR e WHERE e.RECORDKEY LIKE o.MOLI_ROW_ID||'%')
  ;
  
SELECT * FROM TEST_OIC_HOLD WHERE MOLI_ROW_ID = '1-LKWUXSA3';
SELECT * FROM TELS_RCRM_STAGE_HOLD WHERE ROW_ID = '1-LKWUXSA3';

SELECT * FROM TELS_RCRM_ROW_SOURCE WHERE ROW_ID = '1-LKWUXSA3';
SELECT * FROM TELS_PRESTAGE_RCRM WHERE ROW_ID = '1-L5HLAUSB';
SELECT * FROM TELS_STAGE_RCRM WHERE ROW_ID = '1-L5HLAUSB';
SELECT * FROM TELS_CORE_PRESTAGEERROR WHERE RECORDKEY LIKE '1-LKWUXSA3%';



SELECT * FROM TEST_OIC_HOLD WHERE OLI_ROW_ID = '1-O3XHA0XX';
SELECT * FROM TELS_RCRM_STAGE_HOLD WHERE ROW_ID = '1-O3XHA0XX';