WITH ATTRIBUTES AS(
    SELECT d.FILENAME, d.RECORDNUMBER, d.ORDER_NUMBER, d.ROW_ID ATTRIBUTE_OWNER_ROW_ID, d.ATTRIBUTE_ROW_ID, d.ATTRIBUTE_ACTION_CODE, d.ATTRIBUTE_DISPLAY_NAME, d.ATTRIBUTE_VALUE
    FROM TELS_RCRM_ATTRIBUTES_VIEW d 
    WHERE d.ATTRIBUTE_ROW_ID IS NOT NULL)
, HW_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'HW_OLI')
, HW_ASSOC_MOLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'HW_ASSOC_MOLI')
, HW_ASSOC_CONTRACT_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'HW_ASSOC_CONTRACT_OLI')
, HW_ASSOC_PLAN_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'HW_ASSOC_PLAN_OLI')
, HW_ASSOC_MRO_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'HW_ASSOC_MRO_OLI')
, LT_Rebate_Amount AS(
    SELECT lt.STARTDATE, lt.ENDDATE, lt.DIM_NAME_0, lt.IDX_NAME_0, lt.VALUE
    FROM TELS_RCRM_MV_MDLT lt
    WHERE NAME = 'LT_Rebate_Amount')
, LT_MRO_Offset_ARO AS(
    SELECT lt.STARTDATE, lt.ENDDATE, lt.DIM_NAME_0, lt.IDX_NAME_0, lt.DIM_NAME_1, lt.IDX_NAME_1, lt.DIM_NAME_2, lt.IDX_NAME_2, lt.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT lt
    WHERE NAME = 'LT_MRO_Offset_ARO')
, PASS1 AS(
SELECT 
    ho.FILENAME,
    ho.BATCHPROCESSDATE,
    ho.RECORDNUMBER,
    ham.PROVISIONED_DATE PROCESSED_DATE,
    NULL PROCESSED_PERIOD_ID,
    ho.LIST_PRICE TRANSACTION_AMOUNT,
    '1' QUANTITY,
    ham.CUSTOMER_LAST_NAME ATTRIBUTE1,
    ham.CUSTOMER_FIRST_NAME ATTRIBUTE2,
    NULL ATTRIBUTE3,NULL ATTRIBUTE4,NULL ATTRIBUTE5,NULL ATTRIBUTE6,NULL ATTRIBUTE7,NULL ATTRIBUTE8,NULL ATTRIBUTE9,NULL ATTRIBUTE10,NULL ATTRIBUTE11,NULL ATTRIBUTE12,NULL ATTRIBUTE13,NULL ATTRIBUTE14,NULL ATTRIBUTE15,NULL ATTRIBUTE16,NULL ATTRIBUTE17,NULL ATTRIBUTE18,NULL ATTRIBUTE19,NULL ATTRIBUTE20,NULL ATTRIBUTE21,NULL ATTRIBUTE22,NULL ATTRIBUTE23,NULL ATTRIBUTE24,
    ham.ORDER_NUMBER ATTRIBUTE25,
    ham.BILLING_ACCOUNT ATTRIBUTE26,
    ham.PARTNER_CODE ATTRIBUTE27,
    NULL ATTRIBUTE28,NULL ATTRIBUTE29,NULL ATTRIBUTE30,NULL ATTRIBUTE31,NULL ATTRIBUTE32,NULL ATTRIBUTE33,NULL ATTRIBUTE34,
    ham.BUSINESS_UNIT ATTRIBUTE35,
    ham.SALES_FORCE_ID ATTRIBUTE36,
    'COMMISSIONABLE TRANSACTION' ATTRIBUTE37,
    ham.SOURCE_SYSTEM ATTRIBUTE38,
    ham.PRODUCT ATTRIBUTE39,
    NULL ATTRIBUTE40,
    ham.ACTION_CODE ATTRIBUTE41,
    ham.TRANSFER_TYPE ATTRIBUTE42,
    ham.EVENT_SOURCE ATTRIBUTE43,
    ham.PROMOTION_PART_NUMBER ATTRIBUTE44,
    ham.ORDER_SUB_TYPE ATTRIBUTE45,
    ho.ROW_ID ATTRIBUTE46,
    ho.PRODUCT ATTRIBUTE47,
    NULL ATTRIBUTE48,
    ho.ACTION_CODE ATTRIBUTE49,
    ho.PROMOTION_PART_NUMBER ATTRIBUTE50,
    NULL ATTRIBUTE51,NULL ATTRIBUTE52,
    NULL ATTRIBUTE53,  /* Determined in Pass 2 */
    CASE WHEN ho.ACTION_CODE <> 'Delete' 
         THEN CASE WHEN a2.ATTRIBUTE_VALUE = 'Device Lease Contract' THEN 'Leased' ELSE a2.ATTRIBUTE_VALUE END
         END ATTRIBUTE54, /*Override determined in Pass 2*/
    NULL ATTRIBUTE55,NULL ATTRIBUTE56,NULL ATTRIBUTE57,NULL ATTRIBUTE58,
    CASE WHEN ho.ACTION_CODE <> 'Delete' 
         THEN a3.ATTRIBUTE_VALUE 
         END ATTRIBUTE59,
    ham.ORDER_TYPE ATTRIBUTE60,
    haco.ACTION_CODE ATTRIBUTE61,
    haco.CONTRACT_START_DATE ATTRIBUTE62,
    NULL ATTRIBUTE63,NULL ATTRIBUTE64,
    a4.ATTRIBUTE_VALUE ATTRIBUTE65,
    NULL ATTRIBUTE66,
    ho.HARDWARE_SUPPLIED_FLAG ATTRIBUTE67,
    NULL ATTRIBUTE68,NULL ATTRIBUTE69,NULL ATTRIBUTE70,NULL ATTRIBUTE71,NULL ATTRIBUTE72,NULL ATTRIBUTE73,NULL ATTRIBUTE74,NULL ATTRIBUTE75,NULL ATTRIBUTE76,NULL ATTRIBUTE77,NULL ATTRIBUTE78,NULL ATTRIBUTE79,NULL ATTRIBUTE80,
    ho.PART_NUMBER ATTRIBUTE81,
    CASE WHEN ho.ACTION_CODE <> 'Delete' 
         THEN CASE WHEN IS_NUMBER(REPLACE(a5.ATTRIBUTE_VALUE,'$')) = 1 THEN REPLACE(a5.ATTRIBUTE_VALUE,'$') ELSE '0' END
         ELSE CASE WHEN IS_NUMBER(REPLACE(a6.ATTRIBUTE_VALUE,'$')) = 1 THEN REPLACE(a6.ATTRIBUTE_VALUE,'$') ELSE '0' END
         END ATTRIBUTE82, /*Override determined in Pass 2*/
    NULL ATTRIBUTE83,
    CASE WHEN a5.ATTRIBUTE_ROW_ID IS NOT NULL AND ho.ACTION_CODE <> 'Delete' AND lt.VALUE IS NOT NULL 
         THEN TO_CHAR(lt.VALUE) 
         WHEN a5.ATTRIBUTE_ROW_ID IS NOT NULL AND ho.ACTION_CODE <> 'Delete' AND lt.VALUE IS NULL
         THEN 'ERROR'
         END ATTRIBUTE84, 
    NULL ATTRIBUTE85,NULL ATTRIBUTE86,NULL ATTRIBUTE87,
    ho.COMMISSION_PRODUCT_TYPE ATTRIBUTE88,
    CASE WHEN ho.PRODUCT <> 'ARO Accessory'
         THEN hapo.PART_NUMBER 
         END ATTRIBUTE89,
    CASE WHEN ho.PRODUCT <> 'ARO Accessory'
         THEN hapo.PRODUCT 
         END ATTRIBUTE90,
    NULL ATTRIBUTE91,NULL ATTRIBUTE92,NULL ATTRIBUTE93,NULL ATTRIBUTE94,NULL ATTRIBUTE95,NULL ATTRIBUTE96,NULL ATTRIBUTE97,NULL ATTRIBUTE98,NULL ATTRIBUTE99,NULL ATTRIBUTE100,
    NULL LAST_UPDATE_DATE,NULL CREATION_DATE,
    ham.CREATED_DATE BOOKED_DATE,
    'REVENUE' REVENUE_TYPE,
    NULL TYPE,NULL EMPLOYEE_NUMBER,NULL RECORD_STATUS,NULL ERROR_TYPE,
    (CASE WHEN IS_NUMBER(REPLACE(a5.ATTRIBUTE_VALUE,'$')) = 0
         THEN 'MRO Amount is invalid: ' || a5.ATTRIBUTE_VALUE || ' '
    END ||
    CASE WHEN IS_NUMBER(REPLACE(a6.ATTRIBUTE_VALUE,'$')) = 0
         THEN 'MRO Amount is invalid: ' || a6.ATTRIBUTE_VALUE
         END) ERROR_MSG,
    ho.SOURCE_SYSTEM SOURCE,
    ham.SUBMITTED_DATE SUBMITTED_DATE,
    ham.STATUS_HEADER STATUS_HEADER,
    ham.STATUS_ORDER_LINE_ITEM STATUS_ORDER_LINE_ITEM,
    ham.ORIGINAL_ORDER_NUMBER,
    ho.EFFECTIVE_DATE EFFECTIVE_DATE,
    haco.PRODUCT HACO_PRODUCT,
    a1.ATTRIBUTE_VALUE DEVICE_MAX_RETAIL_PRICE
FROM 
  HW_OLI ho
  LEFT OUTER JOIN HW_ASSOC_MOLI          ham ON  ham.ORDER_NUMBER = ho.ORDER_NUMBER AND  ham.STATUS_HEADER = ho.STATUS_HEADER AND  ham.ROW_ID = ho.ROOT_ITEM_ROW_ID
  LEFT OUTER JOIN HW_ASSOC_CONTRACT_OLI haco ON haco.ORDER_NUMBER = ho.ORDER_NUMBER AND haco.STATUS_HEADER = ho.STATUS_HEADER AND haco.ROOT_ITEM_ROW_ID = ho.ROOT_ITEM_ROW_ID
                                                AND EXISTS (SELECT 1 FROM TELS_RCRM_MV_ATTRIBUTE ATT WHERE ATT.ROW_ID = haco.ROW_ID AND ATT.ATTRIBUTE_VALUE = ho.PART_NUMBER)
  LEFT OUTER JOIN HW_ASSOC_PLAN_OLI     hapo ON hapo.ORDER_NUMBER = ho.ORDER_NUMBER AND hapo.STATUS_HEADER = ho.STATUS_HEADER AND hapo.ROOT_ITEM_ROW_ID = ho.ROOT_ITEM_ROW_ID
  LEFT OUTER JOIN HW_ASSOC_MRO_OLI      hamo ON hamo.ORDER_NUMBER = ho.ORDER_NUMBER AND hamo.STATUS_HEADER = ho.STATUS_HEADER AND hamo.ROW_ID = ho.ROOT_ITEM_ROW_ID
  LEFT OUTER JOIN LT_Rebate_Amount        lt ON lt.IDX_NAME_0 = NVL(ho.PART_NUMBER,'NULL') AND lt.STARTDATE <= TO_DATE(NVL(ho.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(ho.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
  LEFT OUTER JOIN ATTRIBUTES              a1 ON a1.ATTRIBUTE_OWNER_ROW_ID = haco.ROW_ID AND a1.ORDER_NUMBER = haco.ORDER_NUMBER AND a1.ATTRIBUTE_DISPLAY_NAME = 'Device Max. Retail Price'
  LEFT OUTER JOIN ATTRIBUTES              a2 ON a2.ATTRIBUTE_OWNER_ROW_ID = ho.ROW_ID AND a2.ORDER_NUMBER = ho.ORDER_NUMBER AND a2.ATTRIBUTE_DISPLAY_NAME = 'Mobile Device Payment Method' AND a2.ATTRIBUTE_ACTION_CODE <> 'Delete'
  LEFT OUTER JOIN ATTRIBUTES              a3 ON a3.ATTRIBUTE_OWNER_ROW_ID = ho.ROW_ID AND a3.ORDER_NUMBER = ho.ORDER_NUMBER AND a3.ATTRIBUTE_DISPLAY_NAME = 'IMEI' AND a3.ATTRIBUTE_ACTION_CODE <> 'Delete'
  LEFT OUTER JOIN ATTRIBUTES              a4 ON a4.ATTRIBUTE_OWNER_ROW_ID = haco.ROW_ID AND a4.ORDER_NUMBER = haco.ORDER_NUMBER AND a4.ATTRIBUTE_DISPLAY_NAME = 'Contract Term'
  LEFT OUTER JOIN ATTRIBUTES              a5 ON a5.ATTRIBUTE_OWNER_ROW_ID = haco.ROW_ID AND a5.ORDER_NUMBER = haco.ORDER_NUMBER AND a5.ATTRIBUTE_DISPLAY_NAME IN('MRO Amount','Device Commitment','Device Purchase Price')
  LEFT OUTER JOIN ATTRIBUTES              a6 ON a6.ATTRIBUTE_OWNER_ROW_ID = hamo.ROW_ID AND a6.ORDER_NUMBER = hamo.ORDER_NUMBER AND a6.ATTRIBUTE_DISPLAY_NAME = 'MRO Amount'
WHERE NVL(ho.ORDER_SUB_TYPE,'NULL') <> 'Transfer'
-- AND ho.ORDER_NUMBER = '1-1776655935664' 
-- AND ho.ROW_ID = '1-OQ54O6P9'
)
SELECT 
    p1.FILENAME,p1.BATCHPROCESSDATE,p1.RECORDNUMBER,p1.PROCESSED_DATE,p1.PROCESSED_PERIOD_ID,p1.TRANSACTION_AMOUNT,p1.QUANTITY,p1.ATTRIBUTE1,p1.ATTRIBUTE2,p1.ATTRIBUTE3,p1.ATTRIBUTE4,p1.ATTRIBUTE5,p1.ATTRIBUTE6,p1.ATTRIBUTE7,p1.ATTRIBUTE8,p1.ATTRIBUTE9,p1.ATTRIBUTE10,
    p1.ATTRIBUTE11,p1.ATTRIBUTE12,p1.ATTRIBUTE13,p1.ATTRIBUTE14,p1.ATTRIBUTE15,p1.ATTRIBUTE16,p1.ATTRIBUTE17,p1.ATTRIBUTE18,p1.ATTRIBUTE19,p1.ATTRIBUTE20,p1.ATTRIBUTE21,p1.ATTRIBUTE22,p1.ATTRIBUTE23,p1.ATTRIBUTE24,p1.ATTRIBUTE25,p1.ATTRIBUTE26,p1.ATTRIBUTE27,p1.ATTRIBUTE28,
    p1.ATTRIBUTE29,p1.ATTRIBUTE30,p1.ATTRIBUTE31,p1.ATTRIBUTE32,p1.ATTRIBUTE33,p1.ATTRIBUTE34,p1.ATTRIBUTE35,p1.ATTRIBUTE36,p1.ATTRIBUTE37,p1.ATTRIBUTE38,p1.ATTRIBUTE39,p1.ATTRIBUTE40,p1.ATTRIBUTE41,p1.ATTRIBUTE42,p1.ATTRIBUTE43,p1.ATTRIBUTE44,p1.ATTRIBUTE45,p1.ATTRIBUTE46,
    p1.ATTRIBUTE47,p1.ATTRIBUTE48,p1.ATTRIBUTE49,p1.ATTRIBUTE50,p1.ATTRIBUTE51,p1.ATTRIBUTE52,
    CASE WHEN p1.HACO_PRODUCT = 'Device Payment Contract'
         THEN 'Device Max. Retail Price=' || p1.DEVICE_MAX_RETAIL_PRICE
         ELSE 'Original Tier=' || Trunc(p1.ATTRIBUTE82)
              || ' MRP=' || (SELECT TO_CHAR(lt.STRINGVALUE) FROM LT_MRO_Offset_ARO lt WHERE lt.IDX_NAME_2 = 'Reimbursement Amount' AND lt.IDX_NAME_0 = NVL(p1.ATTRIBUTE81,'NULL') AND lt.IDX_NAME_1 = Trunc(p1.ATTRIBUTE82) AND lt.STARTDATE <= TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')) || ' ' 
              || CASE WHEN NVL(p1.ATTRIBUTE89,'A') <> NVL((SELECT TO_CHAR(lt.STRINGVALUE) FROM LT_MRO_Offset_ARO lt WHERE lt.IDX_NAME_2 = 'Plan Product Code' AND lt.IDX_NAME_0 = NVL(p1.ATTRIBUTE81,'NULL') AND lt.IDX_NAME_1 = NVL(p1.ATTRIBUTE82,'NULL') AND lt.STARTDATE <= TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')),'B')
                      THEN 'ARO Accessory'
                      ELSE p1.ATTRIBUTE81 
                      END || ' ' 
              || (SELECT TO_CHAR(lt.STRINGVALUE) FROM LT_MRO_Offset_ARO lt WHERE lt.IDX_NAME_2 = 'Plan Name' AND lt.IDX_NAME_0 = NVL(p1.ATTRIBUTE81,'NULL') AND lt.IDX_NAME_1 = Trunc(p1.ATTRIBUTE82) AND lt.STARTDATE <= TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss'))
         END ATTRIBUTE53, 
    CASE WHEN EXISTS(SELECT 1 FROM LT_MRO_Offset_ARO lt WHERE lt.IDX_NAME_0 = NVL(p1.ATTRIBUTE81,'NULL') AND lt.IDX_NAME_1 = to_char(to_number(REPLACE(p1.ATTRIBUTE82,'$'))) AND lt.STARTDATE <= TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss'))
         THEN 'MROZ'
         ELSE p1.ATTRIBUTE54
         END ATTRIBUTE54,
    p1.ATTRIBUTE55,p1.ATTRIBUTE56,p1.ATTRIBUTE57,p1.ATTRIBUTE58,p1.ATTRIBUTE59,p1.ATTRIBUTE60,p1.ATTRIBUTE61,p1.ATTRIBUTE62,p1.ATTRIBUTE63,p1.ATTRIBUTE64,p1.ATTRIBUTE65,p1.ATTRIBUTE66,p1.ATTRIBUTE67,p1.ATTRIBUTE68,p1.ATTRIBUTE69,p1.ATTRIBUTE70,p1.ATTRIBUTE71,p1.ATTRIBUTE72,
    p1.ATTRIBUTE73,p1.ATTRIBUTE74,p1.ATTRIBUTE75,p1.ATTRIBUTE76,p1.ATTRIBUTE77,p1.ATTRIBUTE78,p1.ATTRIBUTE79,p1.ATTRIBUTE80,p1.ATTRIBUTE81,
    CASE WHEN lt1.STRINGVALUE IS NOT NULL 
         THEN TO_CHAR(lt1.STRINGVALUE)
         ELSE TO_CHAR(p1.ATTRIBUTE82)
         END ATTRIBUTE82,
    p1.ATTRIBUTE83,
    CASE WHEN p1.ATTRIBUTE54 = 'Subsidised' 
         THEN p1.ATTRIBUTE84
         ELSE NULL
         END ATTRIBUTE84,
    p1.ATTRIBUTE85,p1.ATTRIBUTE86,p1.ATTRIBUTE87,p1.ATTRIBUTE88,p1.ATTRIBUTE89,p1.ATTRIBUTE90,
    p1.ATTRIBUTE91,p1.ATTRIBUTE92,p1.ATTRIBUTE93,p1.ATTRIBUTE94,p1.ATTRIBUTE95,p1.ATTRIBUTE96,p1.ATTRIBUTE97,p1.ATTRIBUTE98,p1.ATTRIBUTE99,p1.ATTRIBUTE100,
    p1.LAST_UPDATE_DATE,p1.CREATION_DATE,p1.BOOKED_DATE,p1.REVENUE_TYPE,p1.TYPE,p1.EMPLOYEE_NUMBER,p1.RECORD_STATUS,p1.ERROR_TYPE,p1.ERROR_MSG,p1.SOURCE,p1.FILENAME,p1.RECORDNUMBER,p1.SUBMITTED_DATE,p1.STATUS_HEADER,p1.STATUS_ORDER_LINE_ITEM,p1.ORIGINAL_ORDER_NUMBER
FROM 
  PASS1 p1
  LEFT OUTER JOIN LT_MRO_Offset_ARO lt1 ON lt1.IDX_NAME_0 = p1.ATTRIBUTE81 AND lt1.IDX_NAME_1 = to_number(REPLACE(p1.ATTRIBUTE82,'$')) AND IDX_NAME_2 = 'Reimbursement Amount' AND lt1.STARTDATE <= TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt1.ENDDATE > TO_DATE(NVL(p1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')