WITH ATTRIBUTES AS(
    SELECT D.FILENAME, D.RECORDNUMBER, D.ORDER_NUMBER, D.ROW_ID AS "ATTRIBUTE_OWNER_ROW_ID", D.ATTRIBUTE_ROW_ID, D.ATTRIBUTE_ACTION_CODE, D.ATTRIBUTE_DISPLAY_NAME, D.ATTRIBUTE_VALUE
    FROM TELS_RCRM_ATTRIBUTES_VIEW D
    WHERE D.ATTRIBUTE_ROW_ID IS NOT NULL)
, FHW_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'FHW_OLI')
, FHW_ASSOC_MOLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'FHW_ASSOC_MOLI')
, FHW_ASSOC_VAS_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'FHW_ASSOC_VAS_OLI')
, LT_PROFESSIONAL_INSTALL AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Professional_Install')
, LT_PLAN_VAS_HW_RO AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Plan_VAS_HW_RO')
, PASS1 AS(
SELECT
    FO.FILENAME,
    FO.BATCHPROCESSDATE,
    FO.RECORDNUMBER,
    FAM.PROVISIONED_DATE PROCESSED_DATE,
    NULL PROCESSED_PERIOD_ID,
    FO.LIST_PRICE TRANSACTION_AMOUNT,
    '1' QUANTITY,
    FAM.CUSTOMER_LAST_NAME ATTRIBUTE1,
    FAM.CUSTOMER_FIRST_NAME ATTRIBUTE2,
    NULL ATTRIBUTE3,NULL ATTRIBUTE4,NULL ATTRIBUTE5,NULL ATTRIBUTE6,NULL ATTRIBUTE7,NULL ATTRIBUTE8,NULL ATTRIBUTE9,NULL ATTRIBUTE10,NULL ATTRIBUTE11,NULL ATTRIBUTE12,NULL ATTRIBUTE13,NULL ATTRIBUTE14,NULL ATTRIBUTE15,NULL ATTRIBUTE16,NULL ATTRIBUTE17,NULL ATTRIBUTE18,NULL ATTRIBUTE19,NULL ATTRIBUTE20,NULL ATTRIBUTE21,NULL ATTRIBUTE22,NULL ATTRIBUTE23,NULL ATTRIBUTE24,
    FAM.ORDER_NUMBER ATTRIBUTE25,
    FAM.BILLING_ACCOUNT ATTRIBUTE26,
    FAM.PARTNER_CODE ATTRIBUTE27,
    NULL ATTRIBUTE28,NULL ATTRIBUTE29,NULL ATTRIBUTE30,NULL ATTRIBUTE31,NULL ATTRIBUTE32,NULL ATTRIBUTE33,NULL ATTRIBUTE34,
    FAM.BUSINESS_UNIT ATTRIBUTE35,
    FAM.SALES_FORCE_ID ATTRIBUTE36,
    'COMMISSIONABLE TRANSACTION' ATTRIBUTE37,
    FAM.SOURCE_SYSTEM ATTRIBUTE38,
    FAM.PRODUCT ATTRIBUTE39,
    NULL ATTRIBUTE40,
    FAM.ACTION_CODE ATTRIBUTE41,
    FAM.TRANSFER_TYPE ATTRIBUTE42,
    FAM.EVENT_SOURCE ATTRIBUTE43,
    FAM.PROMOTION_PART_NUMBER ATTRIBUTE44,
    CASE WHEN FAM.ORDER_TYPE = 'Modify' AND FAM.SUB_ACTION_CODE IN('Transition-Add','Transition-Delete')
         THEN 'Transition'
         ELSE FAM.ORDER_SUB_TYPE
         END ATTRIBUTE45,
    FO.ROW_ID ATTRIBUTE46,
    FO.PRODUCT ATTRIBUTE47,
    NULL ATTRIBUTE48,
    FO.ACTION_CODE ATTRIBUTE49,
    FO.PROMOTION_PART_NUMBER ATTRIBUTE50,
    NULL ATTRIBUTE51,NULL ATTRIBUTE52,
    CASE WHEN LT2.STRINGVALUE IS NOT NULL AND EXISTS(SELECT 1 FROM FHW_ASSOC_VAS_OLI FAVO 
                                                    JOIN LT_PROFESSIONAL_INSTALL LT1 ON LT1.IDX_NAME_0 = NVL(FAVO.PART_NUMBER,'NULL') AND LT1.IDX_NAME_1 = 'PI' AND LT1.STRINGVALUE = 'Yes' 
                                                    WHERE FAVO.ORDER_NUMBER = FO.ORDER_NUMBER AND FAVO.STATUS_HEADER = FO.STATUS_HEADER AND FAVO.ROOT_ITEM_ROW_ID = FO.ROOT_ITEM_ROW_ID)
         THEN 'Professional Installation'
         ELSE NULL
         END ATTRIBUTE53,
    NULL ATTRIBUTE54,NULL ATTRIBUTE55,NULL ATTRIBUTE56,NULL ATTRIBUTE57,NULL ATTRIBUTE58,NULL ATTRIBUTE59,
    CASE WHEN FAM.ORDER_TYPE = 'Modify' AND FAM.SUB_ACTION_CODE IN('Move-Add','Move-Delete')
         THEN 'Move'
         WHEN FAM.ORDER_TYPE = 'Modify' AND FAM.SUB_ACTION_CODE IN('Transition-Add','Transition-Delete')
         THEN 'Add New Service'
         ELSE FAM.ORDER_TYPE 
         END ATTRIBUTE60,
    NULL ATTRIBUTE61,NULL ATTRIBUTE62,NULL ATTRIBUTE63,NULL ATTRIBUTE64,NULL ATTRIBUTE65,NULL ATTRIBUTE66,
    CASE WHEN LT2.STRINGVALUE IS NOT NULL AND EXISTS(SELECT 1 FROM FHW_ASSOC_VAS_OLI FAVO 
                                                    JOIN LT_PROFESSIONAL_INSTALL LT1 ON LT1.IDX_NAME_0 = NVL(FAVO.PART_NUMBER,'NULL') AND LT1.IDX_NAME_1 = 'PI' AND LT1.STRINGVALUE = 'Yes' 
                                                    WHERE FAVO.ORDER_NUMBER = FO.ORDER_NUMBER AND FAVO.STATUS_HEADER = FO.STATUS_HEADER AND FAVO.ROOT_ITEM_ROW_ID = FO.ROOT_ITEM_ROW_ID )
         THEN 'N'
         WHEN A2.ATTRIBUTE_VALUE IS NOT NULL
         THEN A2.ATTRIBUTE_VALUE
         WHEN A3.ATTRIBUTE_VALUE IS NOT NULL
         THEN A3.ATTRIBUTE_VALUE
         ELSE FO.HARDWARE_SUPPLIED_FLAG
         END ATTRIBUTE67, 
    NULL ATTRIBUTE68,NULL ATTRIBUTE69,NULL ATTRIBUTE70,NULL ATTRIBUTE71,NULL ATTRIBUTE72,NULL ATTRIBUTE73,NULL ATTRIBUTE74,NULL ATTRIBUTE75,NULL ATTRIBUTE76,NULL ATTRIBUTE77,
    CASE WHEN FO.HARDWARE_ASSOCIATION_ID IS NOT NULL 
         THEN 'With HRO'
         WHEN FO.HARDWARE_ASSOCIATION_ID IS NULL 
         THEN 'Without HRO'
         END ATTRIBUTE78,
    NULL ATTRIBUTE79,NULL ATTRIBUTE80,
    FO.PART_NUMBER ATTRIBUTE81,
    NULL ATTRIBUTE82,NULL ATTRIBUTE83,NULL ATTRIBUTE84,NULL ATTRIBUTE85,NULL ATTRIBUTE86,NULL ATTRIBUTE87,
    FO.COMMISSION_PRODUCT_TYPE ATTRIBUTE88,
    NULL ATTRIBUTE89,NULL ATTRIBUTE90,NULL ATTRIBUTE91,NULL ATTRIBUTE92,NULL ATTRIBUTE93,NULL ATTRIBUTE94,NULL ATTRIBUTE95,NULL ATTRIBUTE96,NULL ATTRIBUTE97,NULL ATTRIBUTE98,NULL ATTRIBUTE99,NULL ATTRIBUTE100,
    NULL LAST_UPDATE_DATE,NULL CREATION_DATE,
    FAM.CREATED_DATE BOOKED_DATE,
    'REVENUE' REVENUE_TYPE,
    NULL TYPE,NULL EMPLOYEE_NUMBER,NULL RECORD_STATUS,NULL ERROR_TYPE,NULL ERROR_MSG,
    FO.SOURCE_SYSTEM SOURCE,
    FAM.SUBMITTED_DATE SUBMITTED_DATE,
    FAM.STATUS_HEADER STATUS_HEADER,
    FAM.STATUS_ORDER_LINE_ITEM STATUS_ORDER_LINE_ITEM,
    FAM.ORIGINAL_ORDER_NUMBER,
    CASE WHEN EXISTS(SELECT 1 FROM LT_PLAN_VAS_HW_RO LT WHERE LT.IDX_NAME_0 = NVL(FO.PART_NUMBER,'NULL') AND LT.STARTDATE <= TO_DATE(NVL(FO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT.ENDDATE > TO_DATE(NVL(FO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss'))
         THEN 1 
         ELSE 0
         END LT_PLAN_VAS_HW_RO_EXISTS,
    A1.ATTRIBUTE_ROW_ID FO_HW_ORDER_TYPE
FROM 
  FHW_OLI FO
  LEFT OUTER JOIN FHW_ASSOC_MOLI FAM ON FAM.ORDER_NUMBER = FO.ORDER_NUMBER AND FAM.STATUS_HEADER = FO.STATUS_HEADER AND FAM.ROW_ID = FO.ROOT_ITEM_ROW_ID
  LEFT OUTER JOIN LT_PROFESSIONAL_INSTALL LT2 ON LT2.IDX_NAME_0 = NVL(FO.PART_NUMBER,'NULL') AND LT2.IDX_NAME_1 = 'PIK' AND LT2.STRINGVALUE = 'Yes' AND LT2.STARTDATE <= TO_DATE(NVL(FO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT2.ENDDATE > TO_DATE(NVL(FO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
  LEFT OUTER JOIN ATTRIBUTES A1 ON A1.ATTRIBUTE_OWNER_ROW_ID = FO.ROW_ID AND A1.ORDER_NUMBER = FO.ORDER_NUMBER AND A1.ATTRIBUTE_DISPLAY_NAME = 'Hardware Order Type' AND A1.ATTRIBUTE_VALUE = 'Repayment Option for Device or Service'
--  LEFT OUTER JOIN ATTRIBUTES_VW A2 ON A2.ATTRIBUTE_OWNER_ROW_ID = FO.ROW_ID AND A2.ORDER_NUMBER = FO.ORDER_NUMBER AND A2.ATTRIBUTE_DISPLAY_NAME = 'Supplied in Store?'
  LEFT JOIN (
    SELECT ORDER_NUMBER, ATTRIBUTE_OWNER_ROW_ID, ATTRIBUTE_VALUE, ROW_NUMBER() OVER (PARTITION BY FILENAME, ORDER_NUMBER, ATTRIBUTE_OWNER_ROW_ID, ATTRIBUTE_ACTION_CODE, ATTRIBUTE_DISPLAY_NAME ORDER BY ATTRIBUTE_ROW_ID DESC) AS "ATTRIBUTE_SEQ"
    FROM ATTRIBUTES
    WHERE ATTRIBUTE_DISPLAY_NAME = 'Supplied in Store?') A2
     ON A2.ORDER_NUMBER = FO.ORDER_NUMBER
    AND A2.ATTRIBUTE_OWNER_ROW_ID = FO.ROW_ID
    AND A2.ATTRIBUTE_SEQ = 1
  LEFT OUTER JOIN ATTRIBUTES A3 ON A3.ATTRIBUTE_OWNER_ROW_ID = FO.ROW_ID AND A3.ORDER_NUMBER = FO.ORDER_NUMBER AND A3.ATTRIBUTE_DISPLAY_NAME = 'Hardware Supplied'
WHERE NVL(FO.ORDER_SUB_TYPE,'NULL') <> 'Transfer' 
)
SELECT
    P1.FILENAME,P1.BATCHPROCESSDATE,P1.RECORDNUMBER,P1.PROCESSED_DATE,P1.PROCESSED_PERIOD_ID,P1.TRANSACTION_AMOUNT,P1.QUANTITY,P1.ATTRIBUTE1,P1.ATTRIBUTE2,P1.ATTRIBUTE3,P1.ATTRIBUTE4,P1.ATTRIBUTE5,P1.ATTRIBUTE6,P1.ATTRIBUTE7,P1.ATTRIBUTE8,P1.ATTRIBUTE9,P1.ATTRIBUTE10,
    P1.ATTRIBUTE11,P1.ATTRIBUTE12,P1.ATTRIBUTE13,P1.ATTRIBUTE14,P1.ATTRIBUTE15,P1.ATTRIBUTE16,P1.ATTRIBUTE17,P1.ATTRIBUTE18,P1.ATTRIBUTE19,P1.ATTRIBUTE20,P1.ATTRIBUTE21,P1.ATTRIBUTE22,P1.ATTRIBUTE23,P1.ATTRIBUTE24,P1.ATTRIBUTE25,P1.ATTRIBUTE26,P1.ATTRIBUTE27,P1.ATTRIBUTE28,
    P1.ATTRIBUTE29,P1.ATTRIBUTE30,P1.ATTRIBUTE31,P1.ATTRIBUTE32,P1.ATTRIBUTE33,P1.ATTRIBUTE34,P1.ATTRIBUTE35,P1.ATTRIBUTE36,P1.ATTRIBUTE37,P1.ATTRIBUTE38,P1.ATTRIBUTE39,P1.ATTRIBUTE40,P1.ATTRIBUTE41,P1.ATTRIBUTE42,P1.ATTRIBUTE43,P1.ATTRIBUTE44,P1.ATTRIBUTE45,P1.ATTRIBUTE46,
    P1.ATTRIBUTE47,P1.ATTRIBUTE48,P1.ATTRIBUTE49,P1.ATTRIBUTE50,P1.ATTRIBUTE51,P1.ATTRIBUTE52,P1.ATTRIBUTE53,P1.ATTRIBUTE54,P1.ATTRIBUTE55,P1.ATTRIBUTE56,P1.ATTRIBUTE57,P1.ATTRIBUTE58,P1.ATTRIBUTE59,P1.ATTRIBUTE60,P1.ATTRIBUTE61,P1.ATTRIBUTE62,P1.ATTRIBUTE63,P1.ATTRIBUTE64,
    P1.ATTRIBUTE65,P1.ATTRIBUTE66,P1.ATTRIBUTE67,P1.ATTRIBUTE68,P1.ATTRIBUTE69,P1.ATTRIBUTE70,P1.ATTRIBUTE71,P1.ATTRIBUTE72,P1.ATTRIBUTE73,P1.ATTRIBUTE74,P1.ATTRIBUTE75,P1.ATTRIBUTE76,P1.ATTRIBUTE77,
    CASE WHEN P1.LT_PLAN_VAS_HW_RO_EXISTS = 1
         THEN CASE WHEN P1.FO_HW_ORDER_TYPE IS NOT NULL
                   THEN 'With RO'
                   WHEN P1.FO_HW_ORDER_TYPE IS NULL
                   THEN 'Without RO'
                   END
         ELSE P1.ATTRIBUTE78
         END ATTRIBUTE78,
    P1.ATTRIBUTE79,P1.ATTRIBUTE80,P1.ATTRIBUTE81,P1.ATTRIBUTE82,P1.ATTRIBUTE83,P1.ATTRIBUTE84,P1.ATTRIBUTE85,P1.ATTRIBUTE86,P1.ATTRIBUTE87,P1.ATTRIBUTE88,P1.ATTRIBUTE89,P1.ATTRIBUTE90,
    P1.ATTRIBUTE91,P1.ATTRIBUTE92,P1.ATTRIBUTE93,P1.ATTRIBUTE94,P1.ATTRIBUTE95,P1.ATTRIBUTE96,P1.ATTRIBUTE97,P1.ATTRIBUTE98,P1.ATTRIBUTE99,P1.ATTRIBUTE100,
    P1.LAST_UPDATE_DATE,P1.CREATION_DATE,P1.BOOKED_DATE,P1.REVENUE_TYPE,P1.TYPE,P1.EMPLOYEE_NUMBER,P1.RECORD_STATUS,P1.ERROR_TYPE,P1.ERROR_MSG,P1.SOURCE,P1.FILENAME,P1.RECORDNUMBER,P1.SUBMITTED_DATE,P1.STATUS_HEADER,P1.STATUS_ORDER_LINE_ITEM,P1.ORIGINAL_ORDER_NUMBER
FROM PASS1 P1