WITH ATTRIBUTES AS(
    SELECT D.FILENAME, D.RECORDNUMBER, D.ORDER_NUMBER, D.ROW_ID ATTRIBUTE_OWNER_ROW_ID, D.ATTRIBUTE_ROW_ID, D.ATTRIBUTE_ACTION_CODE, D.ATTRIBUTE_DISPLAY_NAME, D.ATTRIBUTE_VALUE
    FROM TELS_RCRM_ATTRIBUTES_VIEW D
    WHERE D.ATTRIBUTE_ROW_ID IS NOT NULL)
, MP_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'MP_OLI')
, MP_ASSOC_MOLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_MOLI')
, MP_ASSOC_FHW_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_FHW_OLI')
, MP_ASSOC_MAIN_CONT_ADD_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_MAIN_CONT_ADD_OLI')
, MP_ASSOC_MAIN_CONT_DEL_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_MAIN_CONT_DEL_OLI')
, MP_ASSOC_SERVICE_MOLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_SERVICE_MOLI')
, SERVICE_ASSOC_ACCESS_TYPE_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'SERVICE_ASSOC_ACCESS_TYPE_OLI')
, LT_ALLOWABLE_RECON_PERIOD AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.VALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Allowable_Recon_Period')
, LT_PLAN_VAS_HW_RO AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Plan_VAS_HW_RO')
, LT_SALES_TYPE_MAIN_PLAN AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.DIM_NAME_2, LT.IDX_NAME_2, LT.DIM_NAME_3, LT.IDX_NAME_3, LT.DIM_NAME_4, LT.IDX_NAME_4, LT.DIM_NAME_5, LT.IDX_NAME_5, LT.DIM_NAME_6, LT.IDX_NAME_6, LT.DIM_NAME_7, LT.IDX_NAME_7, LT.DIM_NAME_8, LT.IDX_NAME_8, LT.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Sales_Type_Main_Plan')
, PRODUCT AS(
    SELECT CLS.NAME, PRD.GENERICATTRIBUTE1 
    FROM CS_CATEGORYTREE@TC_LINK CTR 
      JOIN CS_CATEGORY_CLASSIFIERS@TC_LINK CCL ON
        CCL.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND CCL.CATEGORYTREESEQ = CTR.CATEGORYTREESEQ
        AND CCL.TENANTID = CTR.TENANTID
      JOIN CS_CLASSIFIER@TC_LINK CLS ON
        CLS.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND CLS.CLASSIFIERSEQ = CCL.CLASSIFIERSEQ
        AND CLS.TENANTID = CCL.TENANTID
      JOIN CS_PRODUCT@TC_LINK PRD ON
        PRD.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND PRD.CLASSIFIERSEQ = CLS.CLASSIFIERSEQ
        AND PRD.TENANTID = CLS.TENANTID
    WHERE
        CTR.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND CTR.TENANTID = 'TELS'
        AND CTR.NAME = 'Product_Category'
    GROUP BY CLS.NAME, PRD.GENERICATTRIBUTE1) -- !!! Needs to be fixed for effective dating
, PASS1 AS(
SELECT 
    MO.FILENAME,
    MO.BATCHPROCESSDATE,
    MO.RECORDNUMBER,
    MPAM.PROVISIONED_DATE PROCESSED_DATE,
    NULL PROCESSED_PERIOD_ID,
    MO.LIST_PRICE TRANSACTION_AMOUNT,
    '1' QUANTITY,
    MPAM.CUSTOMER_LAST_NAME ATTRIBUTE1,
    MPAM.CUSTOMER_FIRST_NAME ATTRIBUTE2,
    NULL ATTRIBUTE3,NULL ATTRIBUTE4,NULL ATTRIBUTE5,NULL ATTRIBUTE6,NULL ATTRIBUTE7,NULL ATTRIBUTE8,NULL ATTRIBUTE9,NULL ATTRIBUTE10,NULL ATTRIBUTE11,NULL ATTRIBUTE12,NULL ATTRIBUTE13,NULL ATTRIBUTE14,NULL ATTRIBUTE15,NULL ATTRIBUTE16,NULL ATTRIBUTE17,NULL ATTRIBUTE18,NULL ATTRIBUTE19,NULL ATTRIBUTE20,NULL ATTRIBUTE21,NULL ATTRIBUTE22,NULL ATTRIBUTE23,NULL ATTRIBUTE24,
    MPAM.ORDER_NUMBER ATTRIBUTE25,
    MPAM.BILLING_ACCOUNT ATTRIBUTE26,
    MPAM.PARTNER_CODE ATTRIBUTE27,
    NULL ATTRIBUTE28,NULL ATTRIBUTE29,NULL ATTRIBUTE30,NULL ATTRIBUTE31,NULL ATTRIBUTE32,NULL ATTRIBUTE33,NULL ATTRIBUTE34,
    MPAM.BUSINESS_UNIT ATTRIBUTE35,
    MPAM.SALES_FORCE_ID ATTRIBUTE36,
    'COMMISSIONABLE TRANSACTION' ATTRIBUTE37,
    MPAM.SOURCE_SYSTEM ATTRIBUTE38,
    MPAM.PRODUCT ATTRIBUTE39,
    NULL ATTRIBUTE40,
    MASM.ACTION_CODE ATTRIBUTE41,
    MPAM.TRANSFER_TYPE ATTRIBUTE42,
    MASM.EVENT_SOURCE ATTRIBUTE43,
    MPAM.PROMOTION_PART_NUMBER ATTRIBUTE44,
    CASE WHEN MPAM.ORDER_TYPE = 'Modify' AND MPAM.SUB_ACTION_CODE IN('Transition-Add','Transition-Delete') 
         THEN 'Transition' 
         ELSE MPAM.ORDER_SUB_TYPE 
         END ATTRIBUTE45,
    MO.ROW_ID ATTRIBUTE46,
    MO.PRODUCT ATTRIBUTE47,
    NULL ATTRIBUTE48,
    MASM.ACTION_CODE ATTRIBUTE49,
    MO.PROMOTION_PART_NUMBER ATTRIBUTE50,
    NULL ATTRIBUTE51,NULL ATTRIBUTE52,NULL ATTRIBUTE53,NULL ATTRIBUTE54,NULL ATTRIBUTE55,NULL ATTRIBUTE56,NULL ATTRIBUTE57,NULL ATTRIBUTE58,NULL ATTRIBUTE59,
    CASE WHEN MPAM.ORDER_TYPE = 'Modify' AND MPAM.SUB_ACTION_CODE IN('Move-Add','Move-Delete')
         THEN 'Move'
         WHEN MPAM.ORDER_TYPE = 'Modify' AND MPAM.SUB_ACTION_CODE IN('Transition-Add','Transition-Delete')
         THEN 'Add New Service'
         ELSE MPAM.ORDER_TYPE 
         END ATTRIBUTE60,
    MCAO.ACTION_CODE ATTRIBUTE61,
    MCAO.CONTRACT_START_DATE ATTRIBUTE62,
    NULL ATTRIBUTE63,
    SATO.PRODUCT ATTRIBUTE64,
    A1.ATTRIBUTE_VALUE ATTRIBUTE65,
    NULL ATTRIBUTE66,
    CASE WHEN A3.ATTRIBUTE_VALUE IS NOT NULL AND LT3.STRINGVALUE = 'Yes' AND LT4.STRINGVALUE = 'Yes'
         THEN A3.ATTRIBUTE_VALUE
         WHEN A3I.ATTRIBUTE_VALUE IS NOT NULL AND LT3.STRINGVALUE = 'Yes' AND LT4.STRINGVALUE = 'Yes'
         THEN A3I.ATTRIBUTE_VALUE
         WHEN LT3.STRINGVALUE = 'Yes' AND LT4.STRINGVALUE = 'Yes'
         THEN A3I.ATTRIBUTE_VALUE
         ELSE MO.HARDWARE_SUPPLIED_FLAG
         END ATTRIBUTE67, 
    NULL ATTRIBUTE68,
    MCDO.CONTRACT_START_DATE ATTRIBUTE69,
    NULL ATTRIBUTE70,NULL ATTRIBUTE71,
    A2.ATTRIBUTE_VALUE ATTRIBUTE72,
    NULL ATTRIBUTE73,NULL ATTRIBUTE74,NULL ATTRIBUTE75,NULL ATTRIBUTE76,NULL ATTRIBUTE77,
    NVL(LT.STRINGVALUE,'Non-Classified') ATTRIBUTE78,
    NULL ATTRIBUTE79, /*Detmined in Pass2*/
    NULL ATTRIBUTE80,
    MO.PART_NUMBER ATTRIBUTE81,
    NULL ATTRIBUTE82,NULL ATTRIBUTE83,NULL ATTRIBUTE84,NULL ATTRIBUTE85,NULL ATTRIBUTE86,NULL ATTRIBUTE87,
    MO.COMMISSION_PRODUCT_TYPE ATTRIBUTE88,
    NULL ATTRIBUTE89,NULL ATTRIBUTE90,NULL ATTRIBUTE91,NULL ATTRIBUTE92,NULL ATTRIBUTE93,NULL ATTRIBUTE94,NULL ATTRIBUTE95,NULL ATTRIBUTE96,NULL ATTRIBUTE97,NULL ATTRIBUTE98,NULL ATTRIBUTE99,NULL ATTRIBUTE100,
    NULL LAST_UPDATE_DATE,NULL CREATION_DATE,
    MPAM.CREATED_DATE BOOKED_DATE,
    'REVENUE' REVENUE_TYPE,
    NULL TYPE,NULL EMPLOYEE_NUMBER,NULL RECORD_STATUS,NULL ERROR_TYPE,NULL ERROR_MSG,
    MPAM.SOURCE_SYSTEM SOURCE,
    MPAM.SUBMITTED_DATE SUBMITTED_DATE,
    MPAM.STATUS_HEADER STATUS_HEADER,
    MPAM.STATUS_ORDER_LINE_ITEM STATUS_ORDER_LINE_ITEM,
    MPAM.ORIGINAL_ORDER_NUMBER,
    MO.EFFECTIVE_DATE EFFECTIVE_DATE
FROM 
  MP_OLI MO
  JOIN MP_ASSOC_MOLI              MPAM ON MPAM.ORDER_NUMBER = MO.ORDER_NUMBER AND MPAM.STATUS_HEADER = MO.STATUS_HEADER AND MPAM.ROW_ID = MO.ROOT_ITEM_ROW_ID
  LEFT JOIN MP_ASSOC_FHW_OLI           MAFO ON MAFO.ORDER_NUMBER = MO.ORDER_NUMBER AND MAFO.STATUS_HEADER = MO.STATUS_HEADER AND MAFO.ROOT_ITEM_ROW_ID = MO.ROOT_ITEM_ROW_ID
  LEFT JOIN MP_ASSOC_MAIN_CONT_ADD_OLI MCAO ON MCAO.ORDER_NUMBER = MO.ORDER_NUMBER AND MCAO.STATUS_HEADER = MO.STATUS_HEADER AND MCAO.ROOT_ITEM_ROW_ID = MO.ROOT_ITEM_ROW_ID
  LEFT JOIN MP_ASSOC_MAIN_CONT_DEL_OLI MCDO ON MCDO.ORDER_NUMBER = MO.ORDER_NUMBER AND MCDO.STATUS_HEADER = MO.STATUS_HEADER AND MCDO.ROOT_ITEM_ROW_ID = MO.ROOT_ITEM_ROW_ID
  LEFT JOIN MP_ASSOC_SERVICE_MOLI MASM
     ON MASM.ORDER_NUMBER = MPAM.ORDER_NUMBER
    AND MASM.PROMOTION_INTEGRATION_ID = MPAM.PROMOTION_INTEGRATION_ID
--    AND CASE WHEN MASM.STATUS_ORDER_LINE_ITEM = 'Complete' THEN CASE WHEN MASM.STATUS_HEADER = 'In-transit' THEN MASM.STATUS_ORDER_LINE_ITEM WHEN MASM.STATUS_HEADER = 'Provisioning' THEN MASM.STATUS_ORDER_LINE_ITEM ELSE MASM.STATUS_HEADER END ELSE MASM.STATUS_HEADER END = CASE WHEN MPAM.STATUS_ORDER_LINE_ITEM = 'Complete' THEN CASE WHEN MPAM.STATUS_HEADER = 'In-transit' THEN MPAM.STATUS_ORDER_LINE_ITEM WHEN MPAM.STATUS_HEADER = 'Provisioning' THEN MPAM.STATUS_ORDER_LINE_ITEM ELSE MPAM.STATUS_HEADER END ELSE MPAM.STATUS_HEADER END
    AND MASM.STATUS_ORDER_LINE_ITEM = MPAM.STATUS_ORDER_LINE_ITEM
  LEFT JOIN SERVICE_ASSOC_ACCESS_TYPE_OLI SATO ON SATO.ORDER_NUMBER = MASM.ORDER_NUMBER AND SATO.STATUS_HEADER = MASM.STATUS_HEADER AND SATO.ROOT_ITEM_ROW_ID = MASM.ROOT_ITEM_ROW_ID AND SATO.ACTION_CODE IN('Add','-')
  LEFT JOIN ATTRIBUTES                    A1 ON A1.ATTRIBUTE_OWNER_ROW_ID = MCAO.ROW_ID AND A1.ORDER_NUMBER = MCAO.ORDER_NUMBER AND A1.ATTRIBUTE_DISPLAY_NAME = 'Contract Term'
  LEFT JOIN ATTRIBUTES                    A2 ON A2.ATTRIBUTE_OWNER_ROW_ID = MCDO.ROW_ID AND A2.ORDER_NUMBER = MCDO.ORDER_NUMBER AND A2.ATTRIBUTE_DISPLAY_NAME = 'Contract Term'
  LEFT JOIN ATTRIBUTES                    A3 ON A3.ATTRIBUTE_OWNER_ROW_ID = MAFO.ROW_ID AND A3.ORDER_NUMBER = MAFO.ORDER_NUMBER AND A3.ATTRIBUTE_DISPLAY_NAME LIKE 'Supplied in Store%'
  LEFT JOIN ATTRIBUTES                   A3I ON A3I.ATTRIBUTE_OWNER_ROW_ID = MAFO.ROW_ID AND A3I.ORDER_NUMBER = MAFO.ORDER_NUMBER AND A3I.ATTRIBUTE_DISPLAY_NAME = 'Hardware Supplied'
  LEFT JOIN LT_SALES_TYPE_MAIN_PLAN       LT ON LT.IDX_NAME_0 = NVL(MO.ORDER_TYPE,'NULL')    AND LT.IDX_NAME_1 = NVL(MO.ORDER_SUB_TYPE,'NULL') 
                                                  AND LT.IDX_NAME_2 = NVL(MO.TRANSFER_TYPE,'NULL') AND LT.IDX_NAME_3 = NVL(MASM.ACTION_CODE,'NULL') 
                                                  AND LT.IDX_NAME_4 = NVL(MASM.ACTION_CODE,'NULL') AND LT.IDX_NAME_5 = NVL(MCAO.ACTION_CODE,'NULL') 
                                                  AND LT.IDX_NAME_6 = NVL(MCDO.ACTION_CODE,'NULL') AND LT.IDX_NAME_7 = NVL(MO.COMMISSION_PRODUCT_TYPE,'NULL')
                                                  AND LT.IDX_NAME_8 = NVL(CASE WHEN MPAM.PRODUCT = 'Mobile Service' AND MPAM.REASON_CODE = 'Migration to Siebel' AND MPAM.ORDER_TYPE = 'Add New Service' THEN MPAM.REASON_CODE ELSE NULL END,'NULL')
                                                  AND LT.STARTDATE <= TO_DATE(NVL(MO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT.ENDDATE > TO_DATE(NVL(MO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
  LEFT JOIN LT_PLAN_VAS_HW_RO            LT3 ON LT3.IDX_NAME_0 = MAFO.PART_NUMBER AND LT3.IDX_NAME_1 = 'PLAN HW' AND LT3.STRINGVALUE = 'Yes' AND LT3.STARTDATE <= TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT3.ENDDATE > TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
  LEFT JOIN LT_PLAN_VAS_HW_RO            LT4 ON LT4.IDX_NAME_0 = MO.PART_NUMBER AND LT4.IDX_NAME_1 = 'PLAN' AND LT4.STRINGVALUE = 'Yes' AND LT4.STARTDATE <= TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT4.ENDDATE > TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
WHERE (1=1)
  AND NVL(MO.ORDER_SUB_TYPE, 'NULL') <> 'Transfer' 
  AND MO.NGB_PROD_TYPE = 'MOC' 
  AND MPAM.COMMISSION_PRODUCT_TYPE = 'Commissions Standalone'
--  AND MO.ROW_ID = '1-LTSZLOFU';
)
SELECT 
    P1.FILENAME,P1.BATCHPROCESSDATE,P1.RECORDNUMBER,P1.PROCESSED_DATE,P1.PROCESSED_PERIOD_ID,P1.TRANSACTION_AMOUNT,P1.QUANTITY,P1.ATTRIBUTE1,P1.ATTRIBUTE2,P1.ATTRIBUTE3,P1.ATTRIBUTE4,P1.ATTRIBUTE5,P1.ATTRIBUTE6,P1.ATTRIBUTE7,P1.ATTRIBUTE8,P1.ATTRIBUTE9,P1.ATTRIBUTE10,P1.ATTRIBUTE11,
    P1.ATTRIBUTE12,P1.ATTRIBUTE13,P1.ATTRIBUTE14,P1.ATTRIBUTE15,P1.ATTRIBUTE16,P1.ATTRIBUTE17,P1.ATTRIBUTE18,P1.ATTRIBUTE19,P1.ATTRIBUTE20,P1.ATTRIBUTE21,P1.ATTRIBUTE22,P1.ATTRIBUTE23,P1.ATTRIBUTE24,P1.ATTRIBUTE25,P1.ATTRIBUTE26,P1.ATTRIBUTE27,P1.ATTRIBUTE28,P1.ATTRIBUTE29,P1.ATTRIBUTE30,
    P1.ATTRIBUTE31,P1.ATTRIBUTE32,P1.ATTRIBUTE33,P1.ATTRIBUTE34,P1.ATTRIBUTE35,P1.ATTRIBUTE36,P1.ATTRIBUTE37,P1.ATTRIBUTE38,P1.ATTRIBUTE39,P1.ATTRIBUTE40,P1.ATTRIBUTE41,P1.ATTRIBUTE42,P1.ATTRIBUTE43,P1.ATTRIBUTE44,P1.ATTRIBUTE45,P1.ATTRIBUTE46,P1.ATTRIBUTE47,P1.ATTRIBUTE48,P1.ATTRIBUTE49,
    P1.ATTRIBUTE50,P1.ATTRIBUTE51,P1.ATTRIBUTE52,P1.ATTRIBUTE53,P1.ATTRIBUTE54,P1.ATTRIBUTE55,P1.ATTRIBUTE56,P1.ATTRIBUTE57,P1.ATTRIBUTE58,P1.ATTRIBUTE59,P1.ATTRIBUTE60,P1.ATTRIBUTE61,P1.ATTRIBUTE62,P1.ATTRIBUTE63,P1.ATTRIBUTE64,P1.ATTRIBUTE65,P1.ATTRIBUTE66,P1.ATTRIBUTE67,P1.ATTRIBUTE68,
    P1.ATTRIBUTE69,P1.ATTRIBUTE70,P1.ATTRIBUTE71,P1.ATTRIBUTE72,P1.ATTRIBUTE73,P1.ATTRIBUTE74,P1.ATTRIBUTE75,P1.ATTRIBUTE76,P1.ATTRIBUTE77,P1.ATTRIBUTE78,
    CASE WHEN (P1.ATTRIBUTE62 IS NULL OR P1.ATTRIBUTE69 IS NULL OR P1.ATTRIBUTE72 IS NULL) 
              OR (TRUNC(TO_DATE(P1.ATTRIBUTE69,'dd/mm/yyyy hh24:mi:ss')) + ((P1.ATTRIBUTE72/12)*365) - TRUNC(TO_DATE(P1.ATTRIBUTE62,'dd/mm/yyyy hh24:mi:ss'))) <= LT1.VALUE
         THEN 'No'
         ELSE 'Yes'
         END ATTRIBUTE79,
    P1.ATTRIBUTE80,P1.ATTRIBUTE81,P1.ATTRIBUTE82,P1.ATTRIBUTE83,P1.ATTRIBUTE84,P1.ATTRIBUTE85,P1.ATTRIBUTE86,P1.ATTRIBUTE87,P1.ATTRIBUTE88,P1.ATTRIBUTE89,P1.ATTRIBUTE90,P1.ATTRIBUTE91,P1.ATTRIBUTE92,P1.ATTRIBUTE93,P1.ATTRIBUTE94,P1.ATTRIBUTE95,P1.ATTRIBUTE96,P1.ATTRIBUTE97,P1.ATTRIBUTE98,
    P1.ATTRIBUTE99,P1.ATTRIBUTE100,P1.LAST_UPDATE_DATE,P1.CREATION_DATE,P1.BOOKED_DATE,P1.REVENUE_TYPE,P1.TYPE,P1.EMPLOYEE_NUMBER,P1.RECORD_STATUS,P1.ERROR_TYPE,P1.ERROR_MSG,P1.SOURCE,P1.FILENAME,P1.RECORDNUMBER,P1.SUBMITTED_DATE,P1.STATUS_HEADER,P1.STATUS_ORDER_LINE_ITEM,P1.ORIGINAL_ORDER_NUMBER
FROM PASS1 P1
  LEFT OUTER JOIN PRODUCT                   PRD ON PRD.NAME = P1.ATTRIBUTE39
  LEFT OUTER JOIN LT_ALLOWABLE_RECON_PERIOD LT1 ON LT1.IDX_NAME_0 = PRD.GENERICATTRIBUTE1 AND LT1.IDX_NAME_1 = P1.ATTRIBUTE65 AND LT1.STARTDATE <= TO_DATE(NVL(P1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT1.ENDDATE > TO_DATE(NVL(P1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')