SELECT * FROM TELS_CONFIG;

SELECT * FROM TELS_RCRM_ROW_SOURCE WHERE ROW_ID IN('1-OFYE3FLQ','1-O6P4KOI9','1-NZ792AN0');
SELECT * FROM TELS_PRESTAGE_RCRM WHERE ROW_ID IN('1-OFYE3FLQ','1-O6P4KOI9','1-NZ792AN0');
SELECT * FROM TELS_STAGE_RCRM WHERE ROW_ID IN('1-OFYE3FLQ','1-O6P4KOI9','1-NZ792AN0');
SELECT * FROM TELS_STAGE_RCRM_PPE WHERE ATTRIBUTE46 IN('1-OASKQ2E5');

SELECT *
FROM TELS_STAGE_RCRM_PPE WHERE ATTRIBUTE46 IN('1-OQSG34OD');