WITH ATTRIBUTES AS(
    SELECT D.FILENAME, D.RECORDNUMBER, D.ORDER_NUMBER, D.ROW_ID ATTRIBUTE_OWNER_ROW_ID, D.ATTRIBUTE_ROW_ID, D.ATTRIBUTE_ACTION_CODE, D.ATTRIBUTE_DISPLAY_NAME, D.ATTRIBUTE_VALUE
    FROM TELS_RCRM_ATTRIBUTES_VIEW D
    WHERE D.ATTRIBUTE_ROW_ID IS NOT NULL)
, DARO_MOLI AS (
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'DARO_MOLI')
,
DARO_ASSOC_FHW_OLI AS(
  SELECT * FROM (
    SELECT
      V.*
      , ROW_NUMBER() OVER (PARTITION BY V.ORDER_NUMBER, V.STATUS_HEADER, V.ROOT_ITEM_ROW_ID, V.PART_NUMBER ORDER BY V.ROW_ID DESC) AS "ROW_NUMBER"
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE V.REC_TYPE = 'DARO_ASSOC_FHW_OLI'
    )
  WHERE ROW_NUMBER = 1
  )
,
DARO_ASSOC_SERVICE_MOLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'DARO_ASSOC_SERVICE_MOLI')
, LT_DARO_OFFSET AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.VALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_DARO_Offset')
, LT_DARO_BUNDLE_REBATE AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.VALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_DARO_Bundle_Rebate')
SELECT 
    D.FILENAME,
    D.BATCHPROCESSDATE,
    D.RECORDNUMBER,
    D.PROVISIONED_DATE PROCESSED_DATE,
    NULL PROCESSED_PERIOD_ID,
    D.LIST_PRICE TRANSACTION_AMOUNT,
    A1.ATTRIBUTE_VALUE QUANTITY,
    D.CUSTOMER_LAST_NAME ATTRIBUTE1,
    D.CUSTOMER_FIRST_NAME ATTRIBUTE2,
    NULL ATTRIBUTE3,NULL ATTRIBUTE4,NULL ATTRIBUTE5,NULL ATTRIBUTE6,NULL ATTRIBUTE7,NULL ATTRIBUTE8,NULL ATTRIBUTE9,NULL ATTRIBUTE10,NULL ATTRIBUTE11,NULL ATTRIBUTE12,NULL ATTRIBUTE13,NULL ATTRIBUTE14,NULL ATTRIBUTE15,NULL ATTRIBUTE16,NULL ATTRIBUTE17,NULL ATTRIBUTE18,NULL ATTRIBUTE19,NULL ATTRIBUTE20,NULL ATTRIBUTE21,NULL ATTRIBUTE22,NULL ATTRIBUTE23,NULL ATTRIBUTE24,
    D.ORDER_NUMBER ATTRIBUTE25,
    D.BILLING_ACCOUNT ATTRIBUTE26,
    D.PARTNER_CODE ATTRIBUTE27,
    NULL ATTRIBUTE28,NULL ATTRIBUTE29,NULL ATTRIBUTE30,NULL ATTRIBUTE31,NULL ATTRIBUTE32,NULL ATTRIBUTE33,NULL ATTRIBUTE34,
    D.BUSINESS_UNIT ATTRIBUTE35,
    D.SALES_FORCE_ID ATTRIBUTE36,
    'COMMISSIONABLE TRANSACTION' ATTRIBUTE37,
    D.SOURCE_SYSTEM ATTRIBUTE38,
    D.PRODUCT ATTRIBUTE39,
    NULL ATTRIBUTE40,
    D.ACTION_CODE ATTRIBUTE41,
    D.TRANSFER_TYPE ATTRIBUTE42,
    CASE WHEN DASM.EVENT_SOURCE IS NOT NULL 
         THEN DASM.EVENT_SOURCE
         ELSE D.EVENT_SOURCE 
         END ATTRIBUTE43,
    CASE WHEN DASM.PROMOTION_PART_NUMBER IS NOT NULL 
         THEN DASM.PROMOTION_PART_NUMBER
         ELSE D.PROMOTION_PART_NUMBER 
         END ATTRIBUTE44,
    D.ORDER_SUB_TYPE ATTRIBUTE45,
    D.ROW_ID ATTRIBUTE46,
    A2.ATTRIBUTE_VALUE ATTRIBUTE47,
    NULL ATTRIBUTE48,
    D.ACTION_CODE ATTRIBUTE49,
    D.PROMOTION_PART_NUMBER ATTRIBUTE50,
    NULL ATTRIBUTE51,NULL ATTRIBUTE52,NULL ATTRIBUTE53,
    CASE WHEN LT.VALUE IS NOT NULL
         THEN 'DAROZ'
         WHEN EXISTS(SELECT 1 FROM LT_DARO_BUNDLE_REBATE LT WHERE LT.IDX_NAME_0 = NVL(D.PART_NUMBER,'NULL') AND LT.STARTDATE <= TO_DATE(NVL(D.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT.ENDDATE > TO_DATE(NVL(D.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss'))
         THEN 'Subsidised'
         END ATTRIBUTE54,
    NULL ATTRIBUTE55,NULL ATTRIBUTE56,NULL ATTRIBUTE57,NULL ATTRIBUTE58,
    A3.ATTRIBUTE_VALUE ATTRIBUTE59,
    D.ORDER_TYPE ATTRIBUTE60,
    NULL ATTRIBUTE61,NULL ATTRIBUTE62,NULL ATTRIBUTE63,NULL ATTRIBUTE64,
    A4.ATTRIBUTE_VALUE ATTRIBUTE65,
    NULL ATTRIBUTE66,
    CASE
      WHEN ATT_P1.ATTRIBUTE_VALUE IS NOT NULL THEN ATT_P1.ATTRIBUTE_VALUE
      WHEN ATT_P2.ATTRIBUTE_VALUE IS NOT NULL THEN ATT_P2.ATTRIBUTE_VALUE
      WHEN DAFO.HARDWARE_SUPPLIED_FLAG IS NOT NULL THEN DAFO.HARDWARE_SUPPLIED_FLAG
      WHEN ATT_P4.ATTRIBUTE_VALUE IS NOT NULL THEN ATT_P4.ATTRIBUTE_VALUE
      ELSE D.HARDWARE_SUPPLIED_FLAG
    END AS "ATTRIBUTE67",
    NULL ATTRIBUTE68,NULL ATTRIBUTE69,NULL ATTRIBUTE70,NULL ATTRIBUTE71,NULL ATTRIBUTE72,NULL ATTRIBUTE73,NULL ATTRIBUTE74,NULL ATTRIBUTE75,NULL ATTRIBUTE76,NULL ATTRIBUTE77,NULL ATTRIBUTE78,NULL ATTRIBUTE79,NULL ATTRIBUTE80,
    A6.ATTRIBUTE_VALUE ATTRIBUTE81,
    CASE WHEN TO_CHAR(LT.VALUE) IS NOT NULL
         THEN TO_CHAR(LT.VALUE)
         ELSE A7.ATTRIBUTE_VALUE 
         END ATTRIBUTE82, 
    NULL ATTRIBUTE83,NULL ATTRIBUTE84,NULL ATTRIBUTE85,NULL ATTRIBUTE86,NULL ATTRIBUTE87,
    D.COMMISSION_PRODUCT_TYPE ATTRIBUTE88,
    NULL ATTRIBUTE89,NULL ATTRIBUTE90,NULL ATTRIBUTE91,NULL ATTRIBUTE92,NULL ATTRIBUTE93,NULL ATTRIBUTE94,NULL ATTRIBUTE95,NULL ATTRIBUTE96,NULL ATTRIBUTE97,NULL ATTRIBUTE98,NULL ATTRIBUTE99,NULL ATTRIBUTE100,
    NULL LAST_UPDATE_DATE,NULL CREATION_DATE,
    D.CREATED_DATE BOOKED_DATE,
    'REVENUE' REVENUE_TYPE,
    NULL TYPE,NULL EMPLOYEE_NUMBER,NULL RECORD_STATUS,NULL ERROR_TYPE,NULL ERROR_MSG,
    D.SOURCE_SYSTEM SOURCE,
    D.FILENAME, D.RECORDNUMBER,
    D.SUBMITTED_DATE SUBMITTED_DATE,
    D.STATUS_HEADER STATUS_HEADER,
    D.STATUS_ORDER_LINE_ITEM STATUS_ORDER_LINE_ITEM,
    D.ORIGINAL_ORDER_NUMBER
FROM 
  DARO_MOLI D
  LEFT OUTER JOIN DARO_ASSOC_SERVICE_MOLI DASM ON DASM.ORDER_NUMBER = D.ORDER_NUMBER AND DASM.STATUS_HEADER = D.STATUS_HEADER AND DASM.ROW_ID = D.ROOT_ITEM_ROW_ID
  LEFT OUTER JOIN ATTRIBUTES     A1 ON A1.ATTRIBUTE_OWNER_ROW_ID = D.ROW_ID AND A1.ORDER_NUMBER = D.ORDER_NUMBER AND A1.ATTRIBUTE_DISPLAY_NAME = 'Quantity'
  LEFT OUTER JOIN ATTRIBUTES     A2 ON A2.ATTRIBUTE_OWNER_ROW_ID = D.ROW_ID AND A2.ORDER_NUMBER = D.ORDER_NUMBER AND A2.ATTRIBUTE_DISPLAY_NAME IN('Product Name','Associated Product')
  LEFT OUTER JOIN ATTRIBUTES     A3 ON A3.ATTRIBUTE_OWNER_ROW_ID = D.ROW_ID AND A3.ORDER_NUMBER = D.ORDER_NUMBER AND A3.ATTRIBUTE_DISPLAY_NAME = 'Serial Number'
  LEFT OUTER JOIN ATTRIBUTES     A4 ON A4.ATTRIBUTE_OWNER_ROW_ID = D.ROW_ID AND A4.ORDER_NUMBER = D.ORDER_NUMBER AND A4.ATTRIBUTE_DISPLAY_NAME = 'Contract Term'
  LEFT OUTER JOIN ATTRIBUTES     A7 ON A7.ATTRIBUTE_OWNER_ROW_ID = D.ROW_ID AND A7.ORDER_NUMBER = D.ORDER_NUMBER AND A7.ATTRIBUTE_DISPLAY_NAME = 'Repayment Amount'
  LEFT JOIN ATTRIBUTES A6
     ON A6.ATTRIBUTE_OWNER_ROW_ID = D.ROW_ID
    AND A6.ORDER_NUMBER = D.ORDER_NUMBER
    AND NVL(A6.ATTRIBUTE_DISPLAY_NAME, 'NULL') IN ('Product Id','Associated Product Part Number')
  LEFT JOIN DARO_ASSOC_FHW_OLI DAFO
     ON DAFO.ORDER_NUMBER = D.ORDER_NUMBER
    AND DAFO.STATUS_HEADER = D.STATUS_HEADER
    AND DAFO.ROOT_ITEM_ROW_ID = D.ROOT_ITEM_ROW_ID
    AND DAFO.PART_NUMBER = A6.ATTRIBUTE_VALUE
  LEFT OUTER JOIN ATTRIBUTES ATT_P1
     ON ATT_P1.ATTRIBUTE_OWNER_ROW_ID = DAFO.ROW_ID
    AND ATT_P1.ORDER_NUMBER = DAFO.ORDER_NUMBER
    AND NVL(ATT_P1.ATTRIBUTE_DISPLAY_NAME, 'NULL') IN ('Supplied in Store?', 'Supplied in Store')
  LEFT OUTER JOIN ATTRIBUTES ATT_P2
     ON ATT_P2.ATTRIBUTE_OWNER_ROW_ID = DAFO.ROW_ID
    AND ATT_P2.ORDER_NUMBER = DAFO.ORDER_NUMBER
    AND ATT_P2.ATTRIBUTE_DISPLAY_NAME = 'Hardware Supplied'
  LEFT OUTER JOIN ATTRIBUTES ATT_P4
     ON ATT_P4.ATTRIBUTE_OWNER_ROW_ID = D.ROW_ID
    AND ATT_P4.ORDER_NUMBER = D.ORDER_NUMBER
    AND ATT_P4.ATTRIBUTE_DISPLAY_NAME = 'Hardware Supplied'
  LEFT OUTER JOIN LT_DARO_OFFSET LT ON LT.IDX_NAME_0 = NVL(D.PART_NUMBER,'NULL') AND LT.IDX_NAME_1 = NVL(A7.ATTRIBUTE_VALUE,'NULL') AND LT.STARTDATE <= TO_DATE(NVL(D.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT.ENDDATE > TO_DATE(NVL(D.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
WHERE NVL(D.ORDER_SUB_TYPE,'NULL') <> 'Transfer'