SELECT * 
  FROM TELS_STAGE_RCRM_PPE WHERE ATTRIBUTE46 IN('1-OFOONSEI',
'1-O35AEXE4',
'1-OHP49DLR',
'1-OHP49DPU',
'1-O7FGYNU5',
'1-N19NJXFM',
'1-OMQ34CCA',
'1-OMQ34CD7',
'1-OMZ8HAO8',
'1-OEBF7WFH',
'1-OEBF7WJS',
'1-OF2RZ45N',
'1-OBCOBCAS',
'1-OBCOBCCH',
'1-OHJEIIUJ',
'1-OLHN5OM2',
'1-ONPFX25P',
'1-OHQUXA13',
'1-OIUCFMUG',
'1-ONKBTRKZ',
'1-OMT1W51T',
'1-OMT1W502',
'1-OF3YDO50',
'1-OHJEIISN',
'1-OHQUX9ZE',
'1-O7C55L2J',
'1-OI91INDA')
;



SELECT O_ATTRIBUTE78, C_ATTRIBUTE78
FROM test_preproc_comparison WHERE O_ATTRIBUTE46 = '1-OF2RZ45N';

SELECT * FROM TELS_STAGE_RCRM_PPE WHERE ATTRIBUTE46 = '1-OF2RZ45N';

SELECT rcrm.BATCHPROCESSDATE, rcrm.ATTRIBUTE46 rcrm_ROW_ID, ppe.ATTRIBUTE46 ppe_ROW_ID, rcrm.ATTRIBUTE25 order_num, rcrm.QUERY_SRC, ppe.ATTRIBUTE53 ppe_ATTRIBUTE53, rcrm.ATTRIBUTE53 rcrm_ATTRIBUTE53
FROM TELS_STAGE_RCRM_PPE rcrm
left outer JOIN TELS_STAGE_RCRM_PPE ppe ON
  ppe.ATTRIBUTE46 = rcrm.ATTRIBUTE46 --row id
  AND ppe.ATTRIBUTE25 = rcrm.ATTRIBUTE25 --order number
  AND nvl(trim(ppe.ATTRIBUTE53),'X') <> nvl(trim(rcrm.ATTRIBUTE53),'X') --comments
WHERE rcrm.SOURCE = 'CCB-RCRM'
  AND ppe.SOURCE = 'SIEBEL'
  AND rcrm.BATCHPROCESSDATE = (SELECT MAX(BATCHPROCESSDATE) BATCHPROCESSDATE FROM TELS_STAGE_RCRM_PPE WHERE SOURCE = 'CCB-RCRM')
;

WITH
  ATTRIBUTES AS(
    SELECT D.FILENAME, D.RECORDNUMBER, D.ORDER_NUMBER, D.ROW_ID ATTRIBUTE_OWNER_ROW_ID, D.ATTRIBUTE_ROW_ID, D.ATTRIBUTE_ACTION_CODE, D.ATTRIBUTE_DISPLAY_NAME, D.ATTRIBUTE_VALUE
    FROM TELS_RCRM_ATTRIBUTES_VIEW D
    WHERE D.ATTRIBUTE_ROW_ID IS NOT NULL)
  ,MP_ASSOC_MAIN_CONT_ADD_OLI AS (
    SELECT V.*
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE V.REC_TYPE = 'MP_ASSOC_MAIN_CONT_ADD_OLI'
    )
  ,MP_ASSOC_MAIN_CONT_DEL_OLI AS (
    SELECT V.*
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE V.REC_TYPE = 'MP_ASSOC_MAIN_CONT_DEL_OLI'
    )
  ,MP_ASSOC_MOLI AS (
    SELECT V.*
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE V.REC_TYPE = 'MP_ASSOC_MOLI'
    )
  ,MP_OLI AS (
    SELECT V.*
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE V.REC_TYPE = 'MP_OLI'
    )
  ,SERVICE_MOLI AS (
    SELECT V.*
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE V.REC_TYPE = 'SERVICE_MOLI'
    AND V.SUB_ACTION_CODE IN ('Move-Add', 'Transition-Add')
    )
  ,MP_ASSOC_FHW_OLI AS (
    SELECT V.*
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE V.REC_TYPE = 'MP_ASSOC_FHW_OLI'
    )
  ,SERVICE_ASSOC_ACCESS_TYPE_OLI AS (
    -- Select only the first record, ordered by Provisioned Date, for each distinct Order Number, Status Header, and Root Item Row Id
    -- Some Service Assoc Access Type OLIs will have multiple iterations with different statuses, select only the first one
    SELECT V.*, ROW_NUMBER() OVER (PARTITION BY V.ORDER_NUMBER, V.STATUS_HEADER, V.ROOT_ITEM_ROW_ID ORDER BY V.PROVISIONED_DATE ASC) AS RECORD_SEQ
    FROM TELS_RCRM_ORDERS_VIEW V
    WHERE (1=1)
    AND V.REC_TYPE = 'SERVICE_ASSOC_ACCESS_TYPE_OLI'
    AND V.ACTION_CODE IN ('Add', '-', 'Update')
    )
--  , MP_ASSOC_SERVICE_MOLI AS (
--    -- Select only the first record, ordered by Row Id, for each distinct Row Id
--    -- We only need to check for the existence of a Row Id, don't select multiple rows for each
--    SELECT V.ROW_ID, ROW_NUMBER() OVER (PARTITION BY V.ROW_ID ORDER BY V.ROW_ID) AS RECORD_SEQ
--    FROM TELS_RCRM_ORDERS_VIEW V
--    WHERE (1=1)
--    AND V.REC_TYPE = 'MP_ASSOC_SERVICE_MOLI'
--  )
  ,LT_SALES_TYPE_MAIN_PLAN AS (
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.DIM_NAME_2, LT.IDX_NAME_2, LT.DIM_NAME_3, LT.IDX_NAME_3, LT.DIM_NAME_4, LT.IDX_NAME_4, LT.DIM_NAME_5, LT.IDX_NAME_5, LT.DIM_NAME_6, LT.IDX_NAME_6, LT.DIM_NAME_7, LT.IDX_NAME_7, LT.DIM_NAME_8, LT.IDX_NAME_8, LT.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Sales_Type_Main_Plan'
    )
  ,LT_PLAN_VAS_HW_RO AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Plan_VAS_HW_RO')
, LT_ALLOWABLE_RECON_PERIOD AS(
    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.VALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Allowable_Recon_Period')
, PRODUCT AS(
    SELECT CLS.NAME, PRD.GENERICATTRIBUTE1 
    FROM   
      CS_CATEGORYTREE@TC_LINK CTR 
      JOIN CS_CATEGORY_CLASSIFIERS@TC_LINK CCL ON
        CCL.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND CCL.CATEGORYTREESEQ = CTR.CATEGORYTREESEQ
        AND CCL.TENANTID = CTR.TENANTID
      JOIN CS_CLASSIFIER@TC_LINK CLS ON
        CLS.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND CLS.CLASSIFIERSEQ = CCL.CLASSIFIERSEQ
        AND CLS.TENANTID = CCL.TENANTID
      JOIN CS_PRODUCT@TC_LINK PRD ON
        PRD.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND PRD.CLASSIFIERSEQ = CLS.CLASSIFIERSEQ
        AND PRD.TENANTID = CLS.TENANTID
    WHERE
        CTR.REMOVEDATE = TO_DATE('01-01-2200','DD-MM-YYYY')
        AND CTR.TENANTID = 'TELS'
        AND CTR.NAME = 'Product_Category'
    GROUP BY CLS.NAME, PRD.GENERICATTRIBUTE1) -- !!! Needs to be fixed for effective dating
, PASS1 AS(
    SELECT
        SM.FILENAME AS FILENAME
      , SM.BATCHPROCESSDATE AS BATCHPROCESSDATE
      , SM.RECORDNUMBER AS RECORDNUMBER
      , SM.PROVISIONED_DATE AS PROCESSED_DATE
      , '' AS PROCESSED_PERIOD_ID
      , SM.LIST_PRICE AS TRANSACTION_AMOUNT
      , '1' AS QUANTITY
      , SM.CUSTOMER_LAST_NAME AS ATTRIBUTE1
      , SM.CUSTOMER_FIRST_NAME AS ATTRIBUTE2
      , '' AS ATTRIBUTE3, '' AS ATTRIBUTE4, '' AS ATTRIBUTE5, '' AS ATTRIBUTE6, '' AS ATTRIBUTE7, '' AS ATTRIBUTE8, '' AS ATTRIBUTE9, '' AS ATTRIBUTE10, '' AS ATTRIBUTE11, '' AS ATTRIBUTE12, '' AS ATTRIBUTE13
      , '' AS ATTRIBUTE14, '' AS ATTRIBUTE15, '' AS ATTRIBUTE16, '' AS ATTRIBUTE17, '' AS ATTRIBUTE18, '' AS ATTRIBUTE19, '' AS ATTRIBUTE20, '' AS ATTRIBUTE21, '' AS ATTRIBUTE22, '' AS ATTRIBUTE23, '' AS ATTRIBUTE24
      , SM.ORDER_NUMBER AS ATTRIBUTE25
      , SM.BILLING_ACCOUNT AS ATTRIBUTE26
      , SM.PARTNER_CODE AS ATTRIBUTE27
      , '' AS ATTRIBUTE28, '' AS ATTRIBUTE29, '' AS ATTRIBUTE30, '' AS ATTRIBUTE31, '' AS ATTRIBUTE32, '' AS ATTRIBUTE33, '' AS ATTRIBUTE34
      , SM.BUSINESS_UNIT AS ATTRIBUTE35
      , SM.SALES_FORCE_ID AS ATTRIBUTE36
      , 'COMMISSIONABLE TRANSACTION' AS ATTRIBUTE37
      , SM.SOURCE_SYSTEM AS ATTRIBUTE38
      , SM.PRODUCT AS ATTRIBUTE39
      , '' AS ATTRIBUTE40
      , SM.ACTION_CODE AS ATTRIBUTE41
      , SM.TRANSFER_TYPE AS ATTRIBUTE42
      , SM.EVENT_SOURCE AS ATTRIBUTE43
      , SM.PROMOTION_PART_NUMBER AS ATTRIBUTE44
      , CASE
          WHEN SM.ORDER_TYPE = 'Modify' AND SM.SUB_ACTION_CODE IN ('Transition-Add') 
          THEN 'Transition' 
          ELSE SM.ORDER_SUB_TYPE 
        END AS ATTRIBUTE45
      , SM.ROW_ID AS ATTRIBUTE46
      , SM.PRODUCT AS ATTRIBUTE47
      , '' AS ATTRIBUTE48
      , SM.ACTION_CODE AS ATTRIBUTE49
      , SM.PROMOTION_PART_NUMBER AS ATTRIBUTE50
      , '' AS ATTRIBUTE51, '' AS ATTRIBUTE52, '' AS ATTRIBUTE53, '' AS ATTRIBUTE54, '' AS ATTRIBUTE55, '' AS ATTRIBUTE56, '' AS ATTRIBUTE57, '' AS ATTRIBUTE58, '' AS ATTRIBUTE59
      , CASE WHEN SM.ORDER_TYPE = 'Modify' AND SM.SUB_ACTION_CODE IN ('Move-Add')
             THEN 'Move'
             WHEN SM.ORDER_TYPE = 'Modify' AND SM.SUB_ACTION_CODE IN ('Transition-Add')
             THEN 'Add New Service'
             ELSE SM.ORDER_TYPE 
         END AS ATTRIBUTE60
      , mcao.ACTION_CODE AS ATTRIBUTE61
      , mcao.CONTRACT_START_DATE AS ATTRIBUTE62
      , '' AS ATTRIBUTE63
      , SAATO.PRODUCT AS ATTRIBUTE64
      , a1.ATTRIBUTE_VALUE AS ATTRIBUTE65
      , '' AS ATTRIBUTE66
      , CASE WHEN A2.ATTRIBUTE_VALUE IS NOT NULL AND LT1.STRINGVALUE = 'Yes' AND LT2.STRINGVALUE = 'Yes'
             THEN A2.ATTRIBUTE_VALUE
             WHEN A3.ATTRIBUTE_VALUE IS NOT NULL AND LT1.STRINGVALUE = 'Yes' AND LT2.STRINGVALUE = 'Yes'
             THEN A3.ATTRIBUTE_VALUE
             WHEN LT1.STRINGVALUE = 'Yes' AND LT2.STRINGVALUE = 'Yes'
             THEN MAFO.HARDWARE_SUPPLIED_FLAG
             ELSE MO.HARDWARE_SUPPLIED_FLAG
             END ATTRIBUTE67
      , '' AS ATTRIBUTE68
      , MCDO.CONTRACT_START_DATE AS ATTRIBUTE69
      , '' AS ATTRIBUTE70, '' AS ATTRIBUTE71
      , A4.ATTRIBUTE_VALUE AS ATTRIBUTE72
      , '' AS ATTRIBUTE73, '' AS ATTRIBUTE74, '' AS ATTRIBUTE75, '' AS ATTRIBUTE76, '' AS ATTRIBUTE77
      , '' AS ATTRIBUTE78 /*Determined in P2 as overrides here influence the lookup*/
      , NULL AS ATTRIBUTE79 /*Determined in P2*/
      , '' AS ATTRIBUTE80
      , SM.PART_NUMBER AS ATTRIBUTE81
      , '' AS ATTRIBUTE82, '' AS ATTRIBUTE83, '' AS ATTRIBUTE84, '' AS ATTRIBUTE85, '' AS ATTRIBUTE86, '' AS ATTRIBUTE87
      , 'Commissions Main Plan' AS ATTRIBUTE88
      , '' AS ATTRIBUTE89, '' AS ATTRIBUTE90, '' AS ATTRIBUTE91, '' AS ATTRIBUTE92, '' AS ATTRIBUTE93, '' AS ATTRIBUTE94, '' AS ATTRIBUTE95, '' AS ATTRIBUTE96, '' AS ATTRIBUTE97, '' AS ATTRIBUTE98, '' AS ATTRIBUTE99, '' AS ATTRIBUTE100
      , NULL AS LAST_UPDATE_DATE, NULL AS CREATION_DATE
      , SM.CREATED_DATE AS BOOKED_DATE
      , 'REVENUE' AS REVENUE_TYPE
      , '' AS TYPE, '' AS EMPLOYEE_NUMBER, '' AS RECORD_STATUS, '' AS ERROR_TYPE, '' AS ERROR_MSG
      , SM.SOURCE_SYSTEM AS SOURCE
      , SM.FILENAME AS FILE_NAME
      , SM.RECORDNUMBER AS RECORD_NUMBER
      , SM.SUBMITTED_DATE AS SUBMITTED_DATE
      , SM.STATUS_HEADER AS STATUS_HEADER
      , SM.STATUS_ORDER_LINE_ITEM AS STATUS_ORDER_LINE_ITEM
      , SM.ORIGINAL_ORDER_NUMBER AS ORIGINAL_ORDER_NUMBER
      , SM.EFFECTIVE_DATE EFFECTIVE_DATE 
      , MCDO.ACTION_CODE MCDO_ACTION_CODE
      , MPAM.PRODUCT MPAM_PRODUCT
      , MPAM.REASON_CODE MPAM_REASON_CODE
      , MPAM.ORDER_TYPE MPAM_ORDER_TYPE
    FROM SERVICE_MOLI SM
        LEFT JOIN SERVICE_ASSOC_ACCESS_TYPE_OLI SAATO
           ON SAATO.ORDER_NUMBER = SM.ORDER_NUMBER
          AND SAATO.STATUS_HEADER = SM.STATUS_HEADER
          AND SAATO.ROOT_ITEM_ROW_ID = SM.ROOT_ITEM_ROW_ID
          AND SAATO.RECORD_SEQ = 1
        --LEFT JOIN MP_ASSOC_SERVICE_MOLI MASM
        --   ON MASM.ROW_ID = SM.ROW_ID
        --  AND MASM.RECORD_SEQ = 1
        LEFT JOIN MP_ASSOC_MOLI             MPAM  ON MPAM.ORDER_NUMBER = SM.ORDER_NUMBER AND MPAM.STATUS_ORDER_LINE_ITEM = SM.STATUS_ORDER_LINE_ITEM
            AND MPAM.STATUS_ORDER_LINE_ITEM NOT IN ('Cancel Pending', 'Cancelled', 'Replaced', 'Revision Rejected', 'Placement Failed') AND MPAM.PROMOTION_INTEGRATION_ID = SM.PROMOTION_INTEGRATION_ID
            AND CASE WHEN MPAM.STATUS_ORDER_LINE_ITEM = 'Complete' THEN CASE WHEN MPAM.STATUS_HEADER = 'In-transit' THEN MPAM.STATUS_ORDER_LINE_ITEM WHEN MPAM.STATUS_HEADER = 'Provisioning' THEN MPAM.STATUS_ORDER_LINE_ITEM ELSE MPAM.STATUS_HEADER END ELSE MPAM.STATUS_HEADER END = CASE WHEN SM.STATUS_ORDER_LINE_ITEM = 'Complete' THEN CASE WHEN SM.STATUS_HEADER = 'In-transit' THEN SM.STATUS_ORDER_LINE_ITEM WHEN SM.STATUS_HEADER = 'Provisioning' THEN SM.STATUS_ORDER_LINE_ITEM ELSE SM.STATUS_HEADER END ELSE SM.STATUS_HEADER END
        LEFT JOIN MP_OLI                       MO ON MO.ORDER_NUMBER = MPAM.ORDER_NUMBER AND MO.STATUS_HEADER = MPAM.STATUS_HEADER AND MO.ROOT_ITEM_ROW_ID = MPAM.ROW_ID
        LEFT JOIN MP_ASSOC_FHW_OLI           MAFO ON MAFO.ORDER_NUMBER = MO.ORDER_NUMBER AND MAFO.STATUS_HEADER = MO.STATUS_HEADER AND MAFO.ROOT_ITEM_ROW_ID = MO.ROOT_ITEM_ROW_ID
        LEFT JOIN MP_ASSOC_MAIN_CONT_ADD_OLI MCAO ON MCAO.ORDER_NUMBER = MO.ORDER_NUMBER AND MCAO.STATUS_HEADER = MO.STATUS_HEADER AND MCAO.ROOT_ITEM_ROW_ID = MO.ROOT_ITEM_ROW_ID
        LEFT JOIN MP_ASSOC_MAIN_CONT_DEL_OLI MCDO ON MCDO.ORDER_NUMBER = MO.ORDER_NUMBER AND MCDO.STATUS_HEADER = MO.STATUS_HEADER AND MCDO.ROOT_ITEM_ROW_ID = MO.ROOT_ITEM_ROW_ID
        LEFT JOIN ATTRIBUTES             A1 ON A1.ATTRIBUTE_OWNER_ROW_ID = MCAO.ROW_ID AND A1.ORDER_NUMBER = MCAO.ORDER_NUMBER AND A1.ATTRIBUTE_DISPLAY_NAME = 'Contract Term'
        LEFT JOIN ATTRIBUTES             A2 ON A2.ATTRIBUTE_OWNER_ROW_ID = MAFO.ROW_ID AND A2.ORDER_NUMBER = MAFO.ORDER_NUMBER AND A2.ATTRIBUTE_DISPLAY_NAME LIKE 'Supplied in Store%'
        LEFT JOIN ATTRIBUTES             A3 ON A3.ATTRIBUTE_OWNER_ROW_ID = MAFO.ROW_ID AND A3.ORDER_NUMBER = MAFO.ORDER_NUMBER AND A3.ATTRIBUTE_DISPLAY_NAME LIKE 'Hardware Supplied'
        LEFT JOIN ATTRIBUTES             A4 ON A4.ATTRIBUTE_OWNER_ROW_ID = MCDO.ROW_ID AND A4.ORDER_NUMBER = MCDO.ORDER_NUMBER AND A4.ATTRIBUTE_DISPLAY_NAME = 'Contract Term'
        LEFT JOIN LT_PLAN_VAS_HW_RO     LT1 ON LT1.IDX_NAME_0 = MAFO.PART_NUMBER AND LT1.IDX_NAME_1 = 'PLAN HW' AND LT1.STRINGVALUE = 'Yes' AND LT1.STARTDATE <= TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT1.ENDDATE > TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
        LEFT JOIN LT_PLAN_VAS_HW_RO     LT2 ON LT2.IDX_NAME_0 = MO.PART_NUMBER AND LT2.IDX_NAME_1 = 'PLAN' AND LT2.STRINGVALUE = 'Yes' AND LT2.STARTDATE <= TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT2.ENDDATE > TO_DATE(NVL(MAFO.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
    WHERE 1=1
      AND (MPAM.COMMISSION_PRODUCT_TYPE<>'Commissions Standalone' or MPAM.COMMISSION_PRODUCT_TYPE is null)
--      AND SM.ROW_ID = '1-OF2RZ45N'
)
SELECT
    P1.FILENAME,P1.BATCHPROCESSDATE,P1.RECORDNUMBER,P1.PROCESSED_DATE,P1.PROCESSED_PERIOD_ID,P1.TRANSACTION_AMOUNT,P1.QUANTITY,P1.ATTRIBUTE1,P1.ATTRIBUTE2,P1.ATTRIBUTE3,P1.ATTRIBUTE4,P1.ATTRIBUTE5,P1.ATTRIBUTE6,P1.ATTRIBUTE7,P1.ATTRIBUTE8,P1.ATTRIBUTE9,P1.ATTRIBUTE10,P1.ATTRIBUTE11,
    P1.ATTRIBUTE12,P1.ATTRIBUTE13,P1.ATTRIBUTE14,P1.ATTRIBUTE15,P1.ATTRIBUTE16,P1.ATTRIBUTE17,P1.ATTRIBUTE18,P1.ATTRIBUTE19,P1.ATTRIBUTE20,P1.ATTRIBUTE21,P1.ATTRIBUTE22,P1.ATTRIBUTE23,P1.ATTRIBUTE24,P1.ATTRIBUTE25,P1.ATTRIBUTE26,P1.ATTRIBUTE27,P1.ATTRIBUTE28,P1.ATTRIBUTE29,P1.ATTRIBUTE30,
    P1.ATTRIBUTE31,P1.ATTRIBUTE32,P1.ATTRIBUTE33,P1.ATTRIBUTE34,P1.ATTRIBUTE35,P1.ATTRIBUTE36,P1.ATTRIBUTE37,P1.ATTRIBUTE38,P1.ATTRIBUTE39,P1.ATTRIBUTE40,P1.ATTRIBUTE41,P1.ATTRIBUTE42,P1.ATTRIBUTE43,P1.ATTRIBUTE44,P1.ATTRIBUTE45,P1.ATTRIBUTE46,P1.ATTRIBUTE47,P1.ATTRIBUTE48,P1.ATTRIBUTE49,
    P1.ATTRIBUTE50,P1.ATTRIBUTE51,P1.ATTRIBUTE52,P1.ATTRIBUTE53,P1.ATTRIBUTE54,P1.ATTRIBUTE55,P1.ATTRIBUTE56,P1.ATTRIBUTE57,P1.ATTRIBUTE58,P1.ATTRIBUTE59,P1.ATTRIBUTE60,P1.ATTRIBUTE61,P1.ATTRIBUTE62,P1.ATTRIBUTE63,P1.ATTRIBUTE64,P1.ATTRIBUTE65,P1.ATTRIBUTE66,P1.ATTRIBUTE67,P1.ATTRIBUTE68,
    P1.ATTRIBUTE69,P1.ATTRIBUTE70,P1.ATTRIBUTE71,P1.ATTRIBUTE72,P1.ATTRIBUTE73,P1.ATTRIBUTE74,P1.ATTRIBUTE75,P1.ATTRIBUTE76,P1.ATTRIBUTE77,
    NVL(LT.STRINGVALUE, 'Non-Classified') ATTRIBUTE78,
    CASE WHEN (P1.ATTRIBUTE62 IS NULL OR P1.ATTRIBUTE72 IS NULL) 
           OR (TRUNC(TO_DATE(P1.ATTRIBUTE69,'dd/mm/yyyy hh24:mi:ss')) + ((P1.ATTRIBUTE72/12)*365) - TRUNC(TO_DATE(P1.ATTRIBUTE62,'dd/mm/yyyy hh24:mi:ss'))) <= LT1.VALUE
         THEN 'No'
         WHEN (TRUNC(TO_DATE(P1.ATTRIBUTE69,'dd/mm/yyyy hh24:mi:ss')) + ((P1.ATTRIBUTE72/12)*365) - TRUNC(TO_DATE(P1.ATTRIBUTE62,'dd/mm/yyyy hh24:mi:ss'))) > LT1.VALUE
         THEN 'Yes'
         END ATTRIBUTE79, /*Override determined in Pass3*/
    P1.ATTRIBUTE80,P1.ATTRIBUTE81,P1.ATTRIBUTE82,P1.ATTRIBUTE83,P1.ATTRIBUTE84,P1.ATTRIBUTE85,P1.ATTRIBUTE86,P1.ATTRIBUTE87,
    P1.ATTRIBUTE88,P1.ATTRIBUTE89,P1.ATTRIBUTE90,P1.ATTRIBUTE91,P1.ATTRIBUTE92,P1.ATTRIBUTE93,P1.ATTRIBUTE94,
    P1.ATTRIBUTE95,P1.ATTRIBUTE96,P1.ATTRIBUTE97,P1.ATTRIBUTE98,P1.ATTRIBUTE99,P1.ATTRIBUTE100,P1.LAST_UPDATE_DATE,P1.CREATION_DATE,P1.BOOKED_DATE,P1.REVENUE_TYPE,P1.TYPE,
    P1.EMPLOYEE_NUMBER,P1.RECORD_STATUS,P1.ERROR_TYPE,P1.ERROR_MSG,P1.SOURCE,P1.FILE_NAME,P1.RECORD_NUMBER,P1.SUBMITTED_DATE,P1.STATUS_HEADER,P1.STATUS_ORDER_LINE_ITEM,P1.ORIGINAL_ORDER_NUMBER
FROM PASS1 P1
    LEFT JOIN PRODUCT                   PRD ON PRD.NAME = P1.ATTRIBUTE39
    LEFT JOIN LT_ALLOWABLE_RECON_PERIOD LT1 ON LT1.IDX_NAME_0 = PRD.GENERICATTRIBUTE1 AND LT1.IDX_NAME_1 = P1.ATTRIBUTE65 AND LT1.IDX_NAME_1 = P1.ATTRIBUTE65 AND LT1.STARTDATE <= TO_DATE(NVL(P1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND LT1.ENDDATE > TO_DATE(NVL(P1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
    LEFT JOIN LT_SALES_TYPE_MAIN_PLAN    LT ON
        LT.IDX_NAME_0 = NVL(P1.ATTRIBUTE60,'NULL') AND LT.IDX_NAME_1 = NVL(P1.ATTRIBUTE45,'NULL') AND LT.IDX_NAME_2 = NVL(P1.ATTRIBUTE42,'NULL')
        AND LT.IDX_NAME_3 = NVL(P1.ATTRIBUTE41,'NULL') AND LT.IDX_NAME_4 = NVL(P1.ATTRIBUTE49,'NULL') AND LT.IDX_NAME_5 = NVL(P1.ATTRIBUTE61,'NULL')
        AND LT.IDX_NAME_6 = NVL(P1.MCDO_ACTION_CODE,'NULL') AND LT.IDX_NAME_7 = 'Commissions Main Plan'
        AND LT.IDX_NAME_8 = NVL(CASE WHEN P1.MPAM_PRODUCT = 'Mobile Service' AND P1.MPAM_REASON_CODE = 'Migration to Siebel' AND P1.MPAM_ORDER_TYPE = 'Add New Service' THEN P1.MPAM_REASON_CODE ELSE NULL END,'NULL')
        AND LT.STARTDATE <= TO_DATE(NVL(P1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'DD/MM/YYYY HH24:MI:SS') AND LT.ENDDATE > TO_DATE(NVL(P1.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'DD/MM/YYYY HH24:MI:SS')
;

    SELECT LT.STARTDATE, LT.ENDDATE, LT.DIM_NAME_0, LT.IDX_NAME_0, LT.DIM_NAME_1, LT.IDX_NAME_1, LT.DIM_NAME_2, LT.IDX_NAME_2, LT.DIM_NAME_3, LT.IDX_NAME_3, LT.DIM_NAME_4, LT.IDX_NAME_4, LT.DIM_NAME_5, LT.IDX_NAME_5, LT.DIM_NAME_6, LT.IDX_NAME_6, LT.DIM_NAME_7, LT.IDX_NAME_7, LT.DIM_NAME_8, LT.IDX_NAME_8, LT.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT LT
    WHERE NAME = 'LT_Sales_Type_Main_Plan'
    AND LT.IDX_NAME_0 = 'Modify' AND IDX_NAME_3 = 'Add' AND IDX_NAME_4 = 'Add'