SELECT
    PL.FILENAME AS "FILENAME"
  , PL.BATCHPROCESSDATE AS "BATCHPROCESSDATE"
  , PL.RECORDNUMBER AS "RECORDNUMBER"
  , PL.QUERY_SRC AS "QUERY_SRC"
  , NVL(PL.ERROR_TYPE, '') as "ERROR_TYPE"
FROM TELS_STAGE_RCRM_PPE PL
WHERE (1=1)
    AND PL.FILENAME = 'CCB-RCRM_OrderDataExtract_20190301_033020.dat' -- TOAD
    --AND PL.FILENAME = '$$filename' -- INFORMATICA
    AND EXISTS (
      WITH LINE_ITEM AS (
        SELECT
            V.FILENAME
          , V.ATTRIBUTE46
          , CASE WHEN V.SOURCE <> 'CCB-RCRM' AND 'UAT' <> 'UAT' THEN 'Complete' ELSE V.STATUS_ORDER_LINE_ITEM END AS "STATUS_ORDER_LINE_ITEM"
    --      , CASE WHEN V.SOURCE <> 'CCB-RCRM' AND '$$custinst' <> 'UAT' THEN 'Complete' ELSE V.STATUS_ORDER_LINE_ITEM END AS "STATUS_ORDER_LINE_ITEM"
          , V.ERROR_TYPE AS "ERROR_TYPE"
          , V.SOURCE AS "SOURCE"
          , NVL2(V.PROCESSED_DATE, TRUNC(TO_DATE(V.PROCESSED_DATE, 'YYYY-MM-DD')), TRUNC(TO_DATE('2200-01-01', 'YYYY-MM-DD'))) AS "PROCESSED_DATE"
          , NVL2(C.DATE_VALUE, TRUNC(C.DATE_VALUE), TRUNC(SYSDATE)) AS "CUTOVER_DATE"
        FROM TELS_STAGE_RCRM_PPE V
        JOIN TELS_CONFIG C
        ON C.ATTRIBUTE_NAME = 'RCRM PPE CUTOVER DATE' 
      )
      , SOURCE_LINE_ITEM AS (
        SELECT
            V.FILENAME
          , V.ATTRIBUTE46
          , V.STATUS_ORDER_LINE_ITEM
        FROM LINE_ITEM V
        WHERE (1=1)
        AND (
          V.SOURCE = 'CCB-RCRM'
          OR (V.SOURCE = 'SIEBEL' AND V.PROCESSED_DATE < V.CUTOVER_DATE)
        )
        AND (V.ERROR_TYPE IS NULL OR SUBSTR(V.ERROR_TYPE, 1, 17) <> '[NOT PROVISIONED]')
      )
      SELECT 1
      FROM SOURCE_LINE_ITEM SL
      WHERE (1=1)
      AND SL.FILENAME <> PL.FILENAME
      AND SL.ATTRIBUTE46 = PL.ATTRIBUTE46
      AND SL.STATUS_ORDER_LINE_ITEM = PL.STATUS_ORDER_LINE_ITEM
    )
;

WITH LINE_ITEM AS (
    SELECT
        V.FILENAME
      , V.ATTRIBUTE46
      , CASE WHEN V.SOURCE <> 'CCB-RCRM' AND 'UAT' <> 'UAT' THEN 'Complete' ELSE V.STATUS_ORDER_LINE_ITEM END AS "STATUS_ORDER_LINE_ITEM"
--      , CASE WHEN V.SOURCE <> 'CCB-RCRM' AND '$$custinst' <> 'UAT' THEN 'Complete' ELSE V.STATUS_ORDER_LINE_ITEM END AS "STATUS_ORDER_LINE_ITEM"
      , V.ERROR_TYPE AS "ERROR_TYPE"
      , V.SOURCE AS "SOURCE"
      , NVL2(V.PROCESSED_DATE, TRUNC(TO_DATE(V.PROCESSED_DATE, 'YYYY-MM-DD')), TRUNC(TO_DATE('2200-01-01', 'YYYY-MM-DD'))) AS "PROCESSED_DATE"
      , NVL2(C.DATE_VALUE, TRUNC(C.DATE_VALUE), TRUNC(SYSDATE)) AS "CUTOVER_DATE"
    FROM TELS_STAGE_RCRM_PPE V
    JOIN TELS_CONFIG C
      ON C.ATTRIBUTE_NAME = 'RCRM PPE CUTOVER DATE'
      )
, SOURCE_LINE_ITEM AS (
    SELECT
        V.FILENAME
      , V.ATTRIBUTE46
      , V.STATUS_ORDER_LINE_ITEM
    FROM LINE_ITEM V
    WHERE 1=1 and (V.SOURCE = 'CCB-RCRM' OR (V.SOURCE = 'SIEBEL' AND V.PROCESSED_DATE < V.CUTOVER_DATE))
      AND (V.ERROR_TYPE IS NULL OR SUBSTR(V.ERROR_TYPE, 1, 17) <> '[NOT PROVISIONED]'))
SELECT
    PL.FILENAME AS "FILENAME"
  , PL.BATCHPROCESSDATE AS "BATCHPROCESSDATE"
  , PL.RECORDNUMBER AS "RECORDNUMBER"
  , PL.QUERY_SRC AS "QUERY_SRC"
  , NVL(PL.ERROR_TYPE, '') as "ERROR_TYPE"
FROM TELS_STAGE_RCRM_PPE PL
WHERE (1=1)
    AND PL.FILENAME = 'CCB-RCRM_OrderDataExtract_20190301_033020.dat' -- TOAD
    --AND PL.FILENAME = '$$filename' -- INFORMATICA
    AND EXISTS (SELECT 1
                FROM SOURCE_LINE_ITEM SL
                WHERE SL.FILENAME <> PL.FILENAME
                    AND SL.ATTRIBUTE46 = PL.ATTRIBUTE46
                    AND SL.STATUS_ORDER_LINE_ITEM = PL.STATUS_ORDER_LINE_ITEM
                    )
;

drop index TELS_STAGE_RCRM_PPE_IX1;
CREATE INDEX TELS_STAGE_RCRM_PPE_IX1 ON TELS_STAGE_RCRM_PPE
(FILENAME,ATTRIBUTE46,STATUS_ORDER_LINE_ITEM)
TABLESPACE TELS_TRANSFORMS;