--INSERT INTO TELS_RCRM_HOLD_RECORDS 
WITH 
  SERVICE_MOLI                  AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'SERVICE_MOLI')
, MP_ASSOC_SERVICE_MOLI         AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_SERVICE_MOLI')
, SERVICE_ASSOC_ACCESS_TYPE_OLI AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'SERVICE_ASSOC_ACCESS_TYPE_OLI')
, MP_ASSOC_MOLI                 AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_MOLI')
, MP_OLI                        AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_OLI')
, MP_ASSOC_CONTRACT_ADD_OLI     AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_CONTRACT_ADD_OLI')
, MP_ASSOC_CONTRACT_DEL_OLI     AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_CONTRACT_DEL_OLI')
, MP_ASSOC_MAIN_CONT_ADD_OLI    AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_MAIN_CONT_ADD_OLI')
, MP_ASSOC_MAIN_CONT_DEL_OLI    AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_MAIN_CONT_DEL_OLI')
, MP_ASSOC_FHW_OLI              AS(SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_FHW_OLI')
, HOLD_SERVICE_MOLI AS(
    SELECT sm.*
    FROM SERVICE_MOLI sm
    WHERE NOT EXISTS(SELECT 1 
                     FROM MP_ASSOC_SERVICE_MOLI masm 
                     WHERE masm.ROW_ID = sm.ROW_ID))
, HOLD_SERVICE_MOLI_RELATED AS(
    SELECT o.*
    FROM HOLD_SERVICE_MOLI m
    JOIN SERVICE_ASSOC_ACCESS_TYPE_OLI o ON
      m.ROW_ID = o.ROOT_ITEM_ROW_ID
      AND m.ORDER_NUMBER = o.ORDER_NUMBER
      AND m.STATUS_HEADER = o.STATUS_HEADER)
, HOLD_MP_ASSOC_MOLI AS(
    SELECT * 
    FROM MP_ASSOC_MOLI mpam
    WHERE NOT EXISTS(SELECT 1
                     FROM MP_ASSOC_SERVICE_MOLI masm
                     WHERE masm.PROMOTION_INTEGRATION_ID = mpam.PROMOTION_INTEGRATION_ID
                       AND masm.ORDER_NUMBER = mpam.ORDER_NUMBER
                       AND masm.STATUS_HEADER = mpam.STATUS_HEADER))
, HOLD_MP_ASSOC_MOLI_RELATED AS(
    SELECT o.*
    FROM HOLD_MP_ASSOC_MOLI m
    JOIN (SELECT * FROM MP_OLI
          UNION ALL SELECT * FROM MP_ASSOC_CONTRACT_ADD_OLI
          UNION ALL SELECT * FROM MP_ASSOC_CONTRACT_DEL_OLI
          UNION ALL SELECT * FROM MP_ASSOC_MAIN_CONT_ADD_OLI
          UNION ALL SELECT * FROM MP_ASSOC_MAIN_CONT_DEL_OLI
          UNION ALL SELECT * FROM MP_ASSOC_FHW_OLI) o ON
      m.ROW_ID = o.ROOT_ITEM_ROW_ID
      AND m.ORDER_NUMBER = o.ORDER_NUMBER
      AND m.STATUS_HEADER = o.STATUS_HEADER)

SELECT * FROM HOLD_SERVICE_MOLI
UNION ALL
SELECT * FROM HOLD_SERVICE_MOLI_RELATED
UNION ALL 
SELECT * FROM HOLD_MP_ASSOC_MOLI
UNION ALL 
SELECT * FROM HOLD_MP_ASSOC_MOLI_RELATED;


