SELECT count(*) FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'SERVICE_MOLI'; --26073
SELECT count(*) FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_SERVICE_MOLI'; --13503

WITH SERVICE_MOLI AS(
    SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'SERVICE_MOLI')
, MP_ASSOC_SERVICE_MOLI AS(
    SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'MP_ASSOC_SERVICE_MOLI')
, HOLD_SERVICE_MOLI AS(
    SELECT sm.ROW_ID
    FROM SERVICE_MOLI sm
    WHERE NOT EXISTS(SELECT 1 
                 FROM MP_ASSOC_SERVICE_MOLI masm 
                 WHERE masm.ROW_ID = sm.ROW_ID))
SELECT * FROM HOLD_SERVICE_MOLI;