--PPE Matrix
WITH ATTRIBUTES AS(
    SELECT d.FILENAME, d.RECORDNUMBER, d.ORDER_NUMBER, d.ROW_ID ATTRIBUTE_OWNER_ROW_ID, d.ATTRIBUTE_ROW_ID, d.ATTRIBUTE_ACTION_CODE, d.ATTRIBUTE_DISPLAY_NAME, d.ATTRIBUTE_VALUE
    FROM TELS_STAGE_RCRM d
    WHERE d.ATTRIBUTE_ROW_ID IS NOT NULL)
, DARO AS(
    SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'DARO_MOLI'
    UNION
    SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'DARO_OLI')
, DARO_ASSOC_SERVICE_MOLI AS(
	SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'DARO_ASSOC_SERVICE_MOLI')
, LT_DARO_Offset AS(
    SELECT lt.STARTDATE, lt.ENDDATE, lt.DIM_NAME_0, lt.IDX_NAME_0, lt.DIM_NAME_1, lt.IDX_NAME_1, lt.VALUE
    FROM TELS_RCRM_MV_MDLT lt
    WHERE NAME = 'LT_DARO_Offset')
, LT_DARO_Bundle_Rebate AS(
    SELECT lt.STARTDATE, lt.ENDDATE, lt.DIM_NAME_0, lt.IDX_NAME_0, lt.VALUE
    FROM TELS_RCRM_MV_MDLT lt
    WHERE NAME = 'LT_DARO_Bundle_Rebate')
SELECT 
    d.FILENAME,
    d.BATCHPROCESSDATE,
    d.RECORDNUMBER,
    d.PROVISIONED_DATE PROCESSED_DATE,
    NULL PROCESSED_PERIOD_ID,
    d.LIST_PRICE TRANSACTION_AMOUNT,
    a1.ATTRIBUTE_VALUE QUANTITY,
    d.CUSTOMER_LAST_NAME ATTRIBUTE1,
    d.CUSTOMER_FIRST_NAME ATTRIBUTE2,
    NULL ATTRIBUTE3,NULL ATTRIBUTE4,NULL ATTRIBUTE5,NULL ATTRIBUTE6,NULL ATTRIBUTE7,NULL ATTRIBUTE8,NULL ATTRIBUTE9,NULL ATTRIBUTE10,NULL ATTRIBUTE11,NULL ATTRIBUTE12,NULL ATTRIBUTE13,NULL ATTRIBUTE14,NULL ATTRIBUTE15,NULL ATTRIBUTE16,NULL ATTRIBUTE17,NULL ATTRIBUTE18,NULL ATTRIBUTE19,NULL ATTRIBUTE20,NULL ATTRIBUTE21,NULL ATTRIBUTE22,NULL ATTRIBUTE23,NULL ATTRIBUTE24,
    d.ORDER_NUMBER ATTRIBUTE25,
    d.BILLING_ACCOUNT ATTRIBUTE26,
    d.PARTNER_CODE ATTRIBUTE27,
    NULL ATTRIBUTE28,NULL ATTRIBUTE29,NULL ATTRIBUTE30,NULL ATTRIBUTE31,NULL ATTRIBUTE32,NULL ATTRIBUTE33,NULL ATTRIBUTE34,
    d.BUSINESS_UNIT ATTRIBUTE35,
    d.SALES_FORCE_ID ATTRIBUTE36,
    'COMMISSIONABLE TRANSACTION' ATTRIBUTE37,
    d.SOURCE_SYSTEM ATTRIBUTE38,
    d.PRODUCT ATTRIBUTE39,
    NULL ATTRIBUTE40,
    d.ACTION_CODE ATTRIBUTE41,
    d.TRANSFER_TYPE ATTRIBUTE42,
	CASE WHEN dasm.EVENT_SOURCE IS NOT NULL 
         THEN dasm.EVENT_SOURCE
		 ELSE d.EVENT_SOURCE 
         END ATTRIBUTE43,
	CASE WHEN dasm.PROMOTION_PART_NUMBER IS NOT NULL 
         THEN dasm.PROMOTION_PART_NUMBER
		 ELSE d.PROMOTION_PART_NUMBER 
         END ATTRIBUTE44,
    d.ORDER_SUB_TYPE ATTRIBUTE45,
    d.ROW_ID ATTRIBUTE46,
    a2.ATTRIBUTE_VALUE ATTRIBUTE47,
    NULL ATTRIBUTE48,
    d.ACTION_CODE ATTRIBUTE49,
    d.PROD_PROM_ID ATTRIBUTE50,
    NULL ATTRIBUTE51,NULL ATTRIBUTE52,NULL ATTRIBUTE53,
    CASE WHEN lt.VALUE IS NOT NULL
         THEN 'DAROZ'
         WHEN EXISTS(SELECT 1 FROM LT_DARO_Bundle_Rebate lt WHERE lt.IDX_NAME_0 = NVL(d.PART_NUMBER,'NULL') AND lt.STARTDATE <= TO_DATE(NVL(d.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(d.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss'))
         THEN 'Subsidised'
         END ATTRIBUTE54,
    NULL ATTRIBUTE55,NULL ATTRIBUTE56,NULL ATTRIBUTE57,NULL ATTRIBUTE58,
    a3.ATTRIBUTE_VALUE ATTRIBUTE59,
    d.ORDER_TYPE ATTRIBUTE60,
    NULL ATTRIBUTE61,NULL ATTRIBUTE62,NULL ATTRIBUTE63,NULL ATTRIBUTE64,
    a4.ATTRIBUTE_VALUE ATTRIBUTE65,
    NULL ATTRIBUTE66,
    CASE WHEN a5.ATTRIBUTE_VALUE IS NOT NULL 
         THEN a5.ATTRIBUTE_VALUE
         ELSE d.HARDWARE_SUPPLIED_FLAG
         END ATTRIBUTE67,
    NULL ATTRIBUTE68,NULL ATTRIBUTE69,NULL ATTRIBUTE70,NULL ATTRIBUTE71,NULL ATTRIBUTE72,NULL ATTRIBUTE73,NULL ATTRIBUTE74,NULL ATTRIBUTE75,NULL ATTRIBUTE76,NULL ATTRIBUTE77,NULL ATTRIBUTE78,NULL ATTRIBUTE79,NULL ATTRIBUTE80,
    a6.ATTRIBUTE_VALUE ATTRIBUTE81,
    CASE WHEN TO_CHAR(lt.VALUE) IS NOT NULL
         THEN TO_CHAR(lt.VALUE)
         ELSE a7.ATTRIBUTE_VALUE 
         END ATTRIBUTE82, 
    NULL ATTRIBUTE83,NULL ATTRIBUTE84,NULL ATTRIBUTE85,NULL ATTRIBUTE86,NULL ATTRIBUTE87,
    d.COMMISSION_PRODUCT_TYPE ATTRIBUTE88,
    NULL ATTRIBUTE89,NULL ATTRIBUTE90,NULL ATTRIBUTE91,NULL ATTRIBUTE92,NULL ATTRIBUTE93,NULL ATTRIBUTE94,NULL ATTRIBUTE95,NULL ATTRIBUTE96,NULL ATTRIBUTE97,NULL ATTRIBUTE98,NULL ATTRIBUTE99,NULL ATTRIBUTE100,
    NULL LAST_UPDATE_DATE,NULL CREATION_DATE,
    d.CREATED_DATE BOOKED_DATE,
    'REVENUE' REVENUE_TYPE,
    NULL TYPE,NULL EMPLOYEE_NUMBER,NULL RECORD_STATUS,NULL ERROR_TYPE,NULL ERROR_MSG,
    d.SOURCE_SYSTEM SOURCE,
    d.FILENAME, d.RECORDNUMBER,
    d.SUBMITTED_DATE SUBMITTED_DATE,
    d.STATUS_HEADER STATUS_HEADER,
    d.STATUS_ORDER_LINE_ITEM STATUS_ORDER_LINE_ITEM,
    d.ORIGINAL_ORDER_NUMBER
FROM 
  DARO d
  LEFT OUTER JOIN DARO_ASSOC_SERVICE_MOLI dasm ON dasm.ORDER_NUMBER = d.ORDER_NUMBER AND dasm.STATUS_HEADER = d.STATUS_HEADER AND dasm.ROW_ID = d.ROOT_ITEM_ROW_ID-- AND dasm.FILENAME = d.FILENAME
  LEFT OUTER JOIN ATTRIBUTES     a1 ON a1.ATTRIBUTE_OWNER_ROW_ID = d.ROW_ID AND a1.ORDER_NUMBER = d.ORDER_NUMBER AND a1.ATTRIBUTE_DISPLAY_NAME = 'Quantity'-- AND a1.FILENAME = d.FILENAME
  LEFT OUTER JOIN ATTRIBUTES     a2 ON a2.ATTRIBUTE_OWNER_ROW_ID = d.ROW_ID AND a2.ORDER_NUMBER = d.ORDER_NUMBER AND a2.ATTRIBUTE_DISPLAY_NAME IN('Product Name','Associated Product')-- AND a2.FILENAME = d.FILENAME
  LEFT OUTER JOIN ATTRIBUTES     a3 ON a3.ATTRIBUTE_OWNER_ROW_ID = d.ROW_ID AND a3.ORDER_NUMBER = d.ORDER_NUMBER AND a3.ATTRIBUTE_DISPLAY_NAME = 'Serial Number'-- AND a3.FILENAME = d.FILENAME
  LEFT OUTER JOIN ATTRIBUTES     a4 ON a4.ATTRIBUTE_OWNER_ROW_ID = d.ROW_ID AND a4.ORDER_NUMBER = d.ORDER_NUMBER AND a4.ATTRIBUTE_DISPLAY_NAME = 'Contract Term'-- AND a4.FILENAME = d.FILENAME
  LEFT OUTER JOIN ATTRIBUTES     a5 ON a5.ATTRIBUTE_OWNER_ROW_ID = d.ROW_ID AND a5.ORDER_NUMBER = d.ORDER_NUMBER AND a5.ATTRIBUTE_DISPLAY_NAME = 'Hardware Supplied'-- AND a5.FILENAME = d.FILENAME
  LEFT OUTER JOIN ATTRIBUTES     a6 ON a6.ATTRIBUTE_OWNER_ROW_ID = d.ROW_ID AND a6.ORDER_NUMBER = d.ORDER_NUMBER AND a6.ATTRIBUTE_DISPLAY_NAME IN('Product Id','Associated Product Part Number')-- AND a6.FILENAME = d.FILENAME
  LEFT OUTER JOIN ATTRIBUTES     a7 ON a7.ATTRIBUTE_OWNER_ROW_ID = d.ROW_ID AND a7.ORDER_NUMBER = d.ORDER_NUMBER AND a7.ATTRIBUTE_DISPLAY_NAME = 'Repayment Amount'-- AND a7.FILENAME = d.FILENAME
  LEFT OUTER JOIN LT_DARO_Offset lt ON lt.IDX_NAME_0 = NVL(d.PART_NUMBER,'NULL') AND lt.IDX_NAME_1 = NVL(a7.ATTRIBUTE_VALUE,'NULL') AND lt.STARTDATE <= TO_DATE(NVL(d.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(d.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
WHERE NVL(d.ORDER_SUB_TYPE,'NULL') <> 'Transfer'
--  AND d.FILENAME = '$$filename'
;

/* DARO Investigation*/
SELECT res.O_ATTRIBUTE25, res.O_ATTRIBUTE46, res.* FROM TEST_PREPROC_COMPARISON_DARO2 res WHERE C_FILENAME IS NULL;
SELECT * FROM TEST_PREPROC_COMPARISON_DARO2 WHERE C_ATTRIBUTE25 = '1-1773476970086' OR O_ATTRIBUTE25 = '1-1773476970086';
SELECT * FROM TELS_STAGE_RCRM_PPE WHERE QUERY_SRC = 'DARO' AND ATTRIBUTE25 = '1-1770180275711';
SELECT * FROM TELS_PRESTAGE_RCRM WHERE ORDER_NUMBER = '1-1770180275711' AND ROW_ID = '1-ML88LZX7';
SELECT * FROM TELS_STAGE_RCRM WHERE ROW_ID = '1-MR8Q5BLP';
SELECT * FROM TELS_SUBMITTED_ORDERS_VIEW WHERE REC_TYPE = 'DARO_MOLI' AND ORDER_NUMBER = '1-1770180275711';
