SELECT
    d.FILENAME
  , d.BATCHPROCESSDATE
  , d.RECORDNUMBER
  , d.IS_FILTERED
  , d.ORDER_NUMBER
  , d.BILLING_ACCOUNT
  , d.CUSTOMER_LAST_NAME
  , d.CUSTOMER_FIRST_NAME
  , d.ORDER_TYPE
  , d.ORDER_SUB_TYPE
  , d.CREATED_DATE
  , d.PARTNER_CODE
  , d.CAMPAIGN_NAME
  , d.CAMPAIGN_NUMBER
  , d.CAMPAIGN_TYPE
  , d.CHANNEL_TYPE
  , d.CAMPAIGN_START_DATE
  , d.BUSINESS_UNIT
  , d.SALES_FORCE_ID
  , d.CUSTOMER_ID
  , d.ORDER_REVISION_NUMBER
  , d.SUBMITTED_DATE
  , d.STATUS_HEADER
  , d.REASON_CODE
  , d.COMMISSION_TRANSACTION_TYPE
  , d.SOURCE_SYSTEM
  , d.ROW_ID
  , d.PRODUCT
  , d.PART_NUMBER
  , d.ACTION_CODE
  , d.TRANSFER_TYPE
  , d.EVENT_SOURCE
  , d.PROD_PROM_ID
  , d.PROVISIONED_DATE
  , d.NET_PRICE
  , d.COMMISSION_PRODUCT_TYPE
  , d.COMMISSIONABLE
  , d.STATUS_ORDER_LINE_ITEM
  , d.ORIGINAL_ORDER_NUMBER
  , d.HARDWARE_SUPPLIED_FLAG
  , d.SUB_ACTION_CODE
  , d.PROMOTION_INTEGRATION_ID
  , d.NGB_PROD_TYPE
  , d.PROMOTION_PART_NUMBER
  , d.PRODUCT_ID
  , d.O2A_STATUS
  , d.PARENT_ITEM_ROW_ID
  , d.ROOT_ITEM_ROW_ID
  , d.CONTRACT_START_DATE
  , d.CONTRACT_END_DATE
  , d.LIST_PRICE
  , d.HARDWARE_ASSOCIATION_ID
  , d.ATTRIBUTE_ROW_ID
  , d.ATTRIBUTE_ACTION_CODE
  , d.ATTRIBUTE_DISPLAY_NAME
  , d.ATTRIBUTE_VALUE 
FROM TELS_PRESTAGE_RCRM d
WHERE 
  d.NGB_PROD_TYPE IN('MOC','Shared')
  AND d.COMMISSION_PRODUCT_TYPE <> 'Commissions Fixed Hardware'
  AND NOT EXISTS (
      SELECT 1 FROM TELS_PRESTAGE_RCRM ps
      WHERE ps.ORDER_NUMBER = d.ORDER_NUMBER
        AND ps.PROMOTION_INTEGRATION_ID = d.PROMOTION_INTEGRATION_ID
        AND ps.NGB_PROD_TYPE = 'MOC'
        AND ps.COMMISSION_PRODUCT_TYPE = 'Commissions Main Plan'
        AND ps.STATUS_HEADER = d.STATUS_HEADER)
  AND EXISTS (
      SELECT 1 FROM TELS_PRESTAGE_RCRM ps
      WHERE ps.ORDER_NUMBER = d.ORDER_NUMBER
        AND ps.PROMOTION_INTEGRATION_ID = d.PROMOTION_INTEGRATION_ID
        AND ps.NGB_PROD_TYPE = 'MOC')
  AND NOT EXISTS (
      SELECT 1 FROM TELS_PRESTAGE_RCRM ps
      WHERE ps.ORDER_NUMBER = d.ORDER_NUMBER
        AND ps.PROMOTION_INTEGRATION_ID = d.PROMOTION_INTEGRATION_ID
        AND ps.NGB_PROD_TYPE = 'MOC'
        AND ps.COMMISSION_PRODUCT_TYPE <> 'Commissions Standalone')
  AND NOT EXISTS (
      SELECT 1 FROM TELS_PRESTAGE_RCRM ps
      WHERE ps.ORDER_NUMBER = d.ORDER_NUMBER
        AND ps.PROMOTION_INTEGRATION_ID = d.PROMOTION_INTEGRATION_ID
        AND ps.NGB_PROD_TYPE = 'MOC'
        AND ps.SUB_ACTION_CODE IN('Move-Add','Transition-Add'))
  AND NOT EXISTS (
      SELECT 1 FROM TELS_CORE_PRESTAGEERROR pe
      WHERE pe.FILENAME = d.FILENAME
        AND pe.RECORDNUMBER = d.RECORDNUMBER
        AND pe.ISWARNINGONLY = 0)