ALTER TABLE TELS_RCRM_PRESTAGE_ATTRIBUTE DROP PRIMARY KEY CASCADE;

DROP TABLE TELS_RCRM_PRESTAGE_ATTRIBUTE CASCADE CONSTRAINTS;

CREATE TABLE TELS_RCRM_PRESTAGE_ATTRIBUTE
(
    FILENAME VARCHAR2(255) NOT NULL
  , BATCHPROCESSDATE DATE NOT NULL
  , RECORDNUMBER NUMBER(15) NOT NULL
  , IS_FILTERED NUMBER(1) NOT NULL
  , ATTRIBUTE_OWNER_ROW_ID VARCHAR2(15)
  , ATTRIBUTE_ROW_ID VARCHAR2(15)
  , ATTRIBUTE_ACTION_CODE VARCHAR2(30)
  , ATTRIBUTE_DISPLAY_NAME VARCHAR2(100)
  , ATTRIBUTE_VALUE VARCHAR2(255)
)
TABLESPACE TELS_TRANSFORMS;

CREATE UNIQUE INDEX TELS_RCRM_PRESTAGE_ATTRIB_PK ON TELS_RCRM_PRESTAGE_ATTRIBUTE
(FILENAME,BATCHPROCESSDATE,RECORDNUMBER)
TABLESPACE TELS_TRANSFORMS;

ALTER TABLE TELS_RCRM_PRESTAGE_ATTRIBUTE ADD (
  CONSTRAINT TELS_RCRM_PRESTAGE_ATTRIB_PK
  PRIMARY KEY
  (FILENAME,BATCHPROCESSDATE,RECORDNUMBER)
  USING INDEX TELS_RCRM_PRESTAGE_ATTRIB_PK);
