ALTER TABLE TELS_STATUS DROP PRIMARY KEY CASCADE;

DROP TABLE TELS_STATUS CASCADE CONSTRAINTS;

CREATE TABLE TELS_STATUS
(
    STATUS_SEQ  INTEGER NOT NULL
  , STATUS_NAME VARCHAR2(255 BYTE)
)
TABLESPACE TELS_TRANSFORMS;

CREATE UNIQUE INDEX TELS_STATUS_PK ON TELS_STATUS
(STATUS_SEQ)
TABLESPACE TELS_TRANSFORMS;

ALTER TABLE TELS_STATUS ADD (
  CONSTRAINT TELS_STATUS_PK
  PRIMARY KEY
  (STATUS_SEQ)
  USING INDEX TELS_STATUS_PK);

CREATE INDEX TELS_STATUS_NAME ON TELS_STATUS
(STATUS_NAME)
TABLESPACE TELS_TRANSFORMS;

INSERT INTO TELS_STATUS (STATUS_SEQ, STATUS_NAME) VALUES (0, 'Unknown');
INSERT INTO TELS_STATUS (STATUS_SEQ, STATUS_NAME) VALUES (1, 'Cancelled');
INSERT INTO TELS_STATUS (STATUS_SEQ, STATUS_NAME) VALUES (2, 'Complete');
INSERT INTO TELS_STATUS (STATUS_SEQ, STATUS_NAME) VALUES (3, 'Error - Integration');
INSERT INTO TELS_STATUS (STATUS_SEQ, STATUS_NAME) VALUES (4, 'Error - Provisioning');
INSERT INTO TELS_STATUS (STATUS_SEQ, STATUS_NAME) VALUES (5, 'In-transit');
INSERT INTO TELS_STATUS (STATUS_SEQ, STATUS_NAME) VALUES (6, 'Provisioning');

COMMIT;
