CREATE OR REPLACE PACKAGE TELS_STAGE_RCRM_PKG AS
  PROCEDURE TELS_STAGE_RCRM_PRE_LOAD;
  PROCEDURE TELS_STAGE_RCRM_POST_LOAD;
END TELS_STAGE_RCRM_PKG;
/

CREATE OR REPLACE PACKAGE BODY TELS_STAGE_RCRM_PKG AS

  PROCEDURE TELS_STAGE_RCRM_PRE_LOAD
  AS
  BEGIN

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_STAGE_RCRM_IX_ATT';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_STAGE_RCRM_IX_ROW';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'TRUNCATE TABLE TELS_STAGE_RCRM PURGE MATERIALIZED VIEW LOG REUSE STORAGE';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    COMMIT;

  END TELS_STAGE_RCRM_PRE_LOAD;

  PROCEDURE TELS_STAGE_RCRM_POST_LOAD
  AS
  BEGIN

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_STAGE_RCRM_IX_ATT ON TELS_STAGE_RCRM'
        || ' (ATTRIBUTE_ROW_ID)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_STAGE_RCRM_IX_ROW ON TELS_STAGE_RCRM'
        || ' (ROW_ID,ORDER_SUB_TYPE,COMMISSION_PRODUCT_TYPE,ACTION_CODE)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      SYS.DBMS_STATS.GATHER_TABLE_STATS(
          OWNNAME           => 'TELSADMIN'
        , TABNAME           => 'TELS_STAGE_RCRM'
        , ESTIMATE_PERCENT  => NULL
        , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
        , DEGREE            => NULL
        , CASCADE           => TRUE
        , NO_INVALIDATE     => FALSE);
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

--  TELS_RCRM_MV_MOLI_ROOT

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_1';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_2';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_3';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_4';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_MOLI_ROOT', METHOD => 'C' );
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_1 ON TELS_RCRM_MV_MOLI_ROOT'
        || ' (COMMISSION_PRODUCT_TYPE,ACTION_CODE)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_2 ON TELS_RCRM_MV_MOLI_ROOT'
        || ' (ROOT_ITEM_ROW_ID,ORDER_NUMBER,STATUS_HEADER,FILENAME)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_3 ON TELS_RCRM_MV_MOLI_ROOT'
        || ' (ROW_ID,ORDER_NUMBER,STATUS_HEADER,FILENAME)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_4 ON TELS_RCRM_MV_MOLI_ROOT'
        || ' (PROMOTION_INTEGRATION_ID,ORDER_NUMBER,STATUS_HEADER,FILENAME)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      SYS.DBMS_STATS.GATHER_TABLE_STATS(
          OWNNAME           => 'TELSADMIN'
        , TABNAME           => 'TELS_RCRM_MV_MOLI_ROOT'
        , ESTIMATE_PERCENT  => NULL
        , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
        , DEGREE            => NULL
        , CASCADE           => TRUE
        , NO_INVALIDATE     => FALSE);
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;
    
--  TELS_RCRM_MV_OLI_ROOT

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_OLI_ROOT_IX_1';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_OLI_ROOT_IX_2';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_OLI_ROOT', METHOD => 'C' );
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_OLI_ROOT_IX_1 ON TELS_RCRM_MV_OLI_ROOT'
        || ' (COMMISSION_PRODUCT_TYPE,ACTION_CODE)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_OLI_ROOT_IX_2 ON TELS_RCRM_MV_OLI_ROOT'
        || ' (ROOT_ITEM_ROW_ID,ORDER_NUMBER,STATUS_HEADER,FILENAME)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      SYS.DBMS_STATS.GATHER_TABLE_STATS(
          OWNNAME           => 'TELSADMIN'
        , TABNAME           => 'TELS_RCRM_MV_OLI_ROOT'
        , ESTIMATE_PERCENT  => NULL
        , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
        , DEGREE            => NULL
        , CASCADE           => TRUE
        , NO_INVALIDATE     => FALSE);
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

--  TELS_RCRM_MV_ATTRIBUTE

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_1';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_2';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_3';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_ATTRIBUTE_IX_4';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_ATTRIBUTE', METHOD => 'C' );
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_1 ON TELS_RCRM_MV_ATTRIBUTE'
        || ' (FILENAME,ROW_ID,ATTRIBUTE_ROW_ID,ATTRIBUTE_DISPLAY_NAME,ATTRIBUTE_ACTION_CODE)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_2 ON TELS_RCRM_MV_ATTRIBUTE'
        || ' (FILENAME,ROW_ID,ATTRIBUTE_DISPLAY_NAME,ATTRIBUTE_ACTION_CODE)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_3 ON TELS_RCRM_MV_ATTRIBUTE'
        || ' (ROW_ID,ATTRIBUTE_DISPLAY_NAME,FILENAME)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_ATTRIBUTE_IX_4 ON TELS_RCRM_MV_ATTRIBUTE'
        || ' (ROW_ID,FILENAME,ATTRIBUTE_ACTION_CODE)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      SYS.DBMS_STATS.GATHER_TABLE_STATS(
          OWNNAME           => 'TELSADMIN'
        , TABNAME           => 'TELS_RCRM_MV_ATTRIBUTE'
        , ESTIMATE_PERCENT  => NULL
        , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
        , DEGREE            => NULL
        , CASCADE           => TRUE
        , NO_INVALIDATE     => FALSE);
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

--  TELS_RCRM_MV_LINE_ITEM

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_LINE_ITEM_IX_1';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_LINE_ITEM_IX_2';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_LINE_ITEM_IX_ROOT';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_LINE_ITEM_IX_ROW';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_LINE_ITEM_IX_TYPE';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_LINE_ITEM', METHOD => 'C' );
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_1 ON TELS_RCRM_MV_LINE_ITEM'
        || ' (FILENAME,ORDER_NUMBER,ROW_ID)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_2 ON TELS_RCRM_MV_LINE_ITEM'
        || ' (ROW_ID,FILENAME)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_ROOT ON TELS_RCRM_MV_LINE_ITEM'
        || ' (REC_TYPE,FILENAME,ORDER_NUMBER,STATUS_HEADER,ROOT_ITEM_ROW_ID)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_ROW ON TELS_RCRM_MV_LINE_ITEM'
        || ' (REC_TYPE,FILENAME,ORDER_NUMBER,STATUS_HEADER,ROW_ID)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_TYPE ON TELS_RCRM_MV_LINE_ITEM'
        || ' (REC_TYPE)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      SYS.DBMS_STATS.GATHER_TABLE_STATS(
          OWNNAME           => 'TELSADMIN'
        , TABNAME           => 'TELS_RCRM_MV_LINE_ITEM'
        , ESTIMATE_PERCENT  => NULL
        , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
        , DEGREE            => NULL
        , CASCADE           => TRUE
        , NO_INVALIDATE     => FALSE);
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

-- TELS_RCRM_MV_MDLT

    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX TELS_RCRM_MV_MDLT_IX_1';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_MDLT', METHOD => 'C' );
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX TELS_RCRM_MV_MDLT_IX_1 ON TELS_RCRM_MV_MDLT'
        || ' (NAME,STARTDATE,ENDDATE,IDX_NAME_0,IDX_NAME_1,IDX_NAME_2,IDX_NAME_3,IDX_NAME_4,IDX_NAME_5,IDX_NAME_6)'
        || ' TABLESPACE TELS_TRANSFORMS';
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    BEGIN
      SYS.DBMS_STATS.GATHER_TABLE_STATS(
          OWNNAME           => 'TELSADMIN'
        , TABNAME           => 'TELS_RCRM_MV_MDLT'
        , ESTIMATE_PERCENT  => NULL
        , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
        , DEGREE            => NULL
        , CASCADE           => TRUE
        , NO_INVALIDATE     => FALSE);
    EXCEPTION
      WHEN OTHERS
      THEN NULL;
    END;

    COMMIT;

  END TELS_STAGE_RCRM_POST_LOAD;

END TELS_STAGE_RCRM_PKG;
/

SHOW ERRORS
