CREATE TABLE TELS_RCRM_STAGE_HOLD (
    filename                      VARCHAR2(255 BYTE) NOT NULL ENABLE,
    batchprocessdate              DATE NOT NULL ENABLE,
    recordnumber                  NUMBER(15,0) NOT NULL ENABLE,
    is_filtered                   NUMBER(1,0) NOT NULL ENABLE,
    order_number                  VARCHAR2(30 BYTE),
    billing_account               VARCHAR2(100 BYTE),
    customer_last_name            VARCHAR2(100 BYTE),
    customer_first_name           VARCHAR2(50 BYTE),
    order_type                    VARCHAR2(50 BYTE),
    order_sub_type                VARCHAR2(30 BYTE),
    created_date                  VARCHAR2(25 BYTE),
    partner_code                  VARCHAR2(30 BYTE),
    campaign_name                 VARCHAR2(100 BYTE),
    campaign_number               VARCHAR2(30 BYTE),
    campaign_type                 VARCHAR2(30 BYTE),
    channel_type                  VARCHAR2(30 BYTE),
    campaign_start_date           VARCHAR2(25 BYTE),
    business_unit                 VARCHAR2(1 BYTE),
    sales_force_id                VARCHAR2(30 BYTE),
    customer_id                   VARCHAR2(15 BYTE),
    order_revision_number         VARCHAR2(30 BYTE),
    submitted_date                VARCHAR2(25 BYTE),
    status_header                 VARCHAR2(30 BYTE),
    reason_code                   VARCHAR2(30 BYTE),
    commission_transaction_type   VARCHAR2(15 BYTE),
    source_system                 VARCHAR2(8 BYTE),
    row_id                        VARCHAR2(15 BYTE),
    product                       VARCHAR2(100 BYTE),
    part_number                   VARCHAR2(50 BYTE),
    action_code                   VARCHAR2(30 BYTE),
    transfer_type                 VARCHAR2(30 BYTE),
    event_source                  VARCHAR2(100 BYTE),
    prod_prom_id                  VARCHAR2(15 BYTE),
    provisioned_date              VARCHAR2(25 BYTE),
    net_price                     VARCHAR2(30 BYTE),
    commission_product_type       VARCHAR2(50 BYTE),
    commissionable                VARCHAR2(30 BYTE),
    status_order_line_item        VARCHAR2(30 BYTE),
    original_order_number         VARCHAR2(30 BYTE),
    hardware_supplied_flag        VARCHAR2(1 BYTE),
    sub_action_code               VARCHAR2(30 BYTE),
    promotion_integration_id      VARCHAR2(30 BYTE),
    ngb_prod_type                 VARCHAR2(30 BYTE),
    promotion_part_number         VARCHAR2(50 BYTE),
    product_id                    VARCHAR2(30 BYTE),
    o2a_status                    VARCHAR2(30 BYTE),
    parent_item_row_id            VARCHAR2(15 BYTE),
    root_item_row_id              VARCHAR2(15 BYTE),
    contract_start_date           VARCHAR2(25 BYTE),
    contract_end_date             VARCHAR2(25 BYTE),
    list_price                    VARCHAR2(30 BYTE),
    hardware_association_id       VARCHAR2(15 BYTE),
    attribute_row_id              VARCHAR2(15 BYTE),
    attribute_action_code         VARCHAR2(30 BYTE),
    attribute_display_name        VARCHAR2(100 BYTE),
    attribute_value               VARCHAR2(255 BYTE)
);