DROP TABLE TELS_RCRM_HOLD_ATTRIBUTES;

CREATE TABLE TELS_RCRM_HOLD_ATTRIBUTES (
    FILENAME                 VARCHAR2(255 BYTE),
    BATCHPROCESSDATE         DATE,
    RECORDNUMBER             NUMBER(15,0),
    IS_FILTERED              NUMBER(1,0),
    ORDER_NUMBER             VARCHAR2(30 BYTE),
    ORDER_SUB_TYPE           VARCHAR2(30 BYTE),
    STATUS_HEADER            VARCHAR2(30 BYTE),
    ROW_ID                   VARCHAR2(15 BYTE),
    ATTRIBUTE_ROW_ID         VARCHAR2(15),
    ATTRIBUTE_ACTION_CODE    VARCHAR2(30),
    ATTRIBUTE_DISPLAY_NAME   VARCHAR2(100),
    ATTRIBUTE_VALUE          VARCHAR2(255)
);

CREATE UNIQUE INDEX TELS_RCRM_HOLD_ATTRIBUTES ON TELS_RCRM_HOLD_ATTRIBUTES
(FILENAME,BATCHPROCESSDATE,RECORDNUMBER)
TABLESPACE TELS_SOURCES;

ALTER TABLE TELS_RCRM_HOLD_ATTRIBUTES ADD (
  CONSTRAINT TELS_RCRM_HOLD_ATTRIBUTES
  PRIMARY KEY
  (FILENAME,BATCHPROCESSDATE,RECORDNUMBER)
  USING INDEX TELS_RCRM_HOLD_ATTRIBUTES);