DROP TABLE TEST_IGNORE_COLUMN CASCADE CONSTRAINTS;

CREATE TABLE TEST_IGNORE_COLUMN
(

  COLUMN_NAME VARCHAR2(30)

)
TABLESPACE TELS_TRANSFORMS;

INSERT INTO TEST_IGNORE_COLUMN (COLUMN_NAME) VALUES ('FILENAME');
INSERT INTO TEST_IGNORE_COLUMN (COLUMN_NAME) VALUES ('BATCHPROCESSDATE');
INSERT INTO TEST_IGNORE_COLUMN (COLUMN_NAME) VALUES ('RECORDNUMBER');
INSERT INTO TEST_IGNORE_COLUMN (COLUMN_NAME) VALUES ('IS_FILTERED');
INSERT INTO TEST_IGNORE_COLUMN (COLUMN_NAME) VALUES ('QUERY_SRC');

COMMIT;
