ALTER TABLE TELS_DATA_FILE_SUMMARY RENAME TO TELS_CORE_DATA_FILE_SUMMARY;
ALTER TABLE TELS_DATA_SUMMARY RENAME TO TELS_CORE_DATA_SUMMARY;
ALTER TABLE TELS_INBOUND_FILE_RUN RENAME TO TELS_CORE_INBOUND_FILE_RUN;
ALTER TRIGGER TELS_INBOUND_FILE_RUN_TRG RENAME TO TELS_CORE_INBOUND_FILE_RUN_TRG;
--ALTER SEQUENCE TELS_INBOUND_FILE_RUN_SEQ RENAME TO TELS_CORE_INBOUND_FILE_RUN_SEQ;
--ALTER TABLE TELS_EXTRACT_SUMMARY RENAME TO TELS_CORE_EXTRACT_SUMMARY;

SELECT TELS_INBOUND_FILE_RUN_SEQ.NEXTVAL FROM DUAL;

CREATE SEQUENCE TELS_CORE_INBOUND_FILE_RUN_SEQ  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 475 NOCACHE  NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "TELS_CORE_INBOUND_FILE_RUN_TRG" BEFORE
    INSERT ON tels_core_inbound_file_run
    FOR EACH ROW
BEGIN
    SELECT
        tels_core_inbound_file_run_seq.NEXTVAL
    INTO
        :new.inboundfilerunkey
    FROM
        dual;
END;
/
ALTER TRIGGER "TELS_CORE_INBOUND_FILE_RUN_TRG" ENABLE;