
  CREATE TABLE "TELSADMIN"."TELS_INBOUND_FILE_RUN" 
   (	"INBOUNDFILERUNKEY" NUMBER(10,0), 
	"FILEHANDLERNAME" VARCHAR2(255 CHAR), 
	"BATCHNAME" VARCHAR2(255 CHAR), 
	"STARTTIME" DATE, 
	"ENDTIME" DATE, 
	"FILEHANDLERRETURNCODE" NUMBER(10,0)
   );
  
  CREATE TABLE "TELSADMIN"."TELS_DATA_SUMMARY" 
   (	"BUSINESSUNITNAME" VARCHAR2(255), 
	"FILEHANDLERNAME" VARCHAR2(255), 
	"SOURCEFILENAME" VARCHAR2(255), 
	"FILERECORDCOUNT" VARCHAR2(255), 
	"TARGETFILENAME_1" VARCHAR2(4000), 
	"TARGETRECORDCOUNT_1" VARCHAR2(255), 
	"TARGETFILENAME_2" VARCHAR2(255), 
	"TARGETRECORDCOUNT_2" VARCHAR2(255), 
	"ERRORFILENAME" VARCHAR2(255), 
	"ERRORCOUNT" VARCHAR2(255), 
	"BATCHPROCESSDATE" VARCHAR2(255)
   );
  
  CREATE TABLE "TELSADMIN"."TELS_DATA_FILE_SUMMARY" 
   (	"INBOUNDFILERUNKEY" NUMBER(10,0), 
	"FILENAME" VARCHAR2(256), 
	"FILEHANDLERNAME" VARCHAR2(256), 
	"STAGETABLENAME" VARCHAR2(30), 
	"BATCHNAME" VARCHAR2(90), 
	"PROCESSINGSTARTTIME" DATE, 
	"PROCESSINGENDTIME" DATE, 
	"RETURNCODE" NUMBER(10,0), 
	"FILERECORDCOUNT" NUMBER(10,0), 
	"STAGERECORDCOUNT" NUMBER(10,0), 
	"ERRORCOUNT" NUMBER(10,0), 
	"WARNINGCOUNT" NUMBER(10,0), 
	"ALREADYIMPORTEDCOUNT" NUMBER(10,0), 
	"TCVALIDATIONRETURNCODE" NUMBER(10,0), 
	"TCVALIDATIONINSERTCOUNT" NUMBER(10,0), 
	"TCVALIDATIONUPDATECOUNT" NUMBER(10,0), 
	"TCVALIDATIONERRORCOUNT" NUMBER(10,0), 
	"TCVALIDATIONWARNINGCOUNT" NUMBER(10,0), 
	"TCTRANSFERRETURNCODE" NUMBER(10,0), 
	"TCTRANSFERSUCCESSCOUNT" NUMBER(10,0), 
	"TCTRANSFERERRORCOUNT" NUMBER(10,0), 
	"TCTRANSFERWARNINGCOUNT" NUMBER(10,0), 
	"FILTEREDRECORDCOUNT" NUMBER(10,0)
   );
  
  CREATE TABLE "TELSADMIN"."TELS_PRESTAGE_ERROR" 
   (	"INBOUND_FILE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"INBOUND_RECORD_NUMBER" NUMBER(15,0) NOT NULL ENABLE, 
	"FIELDNAME" VARCHAR2(255), 
	"RECORDKEY" VARCHAR2(255), 
	"ORIGINALVALUE" VARCHAR2(255), 
	"TEMPVALUE" VARCHAR2(50), 
	"ERRORMESSAGE" VARCHAR2(255), 
	"FILERUNDATE" DATE, 
	"TABLENAME" VARCHAR2(50), 
	"ISWARNINGONLY" NUMBER(25,10)
   );

  CREATE TABLE "TELSADMIN"."TELS_EXTRACT_SUMMARY" 
   (	"PERIOD_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"EXTRACT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"PROCESSED_DATE" DATE NOT NULL ENABLE, 
	"FILE_SEQ" NUMBER(*,0) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(255), 
	 CONSTRAINT "TELS_EXTRACT_SUMMARY_PK" PRIMARY KEY ("PERIOD_NAME", "EXTRACT_TYPE", "PROCESSED_DATE", "FILE_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TALLYDATA"  ENABLE
   );