  CREATE TABLE "TELS_CORE_DATA_FILE_SUMMARY" 
   (
    "INBOUNDFILERUNKEY" NUMBER(10,0), 
	"FILENAME" VARCHAR2(256 BYTE), 
	"FILEHANDLERNAME" VARCHAR2(256 BYTE), 
	"STAGETABLENAME" VARCHAR2(30 BYTE), 
	"BATCHNAME" VARCHAR2(90 BYTE), 
	"PROCESSINGSTARTTIME" DATE, 
	"PROCESSINGENDTIME" DATE, 
	"RETURNCODE" NUMBER(10,0), 
	"FILERECORDCOUNT" NUMBER(10,0), 
	"STAGERECORDCOUNT" NUMBER(10,0), 
	"ERRORCOUNT" NUMBER(10,0), 
	"WARNINGCOUNT" NUMBER(10,0), 
	"ALREADYIMPORTEDCOUNT" NUMBER(10,0), 
	"TCVALIDATIONRETURNCODE" NUMBER(10,0), 
	"TCVALIDATIONINSERTCOUNT" NUMBER(10,0), 
	"TCVALIDATIONUPDATECOUNT" NUMBER(10,0), 
	"TCVALIDATIONERRORCOUNT" NUMBER(10,0), 
	"TCVALIDATIONWARNINGCOUNT" NUMBER(10,0), 
	"TCTRANSFERRETURNCODE" NUMBER(10,0), 
	"TCTRANSFERSUCCESSCOUNT" NUMBER(10,0), 
	"TCTRANSFERERRORCOUNT" NUMBER(10,0), 
	"TCTRANSFERWARNINGCOUNT" NUMBER(10,0), 
	"FILTEREDRECORDCOUNT" NUMBER(10,0)
   );

  CREATE TABLE "TELS_CORE_DATA_SUMMARY" 
   (
    "BUSINESSUNITNAME" VARCHAR2(255 BYTE), 
	"FILEHANDLERNAME" VARCHAR2(255 BYTE), 
	"SOURCEFILENAME" VARCHAR2(255 BYTE), 
	"FILERECORDCOUNT" VARCHAR2(255 BYTE), 
	"TARGETFILENAME_1" VARCHAR2(4000 BYTE), 
	"TARGETRECORDCOUNT_1" VARCHAR2(255 BYTE), 
	"TARGETFILENAME_2" VARCHAR2(255 BYTE), 
	"TARGETRECORDCOUNT_2" VARCHAR2(255 BYTE), 
	"ERRORFILENAME" VARCHAR2(255 BYTE), 
	"ERRORCOUNT" VARCHAR2(255 BYTE), 
	"BATCHPROCESSDATE" VARCHAR2(255 BYTE)
   );

  CREATE TABLE "TELS_CORE_INBOUND_FILE_RUN" 
   (
    "INBOUNDFILERUNKEY" NUMBER(10,0), 
	"FILEHANDLERNAME" VARCHAR2(255 CHAR), 
	"BATCHNAME" VARCHAR2(255 CHAR), 
	"STARTTIME" DATE, 
	"ENDTIME" DATE, 
	"FILEHANDLERRETURNCODE" NUMBER(10,0)
   );

  CREATE TABLE "TELS_CORE_PRESTAGE_ERROR" 
   (
    "INBOUND_FILE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"INBOUND_RECORD_NUMBER" NUMBER(15,0) NOT NULL ENABLE, 
	"FIELDNAME" VARCHAR2(255), 
	"RECORDKEY" VARCHAR2(255), 
	"ORIGINALVALUE" VARCHAR2(255), 
	"TEMPVALUE" VARCHAR2(50), 
	"ERRORMESSAGE" VARCHAR2(255), 
	"FILERUNDATE" DATE, 
	"TABLENAME" VARCHAR2(50), 
	"ISWARNINGONLY" NUMBER(25,10)
   );
   
CREATE SEQUENCE TELS_CORE_INBOUND_FILE_RUN_SEQ  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 475 NOCACHE  NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "TELS_CORE_INBOUND_FILE_RUN_TRG" BEFORE
    INSERT ON tels_core_inbound_file_run
    FOR EACH ROW
BEGIN
    SELECT
        tels_core_inbound_file_run_seq.NEXTVAL
    INTO
        :new.inboundfilerunkey
    FROM
        dual;
END;
/
ALTER TRIGGER "TELS_CORE_INBOUND_FILE_RUN_TRG" ENABLE;