ALTER TABLE TELS_CORE_PRESTAGEERROR DROP PRIMARY KEY CASCADE;

DROP TABLE TELS_CORE_PRESTAGEERROR CASCADE CONSTRAINTS;

CREATE TABLE TELS_CORE_PRESTAGEERROR
(
  FILENAME       VARCHAR2(256 BYTE),
  RECORDNUMBER   NUMBER(22),
  FIELDNAME      VARCHAR2(30 BYTE),
  RECORDKEY      VARCHAR2(256 BYTE),
  ORIGINALVALUE  VARCHAR2(256 BYTE),
  TEMPVALUE      VARCHAR2(50 BYTE),
  ERRORMESSAGE   VARCHAR2(256 BYTE),
  FILERUNDATE    DATE,
  TABLENAME      VARCHAR2(50 BYTE),
  ISWARNINGONLY  NUMBER(1)
);

CREATE INDEX TELS_CORE_PRESTAGEERROR_FN ON TELS_CORE_PRESTAGEERROR
(FILENAME,RECORDNUMBER,FIELDNAME,FILERUNDATE)
TABLESPACE TELS_TRANSFORMS;

ALTER TABLE TELS_CORE_PRESTAGEERROR ADD (
  CONSTRAINT TELS_CORE_PRESTAGEERROR_FN
  PRIMARY KEY
  (FILENAME,RECORDNUMBER,FIELDNAME,FILERUNDATE)
  USING INDEX TELS_CORE_PRESTAGEERROR_FN);