DROP MATERIALIZED VIEW TELS_RCRM_MV_LINE_ITEM;

DROP TABLE TELS_RCRM_MV_LINE_ITEM CASCADE CONSTRAINTS;

CREATE TABLE TELS_RCRM_MV_LINE_ITEM
(
    REC_TYPE VARCHAR2(30)
  , FILENAME VARCHAR2(255)
  , BATCHPROCESSDATE DATE
  , RECORDNUMBER NUMBER(15)
  , IS_FILTERED NUMBER(1)
  , ORDER_NUMBER VARCHAR2(30)
  , BILLING_ACCOUNT VARCHAR2(100)
  , CUSTOMER_LAST_NAME VARCHAR2(100)
  , CUSTOMER_FIRST_NAME VARCHAR2(50)
  , ORDER_TYPE VARCHAR2(50)
  , ORDER_SUB_TYPE VARCHAR2(30)
  , CREATED_DATE VARCHAR2(25)
  , PARTNER_CODE VARCHAR2(30)
  , CAMPAIGN_NAME VARCHAR2(100)
  , CAMPAIGN_NUMBER VARCHAR2(30)
  , CAMPAIGN_TYPE VARCHAR2(30)
  , CHANNEL_TYPE VARCHAR2(30)
  , CAMPAIGN_START_DATE VARCHAR2(25)
  , BUSINESS_UNIT VARCHAR2(1)
  , SALES_FORCE_ID VARCHAR2(30)
  , CUSTOMER_ID VARCHAR2(15)
  , ORDER_REVISION_NUMBER VARCHAR2(30)
  , SUBMITTED_DATE VARCHAR2(25)
  , STATUS_HEADER VARCHAR2(30)
  , REASON_CODE VARCHAR2(30)
  , COMMISSION_TRANSACTION_TYPE VARCHAR2(15)
  , SOURCE_SYSTEM VARCHAR2(8)
  , ROW_ID VARCHAR2(15)
  , PRODUCT VARCHAR2(100)
  , PART_NUMBER VARCHAR2(50)
  , ACTION_CODE VARCHAR2(30)
  , TRANSFER_TYPE VARCHAR2(30)
  , EVENT_SOURCE VARCHAR2(100)
  , PROD_PROM_ID VARCHAR2(15)
  , PROVISIONED_DATE VARCHAR2(25)
  , NET_PRICE VARCHAR2(30)
  , COMMISSION_PRODUCT_TYPE VARCHAR2(50)
  , COMMISSIONABLE VARCHAR2(30)
  , STATUS_ORDER_LINE_ITEM VARCHAR2(30)
  , ORIGINAL_ORDER_NUMBER VARCHAR2(30)
  , HARDWARE_SUPPLIED_FLAG VARCHAR2(1)
  , SUB_ACTION_CODE VARCHAR2(30)
  , PROMOTION_INTEGRATION_ID VARCHAR2(30)
  , NGB_PROD_TYPE VARCHAR2(30)
  , PROMOTION_PART_NUMBER VARCHAR2(50)
  , PRODUCT_ID VARCHAR2(30)
  , O2A_STATUS VARCHAR2(30)
  , PARENT_ITEM_ROW_ID VARCHAR2(15)
  , ROOT_ITEM_ROW_ID VARCHAR2(15)
  , CONTRACT_START_DATE VARCHAR2(25)
  , CONTRACT_END_DATE VARCHAR2(25)
  , LIST_PRICE VARCHAR2(30)
  , HARDWARE_ASSOCIATION_ID VARCHAR2(15)
  , EFFECTIVE_DATE VARCHAR2(25)
)
TABLESPACE TELS_TRANSFORMS;

DROP MATERIALIZED VIEW TELS_RCRM_MV_LINE_ITEM;

CREATE MATERIALIZED VIEW TELS_RCRM_MV_LINE_ITEM
ON PREBUILT TABLE
REFRESH COMPLETE
ON DEMAND
AS
SELECT * FROM TELS_RCRM_VW_LINE_ITEM
;

BEGIN
  DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_LINE_ITEM', METHOD => 'C' );
END;

--SELECT * FROM TELS_RCRM_MV_LINE_ITEM;

--CREATE INDEX TELS_RCRM_MV_LINE_ITEM_PK ON TELS_RCRM_MV_LINE_ITEM
--(FILENAME,BATCHPROCESSDATE,RECORDNUMBER)
--TABLESPACE TELS_TRANSFORMS;

DROP INDEX TELS_RCRM_MV_LINE_ITEM_IX_2;

CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_2 ON TELS_RCRM_MV_LINE_ITEM
--(FILENAME,ROW_ID,ORDER_NUMBER,ATTRIBUTE_DISPLAY_NAME)
(ROW_ID,FILENAME)
TABLESPACE TELS_TRANSFORMS
;

BEGIN
  SYS.DBMS_STATS.GATHER_TABLE_STATS(
      OWNNAME           => 'TELSADMIN'
    , TABNAME           => 'TELS_RCRM_MV_LINE_ITEM'
    , ESTIMATE_PERCENT  => NULL
    , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
    , DEGREE            => NULL
    , CASCADE           => TRUE
    , NO_INVALIDATE     => FALSE);
END;

CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_1 ON TELS_RCRM_MV_LINE_ITEM
(FILENAME,ORDER_NUMBER,ROW_ID)
TABLESPACE TELS_TRANSFORMS;

CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_2 ON TELS_RCRM_MV_LINE_ITEM
(ROW_ID,FILENAME)
TABLESPACE TELS_TRANSFORMS;

CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_ROOT ON TELS_RCRM_MV_LINE_ITEM
(REC_TYPE,FILENAME,ORDER_NUMBER,STATUS_HEADER,ROOT_ITEM_ROW_ID)
TABLESPACE TELS_TRANSFORMS;

CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_ROW ON TELS_RCRM_MV_LINE_ITEM
(REC_TYPE,FILENAME,ORDER_NUMBER,STATUS_HEADER,ROW_ID)
TABLESPACE TELS_TRANSFORMS;

CREATE INDEX TELS_RCRM_MV_LINE_ITEM_IX_TYPE ON TELS_RCRM_MV_LINE_ITEM
(REC_TYPE)
TABLESPACE TELS_TRANSFORMS;
