DROP MATERIALIZED VIEW TELS_RCRM_MV_MOLI_ROOT;

DROP TABLE TELS_RCRM_MV_MOLI_ROOT CASCADE CONSTRAINTS;

CREATE TABLE TELS_RCRM_MV_MOLI_ROOT
(
    FILENAME VARCHAR2(255)
  , BATCHPROCESSDATE DATE
  , RECORDNUMBER NUMBER(15)
  , IS_FILTERED NUMBER(1)
  , ORDER_NUMBER VARCHAR2(30)
  , BILLING_ACCOUNT VARCHAR2(100)
  , CUSTOMER_LAST_NAME VARCHAR2(100)
  , CUSTOMER_FIRST_NAME VARCHAR2(50)
  , ORDER_TYPE VARCHAR2(50)
  , ORDER_SUB_TYPE VARCHAR2(30)
  , CREATED_DATE VARCHAR2(25)
  , PARTNER_CODE VARCHAR2(30)
  , CAMPAIGN_NAME VARCHAR2(100)
  , CAMPAIGN_NUMBER VARCHAR2(30)
  , CAMPAIGN_TYPE VARCHAR2(30)
  , CHANNEL_TYPE VARCHAR2(30)
  , CAMPAIGN_START_DATE VARCHAR2(25)
  , BUSINESS_UNIT VARCHAR2(1)
  , SALES_FORCE_ID VARCHAR2(30)
  , CUSTOMER_ID VARCHAR2(15)
  , ORDER_REVISION_NUMBER VARCHAR2(30)
  , SUBMITTED_DATE VARCHAR2(25)
  , STATUS_HEADER VARCHAR2(30)
  , REASON_CODE VARCHAR2(30)
  , COMMISSION_TRANSACTION_TYPE VARCHAR2(15)
  , SOURCE_SYSTEM VARCHAR2(8)
  , ROW_ID VARCHAR2(15)
  , PRODUCT VARCHAR2(100)
  , PART_NUMBER VARCHAR2(50)
  , ACTION_CODE VARCHAR2(30)
  , TRANSFER_TYPE VARCHAR2(30)
  , EVENT_SOURCE VARCHAR2(100)
  , PROD_PROM_ID VARCHAR2(15)
  , PROVISIONED_DATE VARCHAR2(25)
  , NET_PRICE VARCHAR2(30)
  , COMMISSION_PRODUCT_TYPE VARCHAR2(50)
  , COMMISSIONABLE VARCHAR2(30)
  , STATUS_ORDER_LINE_ITEM VARCHAR2(30)
  , ORIGINAL_ORDER_NUMBER VARCHAR2(30)
  , HARDWARE_SUPPLIED_FLAG VARCHAR2(1)
  , SUB_ACTION_CODE VARCHAR2(30)
  , PROMOTION_INTEGRATION_ID VARCHAR2(30)
  , NGB_PROD_TYPE VARCHAR2(30)
  , PROMOTION_PART_NUMBER VARCHAR2(50)
  , PRODUCT_ID VARCHAR2(30)
  , O2A_STATUS VARCHAR2(30)
  , PARENT_ITEM_ROW_ID VARCHAR2(15)
  , ROOT_ITEM_ROW_ID VARCHAR2(15)
  , CONTRACT_START_DATE VARCHAR2(25)
  , CONTRACT_END_DATE VARCHAR2(25)
  , LIST_PRICE VARCHAR2(30)
  , HARDWARE_ASSOCIATION_ID VARCHAR2(15)
  , EFFECTIVE_DATE VARCHAR2(25)
)
TABLESPACE TELS_TRANSFORMS;

CREATE MATERIALIZED VIEW TELS_RCRM_MV_MOLI_ROOT
ON PREBUILT TABLE
REFRESH COMPLETE
ON DEMAND
AS
SELECT
--  CAST('MOLI' AS VARCHAR2(255)) AS "REC_TYPE",
  D.FILENAME,
  D.BATCHPROCESSDATE,
  CAST(MAX(D.RECORDNUMBER) AS NUMBER(15)) AS "RECORDNUMBER",
  D.IS_FILTERED,
  D.ORDER_NUMBER,
  D.BILLING_ACCOUNT,
  D.CUSTOMER_LAST_NAME,
  D.CUSTOMER_FIRST_NAME,
  D.ORDER_TYPE,
  D.ORDER_SUB_TYPE,
  D.CREATED_DATE,
  D.PARTNER_CODE,
  D.CAMPAIGN_NAME,
  D.CAMPAIGN_NUMBER,
  D.CAMPAIGN_TYPE,
  D.CHANNEL_TYPE,
  D.CAMPAIGN_START_DATE,
  D.BUSINESS_UNIT,
  D.SALES_FORCE_ID,
  D.CUSTOMER_ID,
  D.ORDER_REVISION_NUMBER,
  D.SUBMITTED_DATE,
  D.STATUS_HEADER,
  D.REASON_CODE,
  D.COMMISSION_TRANSACTION_TYPE,
  D.SOURCE_SYSTEM,
  D.ROW_ID,
  D.PRODUCT,
  D.PART_NUMBER,
  D.ACTION_CODE,
  D.TRANSFER_TYPE,
  D.EVENT_SOURCE,
  D.PROD_PROM_ID,
  D.PROVISIONED_DATE,
  D.NET_PRICE,
  D.COMMISSION_PRODUCT_TYPE,
  D.COMMISSIONABLE,
  D.STATUS_ORDER_LINE_ITEM,
  D.ORIGINAL_ORDER_NUMBER,
  D.HARDWARE_SUPPLIED_FLAG,
  D.SUB_ACTION_CODE,
  D.PROMOTION_INTEGRATION_ID,
  D.NGB_PROD_TYPE,
  D.PROMOTION_PART_NUMBER,
  D.PRODUCT_ID,
  D.O2A_STATUS,
  D.PARENT_ITEM_ROW_ID,
  D.ROOT_ITEM_ROW_ID,
  D.CONTRACT_START_DATE,
  D.CONTRACT_END_DATE,
  D.LIST_PRICE,
  D.HARDWARE_ASSOCIATION_ID,
  CAST(DECODE(D.STATUS_HEADER,'Completed',D.PROVISIONED_DATE,D.SUBMITTED_DATE) AS VARCHAR2(25)) AS "EFFECTIVE_DATE"
FROM TELS_STAGE_RCRM D
WHERE (1=1)
AND D.ROOT_ITEM_ROW_ID = D.ROW_ID
AND NVL(D.ORDER_SUB_TYPE,'NULL') <> 'Transfer'
GROUP BY
--  'MOLI',
  D.FILENAME,
  D.BATCHPROCESSDATE,
  D.IS_FILTERED,
  D.ORDER_NUMBER,
  D.BILLING_ACCOUNT,
  D.CUSTOMER_LAST_NAME,
  D.CUSTOMER_FIRST_NAME,
  D.ORDER_TYPE,
  D.ORDER_SUB_TYPE,
  D.CREATED_DATE,
  D.PARTNER_CODE,
  D.CAMPAIGN_NAME,
  D.CAMPAIGN_NUMBER,
  D.CAMPAIGN_TYPE,
  D.CHANNEL_TYPE,
  D.CAMPAIGN_START_DATE,
  D.BUSINESS_UNIT,
  D.SALES_FORCE_ID,
  D.CUSTOMER_ID,
  D.ORDER_REVISION_NUMBER,
  D.SUBMITTED_DATE,
  D.STATUS_HEADER,
  D.REASON_CODE,
  D.COMMISSION_TRANSACTION_TYPE,
  D.SOURCE_SYSTEM,
  D.ROW_ID,
  D.PRODUCT,
  D.PART_NUMBER,
  D.ACTION_CODE,
  D.TRANSFER_TYPE,
  D.EVENT_SOURCE,
  D.PROD_PROM_ID,
  D.PROVISIONED_DATE,
  D.NET_PRICE,
  D.COMMISSION_PRODUCT_TYPE,
  D.COMMISSIONABLE,
  D.STATUS_ORDER_LINE_ITEM,
  D.ORIGINAL_ORDER_NUMBER,
  D.HARDWARE_SUPPLIED_FLAG,
  D.SUB_ACTION_CODE,
  D.PROMOTION_INTEGRATION_ID,
  D.NGB_PROD_TYPE,
  D.PROMOTION_PART_NUMBER,
  D.PRODUCT_ID,
  D.O2A_STATUS,
  D.PARENT_ITEM_ROW_ID,
  D.ROOT_ITEM_ROW_ID,
  D.CONTRACT_START_DATE,
  D.CONTRACT_END_DATE,
  D.LIST_PRICE,
  D.HARDWARE_ASSOCIATION_ID,
  DECODE(D.STATUS_HEADER,'Completed',D.PROVISIONED_DATE,D.SUBMITTED_DATE)
;

BEGIN
  DBMS_MVIEW.REFRESH( LIST => 'TELSADMIN.TELS_RCRM_MV_MOLI_ROOT', METHOD => 'C' );
END;

DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_1;

CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_1 ON TELS_RCRM_MV_MOLI_ROOT
(COMMISSION_PRODUCT_TYPE,ACTION_CODE)
TABLESPACE TELS_TRANSFORMS
;

DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_2;

CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_2 ON TELS_RCRM_MV_MOLI_ROOT
(ROOT_ITEM_ROW_ID,ORDER_NUMBER,STATUS_HEADER,FILENAME)
TABLESPACE TELS_TRANSFORMS
;

DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_3;

CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_3 ON TELS_RCRM_MV_MOLI_ROOT
(ROW_ID,ORDER_NUMBER,STATUS_HEADER,FILENAME)
TABLESPACE TELS_TRANSFORMS
;

DROP INDEX TELS_RCRM_MV_MOLI_ROOT_IX_4;

CREATE INDEX TELS_RCRM_MV_MOLI_ROOT_IX_4 ON TELS_RCRM_MV_MOLI_ROOT
(PROMOTION_INTEGRATION_ID,ORDER_NUMBER,STATUS_HEADER,FILENAME)
TABLESPACE TELS_TRANSFORMS
;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(
      OWNNAME           => 'TELSADMIN'
    , TABNAME           => 'TELS_RCRM_MV_MOLI_ROOT'
    , ESTIMATE_PERCENT  => NULL
    , METHOD_OPT        => 'FOR ALL INDEXED COLUMNS SIZE AUTO'
    , DEGREE            => NULL
    , CASCADE           => TRUE
    , NO_INVALIDATE     => FALSE
    );
END;

--SELECT * FROM TELS_RCRM_MV_MOLI_ROOT;

--CREATE INDEX TELS_RCRM_MV_MOLI_PK ON TELS_RCRM_MV_MOLI
--(FILENAME,BATCHPROCESSDATE,RECORDNUMBER)
--TABLESPACE TELS_TRANSFORMS;
