
SELECT 
    DISTINCT
    cdt.RULESEQ QUOTA_ID,
    'COMMISSION' TRANSACTION_TYPE,
    '10000' INTERVAL_TYPE_ID,
    cdt.RULESEQ CALC_FORMULA_ID,
    cdt.GENERICATTRIBUTE15 PLAN_ELEMENT_DESCRIPTION,
    cdr.NAME CALC_FORMULA_NAME,
    cdr.NAME || CASE WHEN cdr.DESCRIPTION <> '' THEN ' - '||cdr.DESCRIPTION ELSE '' END CALC_FORMULA_DESCRIPTION
FROM 
  CS_CREDIT@TC_LINK cdt
  JOIN CS_RULE@TC_LINK cdr ON
    cdr.RULESEQ = cdt.RULESEQ
    AND cdr.TENANTID = cdt.TENANTID
    AND cdr.REMOVEDATE = TO_DATE('01012200','DDMMYYYY')
WHERE
  cdt.TENANTID = 'TELS';

