
SELECT * FROM TELS_CCG_COMMISSION_QUOTA;
SELECT * FROM TELS_CCG_DEALER_TRANSLATION;
SELECT * FROM TELS_CCG_PARTNER;
SELECT * FROM TELS_CCG_PAY_PERIOD;
SELECT * FROM TELS_CCG_POST_PAYBATCH;
SELECT * FROM TELS_CCG_USER;