SELECT * FROM(
SELECT
    per.NAME PERIOD,
    'NOT SET' CH_SALE_STAFF_ID,
    'NEW' CH_CH_ADJUST_STATUS,
    'ROLL' CH_STATUS,
    'MANUAL' CH_SOURCE_SYSTEM,
    'COMMISSIONABLE TRANSACTION' CH_SYSTEM_PROCESS,
    CASE WHEN etx.GENERICATTRIBUTE2 IS NULL THEN etx.GENERICATTRIBUTE3 ELSE etx.GENERICATTRIBUTE2 || ' ' || etx.GENERICATTRIBUTE3 END CH_CUSTOMER_NAME,
    etx.GENERICATTRIBUTE1 CH_BILLING_ACCOUNT,
    txn.GENERICATTRIBUTE22 CH_IMEI,
    txn.GENERICDATE2 CH_CONT_ADD_START_DATE,
    etx.GENERICNUMBER5 CH_CONT_ADD_TERM_VALUE,
    txn.GENERICBOOLEAN2 CH_PRIOR_ALLOW_REC_CON,
    txn.GENERICDATE3 CH_CONT_DEL_START_DATE,
    etx.GENERICNUMBER7 CH_CONT_DEL_TERM_VALUE,
    cdt.GENERICATTRIBUTE12 CH_PRODUCT_CATEGORY,
    CASE WHEN txn.DATASOURCE = 'MAXIMPRM' THEN txn.GENERICATTRIBUTE8 ELSE txn.GENERICATTRIBUTE30 END CH_PRODUCT_DESCRIPTION,
    txn.PRODUCTNAME CH_COLI_PART_NUMBER,
    txn.GENERICATTRIBUTE27 CH_NETWORK,
    txn.GENERICATTRIBUTE6 CH_PRODUCT_FAMILY_CODE,
    txn.GENERICATTRIBUTE30 CH_PRODUCT_FAMILY_DESC,
    txn.GENERICATTRIBUTE11 CH_PRODUCT_ATTRIBUTE_1,
    txn.GENERICATTRIBUTE12 CH_PRODUCT_ATTRIBUTE_2,
    txn.GENERICATTRIBUTE13 CH_PRODUCT_ATTRIBUTE_3,
    txn.GENERICATTRIBUTE14 CH_PRODUCT_ATTRIBUTE_4,
    'NOT SET' CH_PRODUCT_REVIEW_NAME_1,
    'NOT SET' CH_PRODUCT_REVIEW_NAME_2,
    CASE WHEN cdt.GENERICATTRIBUTE11 = 'Sales Incentive' THEN cdt.GENERICNUMBER1 END CH_PLAN_MMC,
    'NOT SET' CH_PRODUCT_CODE_PREMIUM_PLAN,
    txn.GENERICNUMBER1 CH_PERCENT_SUB_COMPLETION,
    txn.GENERICDATE1 CH_COMPLETION_DATE,
    txn.GENERICBOOLEAN4 CH_HARDWARE_SUPPLIED,
    txn.GENERICATTRIBUTE7 CH_ACCESS_TYPE,
    txn.GENERICBOOLEAN1 CH_SHAPED_UNSHAPED,
    NULL CH_CAMPAIGN_ID,
    NULL CH_CAMPAIGN_NAME,
    txn.GENERICATTRIBUTE28 CH_SUBSCRIPTION_CATEGORY,
    'NOT SET' CH_SALES_METHOD,
    etx.GENERICNUMBER4 CH_LIST_PRICE,
    etx.GENERICNUMBER2 CH_QUANTITY,
    CASE WHEN txn.DATASOURCE = 'MAXIMPRM' THEN txn.COMPENSATIONDATE ELSE NULL END CH_SUBMISSION_DATE,
    txn.GENERICATTRIBUTE1 CH_SALES_TYPE,
    '-10000' CL_CREDIT_TYPE_ID,
    'CALC' CL_STATUS,
    'ROLL' CL_CREATED_DURING,
    CASE WHEN pip.PIPELINERUNSEQ IS NOT NULL THEN 'POSTED' ELSE 'NOT POSTED' END CL_POSTING_STATUS,
    'NNNN' CL_PRE_PROC_CODE,
    cdt.VALUE CL_COMMISSION_PAYABLE,
    'NULL' SALE_INCET_NUM,
    cdt.GENERICNUMBER1 BASE_REM,
    '9999' CL_REVENUE_CLASS_ID,
    NULL CL_ERROR_REASON,
    cdt.CREDITSEQ TA_COMMISSION_LINE_ID,
    pip.PIPELINERUNSEQ TA_PAYRUN_ID,
    TO_CHAR(per.STARTDATE,'YYYY')||'_'||per.DESCRIPTION TA_PAY_PERIOD_ID,
    cdt.RULESEQ TA_QUOTA_RULE_ID,
    cdt.RULESEQ TA_QUOTA_ID,
    CASE WHEN pip.PIPELINERUNSEQ IS NOT NULL THEN 'Y' ELSE 'N' END TA_PAID_FLAG,
    cdt.CREDITSEQ X_COMMISSION_HEADER_ID,
    cdt.CREDITSEQ X_PAYMENT_TRANSACTION_ID,
    ord.ORDERID X_ORDER_NUMBER,
    txn.SUBLINENUMBER X_ORDER_LINE_ITEM,
    NULL X_INVOICE_NUMBER, --!!!! Needs to be mapped in Informatica via call FNC_TELS_GET_INVOICE_NUMBER(per.NAME, par.USERID) !!!!
    txn.GENERICATTRIBUTE29 X_SERVICE_IDENTIF,
    cdt.GENERICDATE5 X_BASE_DATE_FOR_PAYMENT,
    cdt.GENERICDATE5 X_APPROVED_DATE,
    par.USERID X_CREDITED_SALESREP_ID,
    txn.CHANNEL X_DIRECT_SALESREP_ID,
    cdt.GENERICDATE5 X_POSTING_DATE_PERIOD,
    txn.COMMENTS X_COMMENTS,
    substr(cdt.GENERICATTRIBUTE16, instr(cdt.GENERICATTRIBUTE16,'-')+1, 6) X_ACTIVITY_TYPE, 
    cdt.GENERICNUMBER6 X_GST_AMOUNT,
    NULL X_PRECM01_ID, --!!!! Needs to be mapped in Informatica !!!!
    cdt.VALUE X_COMMISSION_AMOUNT,
    cdt.RULESEQ X_QUOTA_ID,
    cdt.GENERICATTRIBUTE11 X_COMMISSION_TYPE,
    cdt.GENERICATTRIBUTE15 X_PLAN_ELEMENT,
    cdt.GENERICATTRIBUTE12 X_PRODUCT_CATEGORY,
    'S' X_STATUS_FLAG,
    'NOT SET' X_STATUS_MSG
FROM
  CS_CREDIT@TC_LINK cdt
  JOIN CS_SALESTRANSACTION@TC_LINK txn ON
    txn.SALESTRANSACTIONSEQ = cdt.SALESTRANSACTIONSEQ
    AND txn.TENANTID = cdt.TENANTID
    AND txn.PROCESSINGUNITSEQ = cdt.PROCESSINGUNITSEQ
  JOIN CS_GASALESTRANSACTION@TC_LINK etx ON
    etx.SALESTRANSACTIONSEQ = txn.SALESTRANSACTIONSEQ
    AND etx.TENANTID = txn.TENANTID
    AND etx.PAGENUMBER = 0
    AND etx.PROCESSINGUNITSEQ = txn.PROCESSINGUNITSEQ
  JOIN CS_SALESORDER@TC_LINK ord ON
    ord.SALESORDERSEQ = txn.SALESORDERSEQ
    AND ord.TENANTID = txn.TENANTID
    AND ord.PROCESSINGUNITSEQ = txn.PROCESSINGUNITSEQ
    AND ord.REMOVEDATE = TO_DATE('01012200','DDMMYYYY')
  JOIN CS_PERIOD@TC_LINK per ON
    per.PERIODSEQ = cdt.PERIODSEQ
    AND per.TENANTID = cdt.TENANTID
    AND per.REMOVEDATE = TO_DATE('01012200','DDMMYYYY')
  JOIN CS_PARTICIPANT@TC_LINK par ON
    ((par.effectiveStartDate < per.endDate and par.effectiveEndDate >= per.endDate) or (par.effectiveEndDate < per.endDate and par.isLast=1))
    AND par.REMOVEDATE = TO_DATE('01012200','DDMMYYYY')
    AND par.PAYEESEQ = cdt.PAYEESEQ
    AND par.TENANTID = cdt.TENANTID
  LEFT OUTER JOIN CS_PIPELINERUN@TC_LINK pip ON
    pip.PROCESSINGUNITSEQ = cdt.PROCESSINGUNITSEQ
    AND pip.PERIODSEQ = cdt.PERIODSEQ
    AND pip.TENANTID = cdt.TENANTID
    AND pip.COMMAND = 'PipelineRun'
    AND pip.STATUS = 'Successful'
    AND pip.DESCRIPTION LIKE('%stage=Post%')
WHERE
  cdt.TENANTID = 'TELS'
  AND per.NAME = 'SEPW1-FY18'
) WHERE CH_CUSTOMER_NAME IS NOT NULL;
  
  SELECT * FROM CS_PIPELINERUN@TC_LINK;
  select * from TELS_INVOICE_NUMBER;
  
  rollback;