SELECT 
    usr.ID USER_ID,
    usr.USERNAME USER_NAME,
    usr.CREATEDATE START_DATE,
    usr.REMOVEDATE END_DATE,
    usr.EMAIL EMAIL_ADDRESS,
    usr.DESCRIPTION DESCRIPTION,
    'Incentive Compensation' APPLICATION_NAME,
    grp.NAME RESPONSIBILITY_NAME,
    'Standard' SECURITY_GROUP_NAME,
    grp.CREATEDATE RESPONSIBILITY_START_DATE,
    grp.REMOVEDATE RESPONSIBILITY_END_DATE,
    usr.CREATEDATE Import_Date
FROM CS_USER@TC_LINK usr
  JOIN CS_USER_GROUPS@TC_LINK usg ON
    usg.USERSEQ = usr.USERSEQ
    AND usg.REMOVEDATE = TO_DATE('01012200','DDMMYYYY')
    AND usg.TENANTID = usr.TENANTID
  JOIN CS_GROUP@TC_LINK grp ON
    grp.GROUPSEQ = usg.GROUPSEQ
    AND grp.TENANTID = usg.TENANTID
    AND grp.REMOVEDATE = TO_DATE('01012200','DDMMYYYY')
WHERE
  usg.TENANTID = 'TELS'
ORDER BY
  usr.ID, usr.REMOVEDATE;

SELECT * FROM CS_USER@TC_LINK usr;
SELECT * FROM CS_USER_GROUPS@TC_LINK;
SELECT * FROM CS_GROUP@TC_LINK;

