/********************************************************************
  ** TELS_CCG_POST_PAYBATCH
  **
  ** Version: 1.0
  ** Author: Simon Marsh
  ** Created: June 2018
  ** Description:
  **
  ** Date       Modified By   Description
  ** ------------------------------------------------------------------
  ** 20180619   Simon Marsh   Initial Version
  ********************************************************************/
--DROP TABLE TELS_CCG_POST_PAYBATCH;
CREATE TABLE TELS_CCG_POST_PAYBATCH
(
    PERIOD                       varchar(50),
    CH_SALE_STAFF_ID             varchar(50),
    CH_CH_ADJUST_STATUS          varchar(50),
    CH_STATUS                    varchar(50),
    CH_SOURCE_SYSTEM             varchar(50),
    CH_SYSTEM_PROCESS            varchar(50),
    CH_CUSTOMER_NAME             varchar(510),
    CH_BILLING_ACCOUNT           varchar(255),
    CH_IMEI                      varchar(255),
    CH_CONT_ADD_START_DATE       varchar(29),
    CH_CONT_ADD_TERM_VALUE       varchar(28),
    CH_PRIOR_ALLOW_REC_CON       varchar(1),
    CH_CONT_DEL_START_DATE       varchar(29),
    CH_CONT_DEL_TERM_VALUE       varchar(28),
    CH_PRODUCT_CATEGORY          varchar(255),
    CH_PRODUCT_DESCRIPTION       varchar(255),
    CH_COLI_PART_NUMBER          varchar(255),
    CH_NETWORK                   varchar(255),
    CH_PRODUCT_FAMILY_CODE       varchar(255),
    CH_PRODUCT_FAMILY_DESC       varchar(255),
    CH_PRODUCT_ATTRIBUTE_1       varchar(255),
    CH_PRODUCT_ATTRIBUTE_2       varchar(255),
    CH_PRODUCT_ATTRIBUTE_3       varchar(255),
    CH_PRODUCT_ATTRIBUTE_4       varchar(255),
    CH_PRODUCT_REVIEW_NAME_1     varchar(50),
    CH_PRODUCT_REVIEW_NAME_2     varchar(50),
    CH_PLAN_MMC                  varchar(28),
    CH_PRODUCT_CODE_PREMIUM_PLAN varchar(50),
    CH_PERCENT_SUB_COMPLETION    varchar(28),
    CH_COMPLETION_DATE           varchar(29),
    CH_HARDWARE_SUPPLIED         varchar(1),
    CH_ACCESS_TYPE               varchar(255),
    CH_SHAPED_UNSHAPED           varchar(1),
    CH_CAMPAIGN_ID               varchar(10),
    CH_CAMPAIGN_NAME             varchar(10),
    CH_SUBSCRIPTION_CATEGORY     varchar(255),
    CH_SALES_METHOD              varchar(50),
    CH_LIST_PRICE                varchar(28),
    CH_QUANTITY                  varchar(28),
    CH_SUBMISSION_DATE           varchar(29),
    CH_SALES_TYPE                varchar(255),
    CL_CREDIT_TYPE_ID            varchar(10),
    CL_STATUS                    varchar(10),
    CL_CREATED_DURING            varchar(10),
    CL_POSTING_STATUS            varchar(10),
    CL_PRE_PROC_CODE             varchar(10),
    CL_COMMISSION_PAYABLE        varchar(28),
    SALE_INCET_NUM               varchar(10),
    BASE_REM                     varchar(28),
    CL_REVENUE_CLASS_ID          varchar(10),
    CL_ERROR_REASON              varchar(10),
    TA_COMMISSION_LINE_ID        varchar(28),
    TA_PAYRUN_ID                 varchar(28),
    TA_PAY_PERIOD_ID             varchar(255),
    TA_QUOTA_RULE_ID             varchar(28),
    TA_QUOTA_ID                  varchar(28),
    TA_PAID_FLAG                 varchar(1),
    X_COMMISSION_HEADER_ID       varchar(28),
    X_PAYMENT_TRANSACTION_ID     varchar(28),
    X_ORDER_NUMBER               varchar(40),
    X_ORDER_LINE_ITEM            varchar(28),
    X_INVOICE_NUMBER             varchar(28),
    X_SERVICE_IDENTIF            varchar(255),
    X_BASE_DATE_FOR_PAYMENT      varchar(29),
    X_APPROVED_DATE              varchar(29),
    X_CREDITED_SALESREP_ID       varchar(255),
    X_DIRECT_SALESREP_ID         varchar(255),
    X_POSTING_DATE_PERIOD        varchar(29),
    X_COMMENTS                   varchar(255),
    X_ACTIVITY_TYPE              varchar(10),
    X_GST_AMOUNT                 varchar(28),
    X_PRECM01_ID                 varchar(10),
    X_COMMISSION_AMOUNT          varchar(28),
    X_QUOTA_ID                   varchar(28),
    X_COMMISSION_TYPE            varchar(255),
    X_PLAN_ELEMENT               varchar(255),
    X_PRODUCT_CATEGORY           varchar(255),
    X_STATUS_FLAG                varchar(10),
    X_STATUS_MSG                 varchar(10),
    CONTRACT_DAYS_REMAINING      varchar(10)
);
