/********************************************************************
  ** TELS_CCG_PARTNER
  **
  ** Version: 1.0
  ** Author: Simon Marsh
  ** Created: June 2018
  ** Description:
  **
  ** Date       Modified By   Description
  ** ------------------------------------------------------------------
  ** 20180619   Simon Marsh   Initial Version
  ********************************************************************/
--DROP TABLE TELS_CCG_PARTNER;
CREATE TABLE TELS_CCG_PARTNER
(
    RESOURCE_ID         varchar(10),
    DEALER_NAME         varchar(127),
    DEALER_START_DATE   varchar(25),
    DEALER_END_DATE     varchar(25),
    CLOSURE_EFFECTIVE_DATE varchar(25),
    PARTNER_ID          varchar(255),
    PARTNER_CODE        varchar(255),
    PARTNER_TYPE        varchar(255),
    PARTNER_TERRITORY   varchar(255),
    SITE                varchar(255),
    STRATEGIC_ROLE      varchar(255),
    PRIORITY            varchar(255),
    VENDOR_CODE         varchar(255),
    SUPER_DISTRIBUTOR   varchar(255),
    PARTNER_CODE_LEVEL  varchar(255),
    GROUP_NAME          varchar(255),
    GROUP_START_DATE    varchar(255),
    GROUP_END_DATE      varchar(255),
    PARENT_GROUP        varchar(255),
    RELATION_START_DATE varchar(255),
    RELATION_END_DATE   varchar(255),
    LAST_UPDATED_DATE   varchar(255),
    ROLE_TYPE           varchar(255),
    ROLE1               varchar(255),
    ROLE1_START_DATE    varchar(255),
    ROLE1_END_DATE      varchar(255),
    ROLE2               varchar(255),
    ROLE2_START_DATE    varchar(255),
    ROLE2_END_DATE      varchar(255),
    ROLE3               varchar(255),
    ROLE3_START_DATE    varchar(255),
    ROLE3_END_DATE      varchar(255),
    ROLE4               varchar(255),
    ROLE4_START_DATE    varchar(255),
    ROLE4_END_DATE      varchar(255),
    ROLE5               varchar(255),
    ROLE5_START_DATE    varchar(255),
    ROLE5_END_DATE      varchar(255),
    ROLE6               varchar(255),
    ROLE6_START_DATE    varchar(255),
    ROLE6_END_DATE      varchar(255),
    ROLE7               varchar(255),
    ROLE7_START_DATE    varchar(255),
    ROLE7_END_DATE      varchar(255),
    ROLE8               varchar(255),
    ROLE8_START_DATE    varchar(255),
    ROLE8_END_DATE      varchar(255),
    ROLE9               varchar(255),
    ROLE9_START_DATE    varchar(255),
    ROLE9_END_DATE      varchar(255),
    ROLE10              varchar(255),
    ROLE10_START_DATE    varchar(255),
    ROLE10_END_DATE      varchar(255),
    ROLE11               varchar(255),
    ROLE11_START_DATE    varchar(255),
    ROLE11_END_DATE      varchar(255),
    ROLE12               varchar(255),
    ROLE12_START_DATE    varchar(255),
    ROLE12_END_DATE      varchar(255),
    ROLE13               varchar(255),
    ROLE13_START_DATE    varchar(255),
    ROLE13_END_DATE      varchar(255),
    ROLE14               varchar(255),
    ROLE14_START_DATE    varchar(255),
    ROLE14_END_DATE      varchar(255),
    ROLE15               varchar(255),
    ROLE15_START_DATE    varchar(255),
    ROLE15_END_DATE      varchar(255),
    ROLE16               varchar(255),
    ROLE16_START_DATE    varchar(255),
    ROLE16_END_DATE      varchar(255),
    ROLE17               varchar(255),
    ROLE17_START_DATE    varchar(255),
    ROLE17_END_DATE      varchar(255),
    ROLE18               varchar(255),
    ROLE18_START_DATE    varchar(255),
    ROLE18_END_DATE      varchar(255),
    ROLE19               varchar(255),
    ROLE19_START_DATE    varchar(255),
    ROLE19_END_DATE      varchar(255),
    ROLE20               varchar(255),
    ROLE20_START_DATE    varchar(255),
    ROLE20_END_DATE      varchar(255)
);
