SELECT * FROM TELS_CORE_DATA_SUMMARY WHERE FILEHANDLERNAME = 'tels_inbound_orderexpress.sh';
SELECT MAX(BATCHPROCESSDATE) PROCESSDATE FROM TELS_INBOUND_FILE_ATTRIBUTES WHERE FILENAME = 'ORDEREXPRESS_MIF_001_COMMISSIONS_20180904_053022_u1637787000016.datx';

SELECT * FROM TELS_CORE_INBOUND_FILE_RUN WHERE FILEHANDLERNAME = 'tels_inbound_orderexpress.sh' ORDER BY INBOUNDFILERUNKEY DESC;

SELECT * FROM TELS_INBOUND_FILE_ATTRIBUTES;
SELECT * FROM TELS_CORE_DATA_SUMMARY;
SELECT * FROM (SELECT BATCHNAME, STARTTIME, ENDTIME FROM TELS_CORE_INBOUND_FILE_RUN ORDER BY STARTTIME DESC) WHERE ROWNUM<10;

SELECT * FROM TELS_ORDEREXPRESS_MIF_PRESTAGE WHERE FILENAME = 'ORDEREXPRESS_MIF_001_COMMISSIONS_20180904_053022_u1637787000016.dat';
SELECT * FROM TELS_ORDEREXPRESS_MIF_STAGE WHERE FILENAME = 'ORDEREXPRESS_MIF_001_COMMISSIONS_20180904_053022_u1637787000016.dat';
SELECT * FROM TELS_CORE_PRESTAGEERROR WHERE FILENAME = 'ORDEREXPRESS_MIF_001_COMMISSIONS_20180904_053022_u1637787000016.dat';

--TRUNCATE TABLE TELS_INBOUND_FILE_ATTRIBUTES;
--TRUNCATE TABLE TELS_ORDEREXPRESS_MIF_STAGE;
--TRUNCATE TABLE TELS_ORDEREXPRESS_MIF_PRESTAGE;
--TRUNCATE TABLE TELS_CORE_PRESTAGEERROR;

SELECT * FROM TELS_INBOUND_FILE_ATTRIBUTES WHERE FILENAME LIKE '%20181026%';
SELECT * FROM TELS_ORDEREXPRESS_MIF_STAGE WHERE FILENAME LIKE '%20181026%';
SELECT * FROM TELS_ORDEREXPRESS_MIF_PRESTAGE WHERE FILENAME LIKE '%20181026%';
SELECT * FROM TELS_CORE_PRESTAGEERROR WHERE FILENAME LIKE '%2018102%';

--DELETE FROM TELS_INBOUND_FILE_ATTRIBUTES WHERE FILENAME LIKE '%20181026%';
--DELETE FROM TELS_ORDEREXPRESS_MIF_STAGE WHERE FILENAME LIKE '%20181026%';
--DELETE FROM TELS_ORDEREXPRESS_MIF_PRESTAGE WHERE FILENAME LIKE '%20181026%';

SELECT count(*) COUNT
FROM TELS_INBOUND_FILE_ATTRIBUTES
WHERE FILENAME = 'ORDEREXPRESS_MIF_001_COMMISSIONS_20180904_053022_u1637787000016.dat';

SELECT * FROM TELS_CORE_FIELDVALIDATION_STD WHERE FIELDNAME = '';
SELECT * FROM TELS_CORE_FIELDVALIDATION_STD WHERE DATEFORMATCHECK is not null;
SELECT * FROM TELS_CORE_FIELDVALUESET_STD;

--UPDATE TELS_CORE_FIELDVALIDATION_STD SET DATEFORMATCHECK = 'dd/mm/yyyy' WHERE DATEFORMATCHECK = 'DD/MM/YYYY';

UPDATE TELS_CORE_FIELDVALIDATION_STD SET DATEFORMATCHECK = '''DD/MM/YYYY''' WHERE DATEFORMATCHECK = 'DD/MM/YYYY';

SELECT * FROM TELS_PERIOD WHERE PERIOD_NAME = 'OCTW2-FY19';

SELECT STRING_AGG(FILENAME) FILES, PERIOD_NAME PERIOD
FROM(
    SELECT distinct fat.FILENAME, tper.PERIOD_NAME
    FROM TELS_INBOUND_FILE_ATTRIBUTES fat
      LEFT OUTER JOIN TELS_PERIOD tper ON
        tper.PERIOD_NAME = 'OCTW2-FY19'
        AND tper.STARTDATE <= TO_DATE(fat.BATCHPROCESSDATE,'DD/MM/YYYY HH24:MI:SS')
        AND tper.ENDDATE > TO_DATE(fat.BATCHPROCESSDATE,'DD/MM/YYYY HH24:MI:SS')
    WHERE EXISTS (SELECT 1 FROM TELS_CORE_INBOUND_FILE_RUN ifr WHERE ifr.BATCHNAME = fat.FILENAME AND ifr.FILEHANDLERNAME = 'tels_inbound_orderexpress.sh')
)GROUP BY PERIOD_NAME
;

DELETE FROM TELS_INBOUND_FILE_ATTRIBUTES WHERE FILENAME LIKE 'ORDEREXPRESS%';