/* MOLI Duplicate Check logic */
SELECT
    PS.FILENAME
  , PS.BATCHPROCESSDATE
  , PS.RECORDNUMBER
  , PS.STATUS_HEADER
  , PS.STATUS_ORDER_LINE_ITEM
  , PS.ROW_ID
FROM TELS_PRESTAGE_RCRM PS
WHERE (1=1)
AND PS.ROW_ID = PS.ROOT_ITEM_ROW_ID
AND PS.FILENAME = 'CCB-RCRM_OrderDataExtract_20190205_060127.dat' -- TOAD
--AND PS.FILENAME = '$$filename' -- INFORMATICA
AND PS.ROW_ID = '1-O89H0UBH'
AND EXISTS (
  SELECT 1
  FROM TELS_RCRM_ROW_SOURCE RS
  WHERE (1=1)
  AND RS.ROW_ID = PS.ROW_ID
  AND CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE RS.STATUS_HEADER END = CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE PS.STATUS_HEADER END
  AND RS.STATUS_ORDER_LINE_ITEM = PS.STATUS_ORDER_LINE_ITEM
  AND RS.FILENAME <> PS.FILENAME
)
;

SELECT --118806, 126025
    Count(*)
FROM TELS_PRESTAGE_RCRM PS
WHERE (1=1)
AND PS.ROW_ID = PS.ROOT_ITEM_ROW_ID
AND PS.FILENAME = 'CCB-RCRM_OrderDataExtract_20190205_060127.dat' -- TOAD
--AND PS.FILENAME = '$$filename' -- INFORMATICA
--AND PS.ROW_ID = '1-O89H0UBH'
AND EXISTS (
  SELECT 1
  FROM TELS_RCRM_ROW_SOURCE RS
  WHERE (1=1)
  AND RS.ROW_ID = PS.ROW_ID
--  AND RS.STATUS_HEADER = PS.STATUS_HEADER
  AND CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE RS.STATUS_HEADER END = CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE PS.STATUS_HEADER END
  AND RS.STATUS_ORDER_LINE_ITEM = PS.STATUS_ORDER_LINE_ITEM
  AND RS.FILENAME <> PS.FILENAME
);

/* OLI Duplicate Check Logic */
SELECT
    PS.FILENAME
  , PS.BATCHPROCESSDATE
  , PS.RECORDNUMBER
  , PS.STATUS_HEADER
  , PS.STATUS_ORDER_LINE_ITEM
  , PS.ROW_ID
  , PS.ROOT_ITEM_ROW_ID
FROM TELS_PRESTAGE_RCRM PS
WHERE (1=1)
AND PS.ROW_ID <> PS.ROOT_ITEM_ROW_ID
AND PS.FILENAME = 'CCB-RCRM_OrderDataExtract_20190205_060127.dat' -- TOAD
--AND PS.FILENAME = '$$filename' -- INFORMATICA
AND PS.ROW_ID = '1-O7YGYAJX'
AND EXISTS (
  SELECT 1
  FROM TELS_RCRM_ROW_SOURCE RS
  WHERE (1=1)
  AND RS.ROW_ID = PS.ROOT_ITEM_ROW_ID
--  AND RS.STATUS_HEADER = PS.STATUS_HEADER
  AND CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE RS.STATUS_HEADER END = CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE PS.STATUS_HEADER END
  AND RS.STATUS_ORDER_LINE_ITEM = PS.STATUS_ORDER_LINE_ITEM
  AND RS.FILENAME <> PS.FILENAME
)
;

SELECT --498688, 531253
    count(*)
FROM TELS_PRESTAGE_RCRM PS
WHERE (1=1)
AND PS.ROW_ID <> PS.ROOT_ITEM_ROW_ID
AND PS.FILENAME = 'CCB-RCRM_OrderDataExtract_20190205_060127.dat' -- TOAD
--AND PS.FILENAME = '$$filename' -- INFORMATICA
--AND PS.ROW_ID = '1-O7YGYAJX'
AND EXISTS (
  SELECT 1
  FROM TELS_RCRM_ROW_SOURCE RS
  WHERE (1=1)
  AND RS.ROW_ID = PS.ROOT_ITEM_ROW_ID
--  AND RS.STATUS_HEADER = PS.STATUS_HEADER
  AND CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE RS.STATUS_HEADER END = CASE WHEN PS.STATUS_ORDER_LINE_ITEM = 'Complete' THEN '1' ELSE PS.STATUS_HEADER END
  AND RS.STATUS_ORDER_LINE_ITEM = PS.STATUS_ORDER_LINE_ITEM
  AND RS.FILENAME <> PS.FILENAME
);

SELECT STATUS_HEADER, STATUS_ORDER_LINE_ITEM FROM TELS_PRESTAGE_RCRM WHERE ROW_ID = '1-O89H0UBH';
SELECT * FROM TELS_RCRM_ROW_SOURCE WHERE ROW_ID = '1-O89H0UBH';