WITH ATTRIBUTES AS(
    SELECT d.FILENAME, d.RECORDNUMBER, d.ORDER_NUMBER, d.ROW_ID ATTRIBUTE_OWNER_ROW_ID, d.ATTRIBUTE_ROW_ID, d.ATTRIBUTE_ACTION_CODE, d.ATTRIBUTE_DISPLAY_NAME, d.ATTRIBUTE_VALUE
    FROM TELS_RCRM_ATTRIBUTES_VIEW d
    WHERE d.ATTRIBUTE_ROW_ID IS NOT NULL)
, FHW_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'FHW_OLI')
, FHW_ASSOC_MOLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'FHW_ASSOC_MOLI')
, FHW_ASSOC_VAS_OLI AS(
    SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE REC_TYPE = 'FHW_ASSOC_VAS_OLI')
, LT_Professional_Install AS(
    SELECT lt.STARTDATE, lt.ENDDATE, lt.DIM_NAME_0, lt.IDX_NAME_0, lt.DIM_NAME_1, lt.IDX_NAME_1, lt.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT lt
    WHERE NAME = 'LT_Professional_Install')
, LT_Plan_VAS_HW_RO AS(
    SELECT lt.STARTDATE, lt.ENDDATE, lt.DIM_NAME_0, lt.IDX_NAME_0, lt.DIM_NAME_1, lt.IDX_NAME_1, lt.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT lt
    WHERE NAME = 'LT_Plan_VAS_HW_RO')
, PASS1 AS(
SELECT
    fo.FILENAME,
    fo.BATCHPROCESSDATE,
    fo.RECORDNUMBER,
    fam.PROVISIONED_DATE PROCESSED_DATE,
    NULL PROCESSED_PERIOD_ID,
    fo.LIST_PRICE TRANSACTION_AMOUNT,
    '1' QUANTITY,
    fam.CUSTOMER_LAST_NAME ATTRIBUTE1,
    fam.CUSTOMER_FIRST_NAME ATTRIBUTE2,
    NULL ATTRIBUTE3,NULL ATTRIBUTE4,NULL ATTRIBUTE5,NULL ATTRIBUTE6,NULL ATTRIBUTE7,NULL ATTRIBUTE8,NULL ATTRIBUTE9,NULL ATTRIBUTE10,NULL ATTRIBUTE11,NULL ATTRIBUTE12,NULL ATTRIBUTE13,NULL ATTRIBUTE14,NULL ATTRIBUTE15,NULL ATTRIBUTE16,NULL ATTRIBUTE17,NULL ATTRIBUTE18,NULL ATTRIBUTE19,NULL ATTRIBUTE20,NULL ATTRIBUTE21,NULL ATTRIBUTE22,NULL ATTRIBUTE23,NULL ATTRIBUTE24,
    fam.ORDER_NUMBER ATTRIBUTE25,
    fam.BILLING_ACCOUNT ATTRIBUTE26,
    fam.PARTNER_CODE ATTRIBUTE27,
    NULL ATTRIBUTE28,NULL ATTRIBUTE29,NULL ATTRIBUTE30,NULL ATTRIBUTE31,NULL ATTRIBUTE32,NULL ATTRIBUTE33,NULL ATTRIBUTE34,
    fam.BUSINESS_UNIT ATTRIBUTE35,
    fam.SALES_FORCE_ID ATTRIBUTE36,
    'COMMISSIONABLE TRANSACTION' ATTRIBUTE37,
    fam.SOURCE_SYSTEM ATTRIBUTE38,
    fam.PRODUCT ATTRIBUTE39,
    NULL ATTRIBUTE40,
    fam.ACTION_CODE ATTRIBUTE41,
    fam.TRANSFER_TYPE ATTRIBUTE42,
    fam.EVENT_SOURCE ATTRIBUTE43,
    fam.PROMOTION_PART_NUMBER ATTRIBUTE44,
    CASE WHEN fam.ORDER_TYPE = 'Modify' AND fam.SUB_ACTION_CODE IN('Transition-Add','Transition-Delete')
         THEN 'Transition'
         ELSE fam.ORDER_SUB_TYPE
         END ATTRIBUTE45,
    fo.ROW_ID ATTRIBUTE46,
    fo.PRODUCT ATTRIBUTE47,
    NULL ATTRIBUTE48,
    fo.ACTION_CODE ATTRIBUTE49,
    fo.PROD_PROM_ID ATTRIBUTE50,
    NULL ATTRIBUTE51,NULL ATTRIBUTE52,
    CASE WHEN lt2.STRINGVALUE IS NOT NULL AND EXISTS(SELECT 1 FROM FHW_ASSOC_VAS_OLI favo 
                                                    JOIN LT_Professional_Install lt1 ON lt1.IDX_NAME_0 = NVL(favo.PART_NUMBER,'NULL') AND lt1.IDX_NAME_1 = 'PI' AND lt1.STRINGVALUE = 'Yes' 
                                                    WHERE favo.ORDER_NUMBER = fo.ORDER_NUMBER AND favo.STATUS_HEADER = fo.STATUS_HEADER AND favo.ROOT_ITEM_ROW_ID = fo.ROOT_ITEM_ROW_ID)
         THEN 'Professional Installation'
         ELSE NULL
         END ATTRIBUTE53,
    NULL ATTRIBUTE54,NULL ATTRIBUTE55,NULL ATTRIBUTE56,NULL ATTRIBUTE57,NULL ATTRIBUTE58,NULL ATTRIBUTE59,
    CASE WHEN fam.ORDER_TYPE = 'Modify' AND fam.SUB_ACTION_CODE IN('Move-Add','Move-Delete')
         THEN 'Move'
         WHEN fam.ORDER_TYPE = 'Modify' AND fam.SUB_ACTION_CODE IN('Transition-Add','Transition-Delete')
         THEN 'Add New Service'
         ELSE fam.ORDER_TYPE 
         END ATTRIBUTE60,
    NULL ATTRIBUTE61,NULL ATTRIBUTE62,NULL ATTRIBUTE63,NULL ATTRIBUTE64,NULL ATTRIBUTE65,NULL ATTRIBUTE66,
    CASE WHEN lt2.STRINGVALUE IS NOT NULL AND EXISTS(SELECT 1 FROM FHW_ASSOC_VAS_OLI favo 
                                                    JOIN LT_Professional_Install lt1 ON lt1.IDX_NAME_0 = NVL(favo.PART_NUMBER,'NULL') AND lt1.IDX_NAME_1 = 'PI' AND lt1.STRINGVALUE = 'Yes' 
                                                    WHERE favo.ORDER_NUMBER = fo.ORDER_NUMBER AND favo.STATUS_HEADER = fo.STATUS_HEADER AND favo.ROOT_ITEM_ROW_ID = fo.ROOT_ITEM_ROW_ID )
         THEN 'N'
         WHEN a2.ATTRIBUTE_VALUE IS NOT NULL
         THEN a2.ATTRIBUTE_VALUE
         WHEN a3.ATTRIBUTE_VALUE IS NOT NULL
         THEN a3.ATTRIBUTE_VALUE
         ELSE fo.HARDWARE_SUPPLIED_FLAG
         END ATTRIBUTE67, 
    NULL ATTRIBUTE68,NULL ATTRIBUTE69,NULL ATTRIBUTE70,NULL ATTRIBUTE71,NULL ATTRIBUTE72,NULL ATTRIBUTE73,NULL ATTRIBUTE74,NULL ATTRIBUTE75,NULL ATTRIBUTE76,NULL ATTRIBUTE77,
    CASE WHEN fo.HARDWARE_ASSOCIATION_ID IS NOT NULL 
         THEN 'With HRO'
         WHEN fo.HARDWARE_ASSOCIATION_ID IS NULL 
         THEN 'Without HRO'
         END ATTRIBUTE78,
    NULL ATTRIBUTE79,NULL ATTRIBUTE80,
    fo.PART_NUMBER ATTRIBUTE81,
    NULL ATTRIBUTE82,NULL ATTRIBUTE83,NULL ATTRIBUTE84,NULL ATTRIBUTE85,NULL ATTRIBUTE86,NULL ATTRIBUTE87,
    fo.COMMISSION_PRODUCT_TYPE ATTRIBUTE88,
    NULL ATTRIBUTE89,NULL ATTRIBUTE90,NULL ATTRIBUTE91,NULL ATTRIBUTE92,NULL ATTRIBUTE93,NULL ATTRIBUTE94,NULL ATTRIBUTE95,NULL ATTRIBUTE96,NULL ATTRIBUTE97,NULL ATTRIBUTE98,NULL ATTRIBUTE99,NULL ATTRIBUTE100,
    NULL LAST_UPDATE_DATE,NULL CREATION_DATE,
    fam.CREATED_DATE BOOKED_DATE,
    'REVENUE' REVENUE_TYPE,
    NULL TYPE,NULL EMPLOYEE_NUMBER,NULL RECORD_STATUS,NULL ERROR_TYPE,NULL ERROR_MSG,
    fo.SOURCE_SYSTEM SOURCE,
    fam.SUBMITTED_DATE SUBMITTED_DATE,
    fam.STATUS_HEADER STATUS_HEADER,
    fam.STATUS_ORDER_LINE_ITEM STATUS_ORDER_LINE_ITEM,
    fam.ORIGINAL_ORDER_NUMBER,
    CASE WHEN EXISTS(SELECT 1 FROM LT_Plan_VAS_HW_RO lt WHERE lt.IDX_NAME_0 = NVL(fo.PART_NUMBER,'NULL') AND lt.STARTDATE <= TO_DATE(NVL(fo.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt.ENDDATE > TO_DATE(NVL(fo.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss'))
         THEN 1 
         ELSE 0
         END LT_Plan_VAS_HW_RO_Exists,
    a1.ATTRIBUTE_ROW_ID FO_HW_ORDER_TYPE
FROM 
  FHW_OLI fo
  LEFT OUTER JOIN FHW_ASSOC_MOLI          fam ON fam.ORDER_NUMBER = fo.ORDER_NUMBER AND fam.STATUS_HEADER = fo.STATUS_HEADER AND fam.ROW_ID = fo.ROOT_ITEM_ROW_ID
  LEFT OUTER JOIN LT_Professional_Install lt2 ON lt2.IDX_NAME_0 = NVL(fo.PART_NUMBER,'NULL') AND lt2.IDX_NAME_1 = 'PIK' AND lt2.STRINGVALUE = 'Yes' AND lt2.STARTDATE <= TO_DATE(NVL(fo.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss') AND lt2.ENDDATE > TO_DATE(NVL(fo.EFFECTIVE_DATE, '01/01/2200 00:00:00'),'dd/mm/yyyy hh24:mi:ss')
  LEFT OUTER JOIN ATTRIBUTES a1 ON a1.ATTRIBUTE_OWNER_ROW_ID = fo.ROW_ID AND a1.ORDER_NUMBER = fo.ORDER_NUMBER AND a1.ATTRIBUTE_DISPLAY_NAME = 'Hardware Order Type' AND a1.ATTRIBUTE_VALUE = 'Repayment Option for Device or Service'
  LEFT OUTER JOIN ATTRIBUTES a2 ON a2.ATTRIBUTE_OWNER_ROW_ID = fo.ROW_ID AND a2.ORDER_NUMBER = fo.ORDER_NUMBER AND a2.ATTRIBUTE_DISPLAY_NAME = 'Supplied in Store?'
  LEFT OUTER JOIN ATTRIBUTES a3 ON a3.ATTRIBUTE_OWNER_ROW_ID = fo.ROW_ID AND a3.ORDER_NUMBER = fo.ORDER_NUMBER AND a3.ATTRIBUTE_DISPLAY_NAME = 'Hardware Supplied'
WHERE NVL(fo.ORDER_SUB_TYPE,'NULL') <> 'Transfer' 
--and fo.ROW_ID = '1-NVCJQ0GB';
)
SELECT
    p1.FILENAME,p1.BATCHPROCESSDATE,p1.RECORDNUMBER,p1.PROCESSED_DATE,p1.PROCESSED_PERIOD_ID,p1.TRANSACTION_AMOUNT,p1.QUANTITY,p1.ATTRIBUTE1,p1.ATTRIBUTE2,p1.ATTRIBUTE3,p1.ATTRIBUTE4,p1.ATTRIBUTE5,p1.ATTRIBUTE6,p1.ATTRIBUTE7,p1.ATTRIBUTE8,p1.ATTRIBUTE9,p1.ATTRIBUTE10,
    p1.ATTRIBUTE11,p1.ATTRIBUTE12,p1.ATTRIBUTE13,p1.ATTRIBUTE14,p1.ATTRIBUTE15,p1.ATTRIBUTE16,p1.ATTRIBUTE17,p1.ATTRIBUTE18,p1.ATTRIBUTE19,p1.ATTRIBUTE20,p1.ATTRIBUTE21,p1.ATTRIBUTE22,p1.ATTRIBUTE23,p1.ATTRIBUTE24,p1.ATTRIBUTE25,p1.ATTRIBUTE26,p1.ATTRIBUTE27,p1.ATTRIBUTE28,
    p1.ATTRIBUTE29,p1.ATTRIBUTE30,p1.ATTRIBUTE31,p1.ATTRIBUTE32,p1.ATTRIBUTE33,p1.ATTRIBUTE34,p1.ATTRIBUTE35,p1.ATTRIBUTE36,p1.ATTRIBUTE37,p1.ATTRIBUTE38,p1.ATTRIBUTE39,p1.ATTRIBUTE40,p1.ATTRIBUTE41,p1.ATTRIBUTE42,p1.ATTRIBUTE43,p1.ATTRIBUTE44,p1.ATTRIBUTE45,p1.ATTRIBUTE46,
    p1.ATTRIBUTE47,p1.ATTRIBUTE48,p1.ATTRIBUTE49,p1.ATTRIBUTE50,p1.ATTRIBUTE51,p1.ATTRIBUTE52,p1.ATTRIBUTE53,p1.ATTRIBUTE54,p1.ATTRIBUTE55,p1.ATTRIBUTE56,p1.ATTRIBUTE57,p1.ATTRIBUTE58,p1.ATTRIBUTE59,p1.ATTRIBUTE60,p1.ATTRIBUTE61,p1.ATTRIBUTE62,p1.ATTRIBUTE63,p1.ATTRIBUTE64,
    p1.ATTRIBUTE65,p1.ATTRIBUTE66,p1.ATTRIBUTE67,p1.ATTRIBUTE68,p1.ATTRIBUTE69,p1.ATTRIBUTE70,p1.ATTRIBUTE71,p1.ATTRIBUTE72,p1.ATTRIBUTE73,p1.ATTRIBUTE74,p1.ATTRIBUTE75,p1.ATTRIBUTE76,p1.ATTRIBUTE77,
    CASE WHEN p1.LT_Plan_VAS_HW_RO_Exists = 1
         THEN CASE WHEN p1.FO_HW_ORDER_TYPE IS NOT NULL
                   THEN 'With RO'
                   WHEN p1.FO_HW_ORDER_TYPE IS NULL
                   THEN 'Without RO'
                   END
         ELSE p1.ATTRIBUTE78
         END ATTRIBUTE78,
    p1.ATTRIBUTE79,p1.ATTRIBUTE80,p1.ATTRIBUTE81,p1.ATTRIBUTE82,p1.ATTRIBUTE83,p1.ATTRIBUTE84,p1.ATTRIBUTE85,p1.ATTRIBUTE86,p1.ATTRIBUTE87,p1.ATTRIBUTE88,p1.ATTRIBUTE89,p1.ATTRIBUTE90,
    p1.ATTRIBUTE91,p1.ATTRIBUTE92,p1.ATTRIBUTE93,p1.ATTRIBUTE94,p1.ATTRIBUTE95,p1.ATTRIBUTE96,p1.ATTRIBUTE97,p1.ATTRIBUTE98,p1.ATTRIBUTE99,p1.ATTRIBUTE100,
    p1.LAST_UPDATE_DATE,p1.CREATION_DATE,p1.BOOKED_DATE,p1.REVENUE_TYPE,p1.TYPE,p1.EMPLOYEE_NUMBER,p1.RECORD_STATUS,p1.ERROR_TYPE,p1.ERROR_MSG,p1.SOURCE,p1.FILENAME,p1.RECORDNUMBER,p1.SUBMITTED_DATE,p1.STATUS_HEADER,p1.STATUS_ORDER_LINE_ITEM,p1.ORIGINAL_ORDER_NUMBER
FROM PASS1 p1
;

SELECT * FROM TELS_RCRM_ORDERS_VIEW WHERE ORDER_NUMBER = '1-1870609348233';

    SELECT lt.STARTDATE, lt.ENDDATE, lt.DIM_NAME_0, lt.IDX_NAME_0, lt.DIM_NAME_1, lt.IDX_NAME_1, lt.STRINGVALUE
    FROM TELS_RCRM_MV_MDLT lt
    WHERE NAME = 'LT_Professional_Install' AND lt.IDX_NAME_0 IN('XC001007322','XC001000861');
    
SELECT * FROM TELS_PRESTAGE_RCRM WHERE ROW_ID = '1-NVCJQ0GB';